### ISSUE TITLE
Provide FCM integration

### ISSUE THREAD

**Issue by nilsonpontello** [firebase/firebase-admin-java#101]
> This API is currently only available for the Admin Node.js SDK. 

It would be great having it here as well. Is it somehow on the roadmap?

https://firebase.google.com/docs/cloud-messaging/admin/

**Comment by hiranya911** [comment]
@nilsonpontello Definitely on the roadmap. No specific release date yet, but it's coming soon.

**Comment by hiranya911** [comment]
This was released today: https://firebase.google.com/support/release-notes/admin/java#5.9.0
