### ISSUE TITLE
idle connection close 

### ISSUE THREAD

**Issue by stager0909** [firebase/firebase-admin-java#1028]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: ubuntu
  * Firebase SDK version: firebase-admin-java 9.4.0
  * Library version: jdk 17
  * Firebase Product: fcm (auth, database, storage, etc)

#### Steps to reproduce:

I am testing with firebase-admin-java 9.4.0.
Since communication is via HTTP/2, I expected the connection to remain open if there were no issues. However, after making a request, if there are no additional requests, the connection is dropped after about 3 minutes.
The strange part is that the entity sending the FIN packet is not the client, but the FCM server.
Is there any specific reason why the server is sending a FIN packet and closing the connection, even though it's using HTTP/2?

![image](https://github.com/user-attachments/assets/3c607be7-a31c-4599-b72d-685b68b2954a)

**Comment by fwadnjar142** [comment]
https://github.com/firebase/firebase-admin-java/issues/1028#issuecomment-2437267762
