### ISSUE TITLE
FirebaseAuthException: IO error while creating user account

### ISSUE THREAD

**Issue by adtoday** [firebase/firebase-admin-java#103]
* Operating System version: Google appengine standard environment (Java 7)
  * Firebase SDK version: 5.5.0
  * Library version: 5.5.0?
  * Firebase Product: Auth API

I'm trying to create a user through the Authentication API. However, I'm always receiving an ExecutionException with the message:
com.google.firebase.auth.FirebaseAuthException: IO error while creating user account

I do not fully understand the message. However, I have tried all the following:
1) Tried to read credentials from json service account file/key
2) Tried to setDatabaseUrl (even though I believe it's not needed, as I'm only using authentication API)
3) Tried all different combinations and data for user when creating

----

Below are the relevant pieces of code:
A) Initializing the FirebaseApp:

```
public class FirebaseService {

	private static final String projectId = "HIDDEN"; //hidden for reporting issue only
	
    static {
        try {
           // InputStream is = new FileInputStream(
                //    new File("WEB-INF/service-account-credentials.json"));
            FirebaseOptions options = new FirebaseOptions.Builder()
                    .setCredentials(GoogleCredentials.getApplicationDefault())
                    //.setDatabaseUrl("https://"+projectId+".firebaseio.com")
                    .setProjectId(projectId)
                    .build();

            FirebaseApp.initializeApp(options);

        } catch (Exception e) {
            SimpleLogger.log(Level.SEVERE, e.toString(), e);
        }
    }

    ...

```

B) Creating the user: (in a method)
```
CreateRequest request = new CreateRequest()
    		    .setEmail(manager.email) //tried different emails. Valid format
    		    //.setEmailVerified(false) //tried with and without, and true/false
    		   // .setPassword("LsjaA76as%Asd"); //for testing purposes, tried with and without
    		    .setPhoneNumber(manager.phone) //valid format. Tried without as well
    		    .setDisplayName(manager.name) //English letters only
    		    //.setPhotoUrl("http://www.example.com/12345678/photo.png") //tried with and without
    		    .setDisabled(!manager.active); //tried with and without
    	
    	try {
			UserRecord userRecord = FirebaseAuth.getInstance().createUserAsync(request).get();
			return userRecord.getUid();
			
		} catch (InterruptedException | ExecutionException e) {
			throw new ServiceUnavailableException("Could not create user: " + e.getMessage());
		}
```

Note:
The verify token does work:
FirebaseAuth.getInstance().verifyIdTokenAsync(token).get();

-----

Am I doing something wrong?

**Comment by hiranya911** [comment]
This type of issues are almost always configuration problems. Please share a full stack trace.

**Comment by adtoday** [comment]
Actually, I feel so stupid now. I probably rushed into posting the question, but sometimes you get a blocking in your head.. I just needed a sleep.
The project that was making requests to create the user on google app engine, was different than the project registered in firebase as we have 2 different projects that we want to integrate with firebase, and we can not make them as services. This is of course a different issue and not related to the SDK. My appologies. Thank you Hiranya.

Best

**Comment by hiranya911** [comment]
Glad you figured it out. Thanks for the update. :+1:
