### ISSUE TITLE
Firestore large batch writes not working

### ISSUE THREAD

**Issue by Klabauterman** [firebase/firebase-admin-java#106]
I am using this admin sdk version 5.5.0 with the new firestore. I was making batch writes and noticing that larger ones (1000 documents) were not working. The listener of the apifuture gets called, but the objects are just not in my store. With smaller batches (500 documents)  it seems to work. I tried to find a maximum batch size or timeout in the documentation but with no success.

**Comment by hiranya911** [comment]
Thanks @Klabauterman for reporting this. Can you please also share a minimal code snippet that we can use to reproduce this?

**Comment by schmidt-sebastian** [comment]
The limit for batch sizes is 500. We will add this to our documentation.

You should see this reflected in the error message you get from the backend:

```
java.util.concurrent.ExecutionException: com.google.api.gax.rpc.InvalidArgumentException: io.grpc.StatusRuntimeException: INVALID_ARGUMENT: cannot write more than 500 entities in a single call
```

**Comment by phingers** [comment]
So I'm trying to write 2500 records into the system, and I batch them in firestore rules at 500 each, but they dont seem to be firing off. How do you recommend we do the batches?

**Comment by schmidt-sebastian** [comment]
Can you share a code snippet and explain the behavior that you are seeing? Does the AsyncFuture we return never resolve?

You can see how we use WriteBatches here: https://github.com/GoogleCloudPlatform/google-cloud-java/blob/master/google-cloud-firestore/src/test/java/com/google/cloud/firestore/it/ITSystemTest.java#L495

Furthermore, can you go into a little more detail as to how you have configured your rules. Thanks!

**Comment by phingers** [comment]
The below code doesnt show any errors, and prints out

Committed 436
Committed 500
Committed 500
Committed 500
Committed 500

But no actual records are written to the firestore. 

Obviously I'm new to firestore, and it has to be something simple right?

You can see the batch call I have commented as well, that I put with batch.set() or batch.delete() wrappers around the lines as well.

```
//let batch = admin.firestore().batch();
    const chunks = chunk(searchAddRecords, 500);

    for (const searchRecords of chunks) {
      const promisedUpdates = searchRecords.map(record => {
        //let batch = admin.firestore().batch();
        //console.log(record,searchObject,uid)

        if (record.type == "delete") {
          admin.firestore()
            .collection("search")
            .doc(record.start.toString())
            .collection(record.end.toString())
            .doc(uid);
        } else {
          admin.firestore()
            .collection("search")
            .doc(record.start.toString())
            .collection(record.end.toString())
            .doc(uid).set(searchObject);
        }
        // batch.commit().then(function() {
        //   return true;
        // });
      });
      await Promise.all(promisedUpdates);
      console.log(`Committed ${searchRecords.length}`);
    }
```

**Comment by schmidt-sebastian** [comment]
Your commented out code look as such:

```
    const chunks = chunk(searchAddRecords, 500);
    for (const searchRecords of chunks) {
      const promisedUpdates = searchRecords.map(record => {
        if (record.type == "delete") {
          admin.firestore()
            .collection("search")
            .doc(record.start.toString())
            .collection(record.end.toString())
            .doc(uid);  
        } else {
          admin.firestore()
            .collection("search")
            .doc(record.start.toString())
            .collection(record.end.toString())
            .doc(uid).set(searchObject);
        }
      });
      await Promise.all(promisedUpdates);
      console.log(`Committed ${searchRecords.length}`);
    }
```

You seem to have some issues here:
- The first if branch (the delete) doesn't actually call `delete()`.
- You are not waiting on the promises (you need to return them).
- You are initializing Firestore multiple times. While this is more of a performance issue, you should only call `firebase.admin()` once (this constructor does a bunch of work, such as obtaining authentication credentials).

If you want to use a batch, you need to re-arrange your code as such:

```
    let firestore =  admin.firestore();
    let batch = firestore.batch();
    const chunks = chunk(searchAddRecords, 500);

    for (const searchRecords of chunks) {
       const promisedUpdates = searchRecords.map(record => {
       console.log(record,searchObject,uid)

       if (record.type == "delete") {
          batch.delete(firestore.collection("search").doc(record.start.toString())
             .collection(record.end.toString()).doc(uid));
        } else {
          batch.set(firestore.collection("search").doc(record.start.toString())
             .collection(record.end.toString()).doc(uid));
        }
        return batch.commit();
      });

      await Promise.all(promisedUpdates);
      console.log(`Committed ${searchRecords.length}`);
    }
```

You need to append the writes manually to the batch and then commit (and return the result from this commit as well).

**Comment by hiranya911** [comment]
@phingers This is the wrong place to have this discussion. Please use Stackoverflow or firebase-talk Google group for usage questions. This Github repo is for discussing SDK implementation issues for the "Java" Admin SDK.
