### ISSUE TITLE
FR: Limited Service accounts

### ISSUE THREAD

**Issue by fecogc** [firebase/firebase-admin-java#124]
This is more a request, can Google create a role so only read is allowed for a Service Account?

Please see https://stackoverflow.com/questions/48218045/firebase-limited-service-account

**Comment by hiranya911** [comment]
You can set specific roles/permissions on a service account via IAM: https://cloud.google.com/iam/docs/understanding-service-accounts#granting_minimum_permissions_to_service_accounts

The default service account you get from Firebase console has full access to all Firebase services.
