### ISSUE TITLE
Allow control of the URL prefix for googleapis.com API calls

### ISSUE THREAD

**Issue by dimipaun** [firebase/firebase-admin-java#134]
Hi guys,

We need to operate in a corporate environment that severely restricts access to the wider internet. Trying to white-label all googleapis.com IPs is a fools errand (there are _a lot_ of them, and likely to change). 

The best way would be allow us to control the prefix of the URLs to googleapis.com calls so that for example we can direct them via a https://googleapis.example.com/ proxy that is under out control. 

This is a big problem for us right now as we are at the point where we're trying to deploy this in production for a very large client and we've hit a wall on how we can get this done.

Thank you!

**Comment by hiranya911** [comment]
This is what the [`setHttpTransport()`](https://firebase.google.com/docs/reference/admin/java/reference/com/google/firebase/FirebaseOptions.Builder.html#setHttpTransport(com.google.api.client.http.HttpTransport)) API is for:

```
Proxy proxy = new Proxy(Proxy.Type.HTTP, 
    new InetSocketAddress("my-proxy-host", myProxyPort))
FirebaseOptions options =
          new FirebaseOptions.Builder()
              .setCredentials(loadCredentials())
              .setHttpTransport(new NetHttpTransport.Builder()
                  .setProxy(proxy)
                  .build())
              .build();
```

Alternatively, use the HTTP proxy support built into the JVM: https://docs.oracle.com/javase/8/docs/technotes/guides/net/proxies.html
