### ISSUE TITLE
firebase-admin exposes unstable APIs

### ISSUE THREAD

**Issue by garrettjonesgoogle** [firebase/firebase-admin-java#144]
Hello,

An issue was filed against google-cloud-java ( https://github.com/GoogleCloudPlatform/google-cloud-java/issues/2890 ) because users are having trouble with version consistency. It turns out that firebase-admin added types from google-cloud-java onto its surface in this PR:

https://github.com/firebase/firebase-admin-java/pull/83

Since google-cloud-firestore is beta, this means that firebase-admin is now exposing unstable types on its surface, which could break users between minor versions despite any promises of API stability within this repo.

**Comment by hiranya911** [comment]
This was understood when we took the dependency and decided to expose the Firestore API as part of the Admin SDK. We usually pin the Firestore dependency to specific versions, and do controlled releases. This doesn't fully solve the problem, but at least gives more visibility into the potential issues.

**Comment by hiranya911** [comment]
Now that Firestore is GA, I think we can close this.
