### ISSUE TITLE
FR: Expose mutable_content property in iOS Notifications API

### ISSUE THREAD

**Issue by wsimf** [firebase/firebase-admin-java#155]
* Operating System version: Any
  * Firebase SDK version: 5.9.0
  * Library version: Latest
  * Firebase Product: notifications

Please provide an API for setting the `mutable_content` property for iOS in Firebase Notifications.
`com.google.firebase.messaging.Aps` class exposes some some properties like `content-available` but not `mutable_content`. 

`mutable_content` property is important for processing notifications in an `UNNotificationServiceExtension`. 

[Apple docs](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/ModifyingNotifications.html)

**Comment by hiranya911** [comment]
I have an action item to implement this across all Admin SDKs. Will include it in an upcoming release.
