### ISSUE TITLE
Error Response with zero content throws NullPointerException

### ISSUE THREAD

**Issue by funkybookends** [firebase/firebase-admin-java#166]
Hello, 

When a response comes back with an erred status code com.google.firebase.messaging.FirebaseMessaging#handleSendHttpError attempts to read the body, however if the content is null, the jsonFactory throws a NullPointerException, which is not converted into a FirebaseMessagingException. This ends up hiding the http response code.

In the tests, there is a test for testSendError, but there is no test that uses .setZeroContent() which will expose the problem.

To reproduce, send a mock response with an error status code and no content.

**Comment by hiranya911** [comment]
@funkybookends Does this scenario actually occur in practice (with the actual FCM service), or is it just a precaution? If it does happen, can you share the details on how to repro it?

**Comment by funkybookends** [comment]
We have seen it a few times. We don't know what caused it, and we can't see the status code to know more. At the point where this happens the request has completely failed, so there's not much that can be done anyway. 

To reproduce, just mock a non 2XX response with zero content.
