### ISSUE TITLE
FirebaseDatabase not working in versions >= 6.0.0 in Google App Engine

### ISSUE THREAD

**Issue by engeeaitch** [firebase/firebase-admin-java#177]
* Operating System version: Google App Engine, running Java 8
  * Firebase SDK version: 6.0.0 or 6.1.0
  * Library version: _____
  * Firebase Product: database

My web app runs on Google App Engine.  I initialise the App:

        try {
            FirebaseApp.initializeApp(options);
        }
        catch(Exception error){
            Log.info("FirebaseApp already initialised");
            return;
        }

and get a reference to the database:

        DatabaseReference ref = FirebaseDatabase.getInstance().getReference();
        Log.info("Database ref obtained.");

I then listen for children in the database:

        ref.addChildEventListener(new ChildEventListener() {
            @Override
            public void onChildAdded(DataSnapshot dataSnapshot, String s) {
                Log.info("Child Added");
                //Do stuff here
            }
        });

I already have an entry in the database.  On starting my webapp using version 5.11.0 the child event listener fires immediately.  On repeating this using version 6.0.0 or 6.1.0 the event listener never fires.

Is there something special about GAE and version 6.0.0?

**Comment by hiranya911** [comment]
Works fine in our tests. What scaling mode are you using?

**Comment by hiranya911** [comment]
I just double checked to be sure, and it worked as expected. I'm using SDK v6.1.0 on java8 runtime with manual scaling. My code is not too different from yours. I have the following in a servlet context listener:

```
    FirebaseApp.initializeApp(options);
    FirebaseDatabase database = FirebaseDatabase.getInstance();
    database.getReference().child("foo").addChildEventListener(new ChildEventListener() {
      @Override
      public void onChildAdded(DataSnapshot dataSnapshot, String s) {
        logger.info("Data value added: " + dataSnapshot.getValue());
        Status.getInstance().notifyUpdate();
      }
      ....
    });
```

In addition to the expected output in my servlets, I've also enabled debug logging. I see the following getting logged in the App Engine console:

```
2018-05-16 20:45:25.762 PDT
com.google.firebase.database.connection.WebsocketConnection handleNewFrameCount: [ws_0] Handle new frame count: 1 (WebsocketConnection.java:152)
2018-05-16 20:45:25.762 PDT
com.google.firebase.database.connection.WebsocketConnection appendFrame: [ws_0] Parsed complete frame: {t=d, d={r=2, b={d={}, s=ok}}} (WebsocketConnection.java:165)
2018-05-16 20:45:25.762 PDT
com.google.firebase.database.connection.Connection onDataMessage: [conn_0] Received data message: {r=2, b={d={}, s=ok}} (Connection.java:150)
2018-05-16 20:45:25.762 PDT
com.google.firebase.database.core.view.EventRaiser$1 run: Raising /foo: CHILD_ADDED: { child1: value0 } (EventRaiser.java:54)
2018-05-16 20:45:25.835 PDT
com.test.AppListener$1 onChildAdded: Data value added: value0 (AppListener.java:53)
```

I would also recommend you to try enabling debug logs and inspect the output.

```
# logging.properties
.level=INFO
com.google.firebase.level=FINE
java.util.logging.SimpleFormatter.format='%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS %4$s %2$s %5$s%6$s%n'
```

```
<-- appengine-web.xml -->
<system-properties>
        <property name="java.util.logging.config.file" value="WEB-INF/logging.properties"/>
</system-properties>
```

**Comment by engeeaitch** [comment]
Hi Hiranya,
Thanks for your help. I have tried to set the debug logs you suggested with no success.  However, the one thing I have discovered is that for versions >= 6.0.0, there is no /_ah/background entry appearing in the GAE log - it's in here that I should see the Child Added event (and where it appears for version 5.11.0).  Are you able to point me in the right direction please?

P.S. I'm using Manual Scaling, with one B1 instance.  Thanks.

**Comment by hiranya911** [comment]
The latest SDK does not use background threads, so the lack of `/_ah/background` requests is to be expected. To enable debug logs, make sure to also add the `slf4j-jdk14` to the classpath:

```
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-jdk14</artifactId>
            <version>1.7.25</version>
        </dependency>
```

**Comment by engeeaitch** [comment]
Hi Hiranya,
I'm struggling with this one - I can't help think that this is something to do with not having background threads, but I don't know where to look.  Are there any changes necessary to move from 5.11.0 to 6.0.0? Anyway, I added the slf4j-jdk14 to the class path, and now have some logging appearing, but it doesn't look very interesting:

![gae log](https://user-images.githubusercontent.com/5493363/40270417-f3f9eb48-5b84-11e8-93be-67319d56b7b4.PNG)

Any help gratefully received.

**Comment by hiranya911** [comment]
The SDK no longer needs or tries to start background threads. You should make sure you're indeed running on GAE java8 runtime. 6.x will not work on java7 runtime, which is one way of explaining your current predicament. I see the proactive token refresher going hot in your log -- which happens during RTDB initialization -- so it is doing something. Perhaps you can share a minimal code sample which we can use to repro the problem?

**Comment by hiranya911** [comment]
Also note that Cloud Console does not do a great job at displaying debug logs. Sometimes log statements get folded under other request log entries. You might have to click on certain log entries to expand them. Also make sure to select "All Logs" in the drop down at the top. See below...

<img width="1331" alt="screen shot 2018-05-19 at 12 55 31 pm" src="https://user-images.githubusercontent.com/2375201/40272563-191868e4-5b64-11e8-9e25-fd38ac612e6c.png">

**Comment by engeeaitch** [comment]
Hi Hiranya,

Thanks for your suggestions.  Java runtime is Java8 (as reported by App Engine Versions console).
I have written a cut down version of my program here:

```
public class Startup implements ServletContextListener {
    private static final Logger Log = Logger.getLogger(com.gmail.reallycleverapps.trafficalarm.Startup.class.getName());

    @Override
    public void contextInitialized(ServletContextEvent sce) {
        Log.info("Listener started");
        //Get a FirebaseApp instance
        FileInputStream refreshToken;
        try {
            refreshToken = new FileInputStream("WEB-INF/FirebaseAdminKey.json");
        } catch (Exception error) {
            Log.warning("Error accessing Firebase refresh token: " + error);
            //No point in continuing
            return;
        }
        FirebaseOptions options;
        try {
            options = new FirebaseOptions.Builder()
                    .setCredentials(GoogleCredentials.fromStream(refreshToken))
                    .setDatabaseUrl(MyGoogleConstants.FB_DB_URL)
                    .build();
        } catch (Exception error) {
            Log.warning("Error setting Firebase Options: "+error);
            //No point in continuing if this fails
            return;
        }

        try {
            FirebaseApp.initializeApp(options);
        }
        catch(Exception error){
            Log.info("Unable to initialise");
            return;
        }

        DatabaseReference ref = FirebaseDatabase.getInstance().getReference();
        Log.info("Database ref obtained.");

        ref.addChildEventListener(new ChildEventListener() {
            @Override
            public void onChildAdded(DataSnapshot dataSnapshot, String s) {
                Log.info("Child Added");
                //Do other stuff
            }

            @Override
            public void onChildChanged(DataSnapshot dataSnapshot, String s) {
                Log.info("Child Changed: "+dataSnapshot.getKey());
                //Process the changes
            }

            @Override
            public void onChildRemoved(DataSnapshot dataSnapshot) {
                //Don't care - nothing to do
                Log.info("Child Removed");
            }

            @Override
            public void onChildMoved(DataSnapshot dataSnapshot, String s) {
                //Don't care - nothing to do
                Log.info("Child Moved");
            }

            @Override
            public void onCancelled(DatabaseError databaseError) {
                Log.warning("Error obtaining data from db: "+databaseError);
            }
        });
    }

    @Override
    public void contextDestroyed(ServletContextEvent sce){
        Log.info("Listener stopped");
    }
}
```
And here is the log when I run under 6.1.0:
![log w 6 1 0](https://user-images.githubusercontent.com/5493363/40276507-e7d57c40-5c03-11e8-918d-52c37bace2f9.PNG)

And here is the log when I run exactly the same program under 5.11.0 (I've highlighted the entry where the database entry changed:
![log w 5 11 0](https://user-images.githubusercontent.com/5493363/40276510-f8d44774-5c03-11e8-9746-443d7e91a28d.PNG)

**Comment by hiranya911** [comment]
@engeeaitch Just tried your code. Here's what I got:

<img width="994" alt="screen shot 2018-05-20 at 12 42 27 am" src="https://user-images.githubusercontent.com/2375201/40276744-ea020480-5bc6-11e8-9214-4b91a4e28a60.png">

I think it's working in your case too. It's just the logging behavior in App Engine has changed with the latest version of the SDK. 

In the past versions, the SDK used background threads. This means your RTDB event handlers used to fire on background threads, and the logs generated by your code got folded under `/_ah/background` requests in the console. But with the latest SDK, background threads are no longer in the picture. And App Engine does not do a good job at capturing the log statements produced by regular, non-background threads. To see them you need to send another request to your app. In my case, I have a servlet endpoint (`/hello`) in my app. App Engine console folds RTDB log entries under the `/hello` requests. For example:

**I too don't get any interesting logs under the initial `/_ah/start` request (same as yours):**

<img width="1327" alt="screen shot 2018-05-20 at 12 54 44 am" src="https://user-images.githubusercontent.com/2375201/40276823-a1a9ae84-5bc8-11e8-99b9-6c2124b336a6.png">

**All the interesting logs get folded under `/hello` instead:**

<img width="1340" alt="screen shot 2018-05-20 at 12 49 56 am" src="https://user-images.githubusercontent.com/2375201/40276783-c0df7726-5bc7-11e8-828f-29f1e85b98c1.png">

This is probably what's going on in your app too. Send a few requests to your app, and inspect the log entries for those requests. Or implement some other means of verifying the functionality. One trick I often employ during testing is to update a static counter in each of my event listeners and then querying those counter values via a servlet. 

It's unfortunate that App Engine console doesn't handle async log entries well. But the SDK and your code is functioning correctly AFAICT.

**Comment by engeeaitch** [comment]
@hiranya911 Thank you - you are correct - by running the /hello page, I can see the entries in the logs.  How confusing!!!.
Anyway, my problem now is that when a database entry is found, this block of code is called but is not working (but works fine in 5.11.0):

```
        Queue queue = QueueFactory.getQueue(Constants.GET_DEPARTURE_TIME_QUEUE);
        Gson gson = new Gson();
        String json = gson.toJson(alarm);

        queue.add(TaskOptions.Builder.withUrl("/getDepartureTimeWorker")
                .param("dbKey", dbKey)
                .param("alarm", json)
                //.countdownMillis(delay));
                .countdownMillis(1000000)); //Test value to ensure that item can be seen on queue
```
With version 6.1.0 I can't see any errors in the logs, but when I look at the queue count in the console, it is empty (but not for 5.11.0).

**Comment by hiranya911** [comment]
I didn't try this in cloud, but just using the local dev app server and some additional logging in the code I get:

```
[INFO] INFO: Child Added
[INFO] May 20, 2018 11:04:20 AM com.test.Startup$1 onChildAdded
[INFO] WARNING: Error while enqueue: Can't make API call taskqueue.BulkAdd in a thread that is neither the original request thread nor a thread created by ThreadManager
```

You can't call `com.google.appengine.api.*` APIs on regular threads. This limitation is documented in https://cloud.google.com/appengine/docs/standard/java/runtime-java8#threads. It might get fixed in a future iteration of the App Engine SDK. In the meantime, if you wish to access GAE APIs from RTDB threads, you will have to switch your logic on to a background thread by specifying a custom [`ThreadManager`](https://firebase.google.com/docs/reference/admin/java/reference/com/google/firebase/FirebaseOptions.Builder.html#setThreadManager(com.google.firebase.ThreadManager)).

```
      ThreadManager threadManager = new ThreadManager() {
        @Override
        protected ExecutorService getExecutor(FirebaseApp app) {
          return Executors.newCachedThreadPool();
        }

        @Override
        protected void releaseExecutor(FirebaseApp app, ExecutorService executor) {
          executor.shutdown();
        }

        @Override
        protected ThreadFactory getThreadFactory() {
          // use GAE background thread factory
          return com.google.appengine.api.ThreadManager.backgroundThreadFactory();
        }
      };
      options = new FirebaseOptions.Builder()
          .setCredentials(GoogleCredentials.fromStream(refreshToken))
          .setDatabaseUrl(dbUrl)
          .setThreadManager(threadManager)
          .build();
```

```
[INFO] May 20, 2018 6:28:58 PM com.test.Startup$2 onChildAdded
[INFO] INFO: Enqueue successful
[INFO] May 20, 2018 6:28:58 PM com.test.Startup$2 onChildAdded
[INFO] INFO: Child Added
[INFO] May 20, 2018 6:28:58 PM com.test.Startup$2 onChildAdded
[INFO] INFO: Enqueue successful
...
[INFO] May 20, 2018 11:28:59 AM com.test.QueueWorkerServlet doPost
[INFO] INFO: Task received: -LCVeHUj9w0qUKB2b-5n
[INFO] May 20, 2018 11:28:59 AM com.test.QueueWorkerServlet doPost
[INFO] INFO: Task received: -LCVeHWoKMnAa4lVINdJ
[INFO] May 20, 2018 11:28:59 AM com.test.QueueWorkerServlet doPost
[INFO] INFO: Task received: -LCVeHWphGGnT-5_ZV--
```

**Comment by hiranya911** [comment]
Another approach I've had success with (without using Firebase `ThreadManager` API):

```
public class Startup implements ServletContextListener {

  private static final Logger Log = Logger.getLogger(Startup.class.getName());
  private static ExecutorService backgroundExecutor;

  @Override
  public void contextInitialized(ServletContextEvent sce) {
    Log.info("Listener started");
    backgroundExecutor = Executors.newSingleThreadScheduledExecutor(
         com.google.appengine.api.ThreadManager.backgroundThreadFactory());
    // Submit a task to ensure initialization of the thread (required)
    backgroundExecutor.submit(() -> Log.info("Worker pool initialized"));
    ....
```

```
      @Override
      public void onChildAdded(DataSnapshot dataSnapshot, String s) {
        Log.info("Child Added");
        try {
          backgroundExecutor.submit(() -> {
            Queue queue = QueueFactory.getDefaultQueue();
            queue.add(TaskOptions.Builder.withUrl("/getDepartureTimeWorker")
                .param("dbKey", dataSnapshot.getKey())
                .countdownMillis(1000));
            Log.info("Enqueue successful");
          });
        } catch (Exception e) {
          Log.warning("Error with submit: " + e.getMessage());
        }
      }
```

You can shutdown the executor in `contextDestroyed()`.

**Comment by engeeaitch** [comment]
@hiranya911 Thank you very much - I used your first solution, and it's all working correctly now.
Thanks again for your help.

**Comment by hiranya911** [comment]
Sounds good. This was useful to know. Hopefully other developers doing similar things in GAE will find this thread useful.
