### ISSUE TITLE
Firebase wipes out data when performs combination of transactional updates

### ISSUE THREAD

**Issue by sergey-ua** [firebase/firebase-admin-java#178]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macOS Sierra 10.12.6
  * Firebase SDK version: 6.1.0
  * Library version: ? 
  * Firebase Product: database

### [REQUIRED] Step 3: Describe the problem
Under some circumstances Firebase SDK squashes updates from different transactions into single set operation which wipes out existing data.

I have a structure like this:

```
/test/users/u1/
                     lastUpdate: 123
                     calls/history
                                  c1
                                  c2
                                  c3
```
In my code I do the following:
- transactionally append new call c4 to user u1
- transactionally modify call c4
- transactionally update user u1 and set new  lastUpdate field

At the end I have calls/history with call c4 only. Calls c1, c2, c3 were wiped out.

#### Steps to reproduce:

I have created demo repository which demonstrates the problem: https://github.com/sergey-ua/firebase-transaction-issue-demo

- Clone it
- Initialize described structure by calling
```
  ./mvnw -Dtest=FirebaseTransactionsTest#resetState -DdatabaseUrl="https://your-db-url.firebaseio.com/" -Dcert="path/to/cert.json" test
```
- Run described transaction sequence by calling
```
  ./mvnw -Dtest=FirebaseTransactionsTest#subsequentTransactions -DdatabaseUrl="https://your-db-url.firebaseio.com/" -Dcert="path/to/cert.json" test
```

#### Relevant Code:
See full code here: 
https://github.com/sergey-ua/firebase-transaction-issue-demo/blob/master/src/test/java/org/test/firebase/FirebaseTransactionsTest.java

[firebase-transaction-log.log](https://github.com/firebase/firebase-admin-java/files/2024680/firebase-transaction-log.log)
See Firebase SDK logs attached. 

Copied code snippet is here: 
```
@Test
    /**
     * Run this to reproduce issue. This test will fail
     * ./mvnw -Dtest=FirebaseTransactionsTest#subsequentTransactions -DdatabaseUrl="https://your-db-url.firebaseio.com/" -Dcert="/path/to/serviceAccountKey.json" test
     */
    public void subsequentTransactions() throws Exception {
        CountDownLatch latch = new CountDownLatch(3);
        String callUid = UUID.randomUUID().toString();
        //create new call
        firebaseDatabase.getReference(TEST_USER_PATH).child("calls").child("history").child(callUid)
            .runTransaction(new Transaction.Handler() {
                @Override
                public Transaction.Result doTransaction(MutableData currentData) {
                    currentData.child("/").setValue(getCallTemplate("updated"));
                    return Transaction.success(currentData);
                }

                @Override
                public void onComplete(DatabaseError error, boolean committed, DataSnapshot currentData) {
                    latch.countDown();
                }
            });
        //update call we have just created
        firebaseDatabase.getReference(TEST_USER_PATH).child("calls").child("history").child(callUid)
            .runTransaction(new Transaction.Handler() {
                @Override
                public Transaction.Result doTransaction(MutableData currentData) {
                    currentData.child("/").setValue(getCallTemplate("updated"));
                    return Transaction.success(currentData);
                }

                @Override
                public void onComplete(DatabaseError error, boolean committed, DataSnapshot currentData) {
                    latch.countDown();
                }
            });

        //Thread.sleep(5000); <- uncomment this and test will pass

        //update user object
        firebaseDatabase.getReference(TEST_USER_PATH).runTransaction(new Transaction.Handler() {
            @Override
            public Transaction.Result doTransaction(MutableData currentData) {
                currentData.child("lastUpdated").setValue(new Date().getTime());
                return Transaction.success(currentData);
            }

            @Override
            public void onComplete(DatabaseError error, boolean committed, DataSnapshot currentData) {
                latch.countDown();
            }
        });
        latch.await();

        //lets check initial calls are in place
        assertUserObject();
    }
```

**Comment by hiranya911** [comment]
@sergey-ua Thank you so much for the test case. Really makes it easier to look into the problem. It looks like the last transaction is the one that's causing issues. If it runs while the other 2 are still in progress, it clobbers part of the database tree. This probably has something to do with multiple transactions working on the same subtree.

@schmidt-sebastian FYI.

**Comment by hiranya911** [comment]
Btw why not fold all these changes into a single transaction?

**Comment by hiranya911** [comment]
I have a simple workaround for you. Just change the 3rd transaction as follows:

```
firebaseDatabase.getReference(TEST_USER_PATH).child("lastUpdated").runTransaction(new 
  Transaction.Handler() {
      @Override
      public Transaction.Result doTransaction(MutableData currentData) {
        currentData.setValue(new Date().getTime());
        return Transaction.success(currentData);
      }

      @Override
      public void onComplete(DatabaseError error, boolean committed, DataSnapshot currentData) {
        latch.countDown();
      }
    });
```

This way you're not running a transaction on the parent `TEST_USER_PATH`, which is what's causing the values to reset.

**Comment by sergey-ua** [comment]
Thanks for suggestion, but as I understand this will work only in this showcase. In production I may need to update several fields in one transaction and thus this approach will not work.

**Comment by hiranya911** [comment]
Then I suggest you run all your transactions on the parent `TEST_USER_PATH` (i.e. change the 1st and 2nd transactions).  Basically, the SDK needs to see the full subtree at least once, before its children get modified by multiple concurrent transactions.

**Comment by schmidt-sebastian** [comment]
@sergey-ua Thank for for filing this detailed bug report. We are looking at this with our backend team.

**Comment by hiranya911** [comment]
Based on the debug logs, it seems the last transaction commits before the current state of the `TEST_USER_PATH` is read from the remote storage (or at least without taking the current state of the node into consideration).

**Comment by sergey-ua** [comment]
Maybe it worth mentioning that initially I encountered this issue with SDK 4.1.7.  Tried to update to latest but that did not help.

**Comment by schmidt-sebastian** [comment]
I have been trying to track this down. Unfortunately, this appears to be rare edge case in our event handling logic that is a little tricky to address without changing behavior that we rely on in the rest of the SDK.

For what it's worth, I have taken your example and simplified it into a test case that can be run as an integration test in the Admin SDK:

```
@Test
public void testTransactionIsCanceledAfterServerUpdate()
    throws InterruptedException, ExecutionException {
  // This test reproduces https://github.com/firebase/firebase-admin-java/issues/178:
  //
  // If we run two transactions (one at "path/nested1" and one at "path"), the SDK did not
  // correctly re-run the "path" transaction if it got an update from the server for
  // "path/nested2". This caused the "path" transaction to succeed on the server
  // (our hash included the update from the server), merging stale data.
  final DatabaseReference ref = IntegrationTestUtils.getRandomNode(masterApp);
  ref.getDatabase().goOffline();

  // Write data to the backend from a secondary instance. The primary instance receives this data
  // when it goes online during the first transaction.
  FirebaseApp secondaryApp = IntegrationTestUtils.initApp("secondaryApp");
  DatabaseReference initialData =
      FirebaseDatabase.getInstance(secondaryApp).getReference(ref.getKey());
  initialData.setValueAsync(new MapBuilder().put("a", "a").build()).get();
  secondaryApp.delete();

  final Semaphore semaphore = new Semaphore(0);

  ref.child("b").runTransaction(new Handler() {
    @Override
    public Result doTransaction(MutableData currentData) {
      ref.getDatabase().goOnline();
      currentData.setValue("b");
      return Transaction.success(currentData);
    }

    @Override
    public void onComplete(DatabaseError error, boolean committed, DataSnapshot currentData) {
      Assert.assertTrue(committed);
      semaphore.release();
    }
  });

  ref.runTransaction(new Handler() {
    @Override
    public Result doTransaction(MutableData currentData) {
      currentData.child("c").setValue("c");
      return Transaction.success(currentData);
    }

    @Override
    public void onComplete(DatabaseError error, boolean committed, DataSnapshot currentData) {
      Assert.assertTrue(committed);
      semaphore.release();
    }
  });

  TestHelpers.waitFor(semaphore, 2);

  DataSnapshot dataSnapshot = TestHelpers.getSnap(ref);
  assertEquals(3, dataSnapshot.getChildrenCount());
}
```

We will let you know when he addressed this. Bear in mind that this could take a while since this is a rare edge case, and the first mention of this problem since the transaction code was initially released.

**Comment by sergey-ua** [comment]
ok, thanks for the update. @hiranya911 @schmidt-sebastian do you know if firebase-admin-node has same issue? I am thinking of migrating my code to nodejs then.

**Comment by schmidt-sebastian** [comment]
Yes, it does. For better or for worse, the codebases are a close 1:1 match. I was able to reproduce this with the Node client as well.

**Comment by sergey-ua** [comment]
@schmidt-sebastian thanks, good to know. will try to go with some of workarounds proposed by @hiranya911

**Comment by hiranya911** [comment]
We currently have no plans for further investigating this. Hopefully one of the proposed workarounds did the trick. Please reopen if this continues to be an issue.
