### ISSUE TITLE
Dangling thread(s) with FirebaseAuth.*Async methods ?

### ISSUE THREAD

**Issue by Nic0w** [firebase/firebase-admin-java#184]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Google App Engine (Java 8)
  * Firebase SDK version: 6.2
  * Library version: ?
  * Firebase Product: auth 

### [REQUIRED] Step 3: Describe the problem

We've got a servlet whose role is to provide a custom firebase token to the requesting user, given an id and an user name. First we check with FirebaseAuth.getUserAsync if the user exists for the submitted id. If it exists, we try to update it with FirebaseAuth.updateUserAsync. If not, a new record is created it with 
FirebaseAuth.createUserAsync. Then a custom token is built with FirebaseAuth.createCustomTokenAsync.

That servlet always anwser in ~60 seconds, despite no heavy computation being done, which is not acceptable. Indeed, we can see by adding tracepoints (thanks to Stackdriver Debug) that the whole logic is taking a few hundred milliseconds to complete. 

Troubleshooting was done by commenting out the whole logic in the servlet, then uncommenting relevant chunks one by one. When totally commented out, response time is just a few milliseconds. When uncommenting FirebaseAuth.getUserAsync, with no added logic, response time goes up to 60 seconds.

#### Steps to reproduce:

Looking at the logs for requests made to that servlet, this stacktrace shows up for every request : 

> Threads still running after 10 seconds:
Thread[Thread-24,5,Request #0] in state TIMED_WAITING
... sun.misc.Unsafe.park(Native Method)
... java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
... java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
... java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
... java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
... java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1066)
... java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1127)
... java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
... com.google.apphosting.runtime.ApiProxyImpl$CurrentRequestThreadFactory$1$1.run(ApiProxyImpl.java:1281)
... java.security.AccessController.doPrivileged(Native Method)
... com.google.apphosting.runtime.ApiProxyImpl$CurrentRequestThreadFactory$1.run(ApiProxyImpl.java:1275)
... java.lang.Thread.run(Thread.java:745)
... com.google.apphosting.runtime.ApiProxyImpl$CurrentRequestThread.run(ApiProxyImpl.java:1242)

**Comment by hiranya911** [comment]
Sounds like a bug in your code. Following servlet responds under 1 second for me (verified in App Engine java8 runtime -- both locally and in the cloud):

```
public void doGet(HttpServletRequest request, HttpServletResponse response) 
      throws IOException, ServletException {
    FirebaseAuth auth = FirebaseAuth.getInstance();
    String uid = request.getParameter("uid");
    try {
      UserRecord user;
      try {
         // get the existing user
        user = auth.getUserAsync(uid).get();
      } catch (ExecutionException e) {
        FirebaseAuthException authError = (FirebaseAuthException) e.getCause();
        if ("user-not-found".equals(authError.getErrorCode())) {
          // create the user if necessary
          System.out.println("Creating new user: " + uid);
          UserRecord.CreateRequest createRequest = new UserRecord.CreateRequest()
              .setUid(uid);
          user = auth.createUserAsync(createRequest).get();
        } else {
          throw new ServletException(e);
        }
      }

      // update the user and set custom claims
      auth.updateUserAsync(user.updateRequest().setCustomClaims(
          ImmutableMap.of("admin", true))).get();

      // create custom token
      String customToken = auth.createCustomTokenAsync(uid).get();
      response.getWriter().print(customToken);
    } catch (InterruptedException | ExecutionException e) {
      throw new ServletException(e);
    }
}
```

Client output:
```
$ time curl -v "https://<my_app>.appspot.com/hello?uid=user1"
* TCP_NODELAY set
* Connected to <my_app>.appspot.com port 443 (#0)
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x7fdd95004000)
> GET /hello?uid=user1 HTTP/2
> Host: <my_app>.appspot.com
> User-Agent: curl/7.54.0
> Accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
< HTTP/2 200 
< x-cloud-trace-context: d0781cf3e25e741a865f8e8a1b47b05d;o=1
< date: Sun, 03 Jun 2018 18:09:15 GMT
< content-type: text/html
< server: Google Frontend
< content-length: 771
< alt-svc: quic=":443"; ma=2592000; v="43,42,41,39,35"
< 
* Connection #0 to host <my_app>.appspot.com left intact
eyJhbGciOiJSUzI1NiJ9.eyJhdWQiOiJodHRw...........

real	0m0.634s
user	0m0.032s
sys	0m0.021s
```

The 60s delay you're seeing is the App Engine default timeout. That indicates there's a bug in your code, and it's not doing what you expect.

Also the scenario you've described is a classic sequential computation, and is best implemented using the regular (non-async) methods.

**Comment by Nic0w** [comment]
Hi,

Following your advice, we replaced async methods with blocking ones and our
issue went away. Response time is now below 500ms.

Thanks a lot for your help!

**Comment by hiranya911** [comment]
I will close this now. If you wish to investigate this further, please share the async code since my attempt above does not repro the issue.
