### ISSUE TITLE
Firebase Database suddenly stop working and send TimeoutException

### ISSUE THREAD

**Issue by jonathan-bibas** [firebase/firebase-admin-java#186]
Hi, all is in the title...
After some time (randomaly) the SDK doesn't want to send any update on my database. It send for each kind of request: `setValueAsync(element)` or `updateChildrenAsync(element)` a TimoutException.
My log for this error here:

![image](https://user-images.githubusercontent.com/7620241/41360621-df0b1c9c-6f35-11e8-9f92-39286d968d3b.png)
What do solve the problem is to restart the server but it still not a real solution...

Is it possible my app is black-listed or something?

I'm using Google AppEngine standard for Java 8

**Comment by hiranya911** [comment]
What's your scaling mode?

**Comment by hiranya911** [comment]
A couple of things you can try out:

1. Switch to manual scaling and see if that helps (it's possible that basic scaling instances are turning off certain features after the idle timeout).
2. Enable debug logs for the SDK (recommended approach is to use SLF4J, but since you seem to be on 5.x you can also call `FirebaseDatabase.enableLogging()`.

You should also share the code for initializing the SDK/Database and performing updates.

**Comment by jonathan-bibas** [comment]
> 1. Switch to manual scaling and see if that helps (it's possible that basic scaling instances are turning off certain features after the idle timeout).


1. I'll investigate for some different type of scaling instance and return to you my test results, but I'm using this scaling mode:
```
	<instance-class>B1</instance-class>
	<basic-scaling>
	    <max-instances>1</max-instances>
	    <idle-timeout>10m</idle-timeout>
	</basic-scaling>
```
Maybe it's the problem, the instance class is too low or there isn't enough instances (maybe need more than 1).


> 2. Enable debug logs for the SDK (recommended approach is to use SLF4J, but since you seem to be on 5.x you can also call FirebaseDatabase.enableLogging().

2. I run the version 6.0.0:
```
	<dependency>
	  <groupId>com.google.firebase</groupId>
	  <artifactId>firebase-admin</artifactId>
	  <version>6.0.0</version>
	</dependency>
```

> You should also share the code for initializing the SDK/Database and performing updates.

Here my code on initializing SDK/Database:

```
public class FirebaseInitListener implements ServletContextListener {

	/**
	 * @see ServletContextListener#contextInitialized(ServletContextEvent)
	 */
	public void contextInitialized(ServletContextEvent sce) {
		FirebaseOptions options = null;
		Map<String, Object> auth = new HashMap<String, Object>();
		auth.put("uid", "xxxxxxxxxxxxx");
		try {
			options = new FirebaseOptions.Builder().setCredentials(
					GoogleCredentials.fromStream(sce.getServletContext()
							.getResourceAsStream(
									"/WEB-INF/xxxxxxxxxxxxxxxxxxxx.json")))
					.setDatabaseUrl("https://rcm55-bagshop.firebaseio.com/")
					.setDatabaseAuthVariableOverride(auth)
					.build();
		} catch (IOException e) {
			e.printStackTrace();
		}
		FirebaseApp.initializeApp(options);
	}

	/**
	 * @see ServletContextListener#contextDestroyed(ServletContextEvent)
	 */
	public void contextDestroyed(ServletContextEvent sce) {}

}
```

Here the code using firebase database and throwing the timeout:

```
	private static void saveRTDB(Object o, String path) throws ApiException {

		DatabaseReference ref = FirebaseDatabase.getInstance()
				.getReference(path);

		try {
			ref.setValueAsync(o)
					.get(5, TimeUnit.SECONDS);
		} catch (InterruptedException e) {
			e.printStackTrace();
			log.severe(e.getMessage());
			throw new ApiException(500, "Error firebase, check server log");
		} catch (ExecutionException e) {
			e.printStackTrace();
			log.severe(e.getMessage());
			throw new ApiException(500, "Error firebase, check server log");
		} catch (TimeoutException e) {
			e.printStackTrace();
			log.severe(e.getMessage());
			throw new ApiException(500, "Error firebase, check server log");
		}

	}
```

Thank @hiranya911 for your help!

**Comment by jonathan-bibas** [comment]
You find my problem I think. I checked and you're right I was using the old version (forgot to `mvn clean`).
Now I deed it and it doesn't seem to do the error again.
Other modification I figure out needed: I was using a old version of SLF4J (v 1.5.*) and it was causing an error on each `/_ah/start` request. I so update to v1.7 and now it seem more stable

Thank you for the fast response and problem handling!

**Comment by hiranya911** [comment]
Glad you made some progress. I will close this issue now. We can revisit it if the problems show up again.
