### ISSUE TITLE
FR: Cloud Messaging Device Group Management for Java Admin SDK

### ISSUE THREAD

**Issue by vgalisson** [firebase/firebase-admin-java#187]
* Firebase Product: Cloud Messaging

I came by this [issue](https://github.com/firebase/firebase-admin-java/issues/185) about the same subject but I don't think it should be closed as it's a fair question. 

Why Device Group Management is only a feature in the node.js Admin SDK ? This is very useful feature when you have to handle multiple device for a user. Firebase documentation even says :

> If you need to send messages to multiple devices per user, consider device group messaging for those use cases.

The issue is that is only available with node.js or the legacy API (and it would be very bad design to use both API at the same time).

Are you **planning on implementing Device Group** to the Java Admin SDK or **should we use topic now** to handle multiple device per user?

Thanks in advance for any clarification,

**Comment by hiranya911** [comment]
Device groups are a part of the FCM legacy API: https://firebase.google.com/docs/cloud-messaging/admin/legacy-fcm

The new v1 API does not support it: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#Message

Node.js supports device groups because the FCM support in that SDK predates the v1 API. We currently don't have any plans to incorporate the legacy API features into other SDKs.

**Comment by vgalisson** [comment]
@hiranya911 Hi ! Thanks for the fast reply. 

So if you don't plan on adding Device Group to Admin SDK, what is the recommend way to handle multiple device per user ?

I've read that topic "`are optimized for throughput rather than latency.`" so should we use the legacy API instead? (I would prefer not because using both API at the same time seems strange)

**Comment by hiranya911** [comment]
For now you don't have much of a choice other than using the old API if you wish to use device groups.

@sampson-chen probably has more details.

**Comment by vgalisson** [comment]
@sampson-chen Hi, any hint on the correct way to handle multiple device per user with the latest API ? Is `topic` a viable solution?

**Comment by runningcode** [comment]
If i'm understanding this correctly, device groups seem to be a part of the new http api: https://firebase.google.com/docs/cloud-messaging/android/device-group

Sending to multiple devices for a single user is a pretty common use case.

**Comment by hiranya911** [comment]
On the back-end device groups are part of the legacy API: https://firebase.google.com/docs/cloud-messaging/admin/legacy-fcm

**Comment by jonathan-bibas** [comment]
Any news about this feature request?

**Comment by ncanu** [comment]
The reason why device groups is not in the Java SDK admin is because is a bad approach? If that's the case what is the recommended approach? Thanks

**Comment by chong-shao** [comment]
Hi, the FCM team is working on a new private topics feature for Java Admin SDK, which would be equivalent to device groups.
