### ISSUE TITLE
Firebase Admin SDK for Auth-only

### ISSUE THREAD

**Issue by deepfriedbrain** [firebase/firebase-admin-java#190]
I'm replacing Google Identity Toolkit Java SDK with Firebase Admin Java SDK in my GAE project. The project bloats from 12.5 MB to 29 MB after the replacement. The Identity Toolkit was adding 1.3MB where Firebase Admin SDK is adding about 17MB. I'm using Maven to add it as a dependency.

Since I'm only interested in Firebase Auth, is there a way to just bring in the "Auth" part of the SDK and not everything? I don't need any other feature of Firebase at the moment.

Environment:

Operating System version: MacOS 10.13.5
Firebase SDK version: 6.2.0
Library version: 5.0.4
Firebase Product: auth

**Comment by hiranya911** [comment]
Review the transitive [dependencies](https://github.com/firebase/firebase-admin-java/blob/master/pom.xml#L373) of firebase-admin, and configure a build rule to exclude the ones you don't want (specifically google-cloud-firestore, google-cloud-storage and all the netty libs). firebase-admin itself is quite small (< 1MB).

**Comment by deepfriedbrain** [comment]
Thank you @hiranya911 . That was very helpful. It's down to 12.9 MB (tad bit higher than the 12.5 with Google Identity Toolkit, but still acceptable) after adding 5 exclusions.

        <dependency>
            <groupId>com.google.firebase</groupId>
            <artifactId>firebase-admin</artifactId>
            <version>6.2.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.cloud</groupId>
                    <artifactId>google-cloud-storage</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.google.cloud</groupId>
                    <artifactId>google-cloud-firestore</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.netty</groupId>
                    <artifactId>netty-codec-http</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.netty</groupId>
                    <artifactId>netty-handler</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>io.netty</groupId>
                    <artifactId>netty-transport</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by deepfriedbrain** [comment]
@hiranya911 I'm using only 4 APIs `verifyIdToken`, `getUser`, `generateEmailVerificationLink`, and `generatePasswordResetLink` from the Admin SDK (v6.12.2).

Are there more libraries that I can exclude than the 5 listed above?
