### ISSUE TITLE
FR: Provide a generic way to set data to a node (JSON/Protobuf)

### ISSUE THREAD

**Issue by dmytro-grankin** [firebase/firebase-admin-java#195]
Now, to pass a custom object to `DatabaseReference.setValue(Object, CompletionListener)`, a class should have a default no-args constructor and provide public getters.

I am using Protobuf and want to pass a generated Protobuf message or a JSON string representing this message. If a string is passed to `DatabaseReference.setValue`, then it is considered as a plain string, not a string containing a JSON. If a generated Protobuf message is passed, then an exception is thrown (`DatabaseException: Found conflicting getters for name: getDefaultInstanceForType`).

It would be helpful to have at least one method of the following ones:
- `DatabaseReference.setJson(String json, CompletionListener listener)`
- `DatabaseReference.setMessage(com.google.protobuf.Message message, CompletionListener listener)`

In this way, a user of the library won't be forced to create multiple classes matching the requirements of `DatabaseReference.setValue`. Currently, the API is not flexible enough. 

The `DatabaseReference.updateChildren(...)` method may be enhanced in the same way.

**Comment by hiranya911** [comment]
You can use Maps to implement this use case. Simply unmarshal the json string into a Map and pass that in. Here's an example that uses org.json API to parse JSON:

```
    String json = "{\"foo\": \"value1\", \"bar\": 123}";
    Map map = new JSONObject(json).toMap();
    ref.setValueAsync(map).get();    
```

We are not considering API changes to Realtime Database at this point.
