### ISSUE TITLE
allow for client-safe authentication

### ISSUE THREAD

**Issue by nbransby** [firebase/firebase-admin-java#206]
I am primarily after the ability to authenticate as a user for Cloud Firestore

See https://github.com/firebase/firebase-android-sdk/issues/14 for more info

**Comment by hiranya911** [comment]
Admin SDK is for authenticating as privileged, back-end services. It should not be used for desktop apps, and authenticating as individual users is really not in scope for us. 

Having said that, there's a plan to support scoping Firestore requests down to individual users: https://github.com/firebase/firebase-admin-node/issues/132. When that's implemented it will be exposed in Java as well. That, combined with Google authorized user credentials can probably be used to implement the type of things you're thinking about.

**Comment by hiranya911** [comment]
Closing, since there isn't anything that can be done in this repo to support this feature. Firestore auth override capability is developed in the google-cloud-firestore library.

**Comment by nbransby** [comment]
Hmm ok well as @samtstern rated my chances of forking firebase-android-sdk and remove the android specific code as somewhere between "very hard" and "impossible" 

How would you rate my changes of forking firebase-admin-java and adding the client-safe authentication from the android client? Its all just java right? 😀

**Comment by hiranya911** [comment]
I'd say near impossible. Implementing this in our server SDKs require changes to Firestore service itself. Firestore server SDK code is here: https://github.com/GoogleCloudPlatform/google-cloud-java/tree/master/google-cloud-clients/google-cloud-firestore

It is not a simple clone/port of the Android code. It's a whole different beast.

**Comment by samtstern** [comment]
I believe the Firestore gRPC API (which the Java SDK uses) will "just work" if you pass it a Firebase Auth token.  And you can get that token from the Firebase Auth REST API.  

However the challenge here is threading that token through the `google-cloud-java` library (as @hiranya911 mentioned) and then managing the token lifecycle (they die each out).

**Comment by nbransby** [comment]
I’m guessing you chose to respond here because you feel that this task is (substantially?) more viable that porting the Firestore and dependent code from the android sdk to pure java?

**Comment by samtstern** [comment]
Yeah @nbransby I don't think starting from the Android SDK will ever work, to be honest.  I think building your own client on top of the gRPC or REST APIs would be easier than that.
