### ISSUE TITLE
FR: Get project id from credentials

### ISSUE THREAD

**Issue by viniciuslrangel** [firebase/firebase-admin-java#208]
Cannot get project id from FirebaseOptions if using GoogleCredentials (aka default instance).

`FirebaseApp.getInstance().getOptions().getDefaultProjectId()` could check if it's null and get from ServiceOptions

**Comment by hiranya911** [comment]
Where will it be used in the SDK?

**Comment by viniciuslrangel** [comment]
Just a guess, but it would be more friendly to find the project id when the `FirebaseOptions.Builder` does not come with it. I had to dig deep in the source to find `ServiceOptions.getDefaultProjectId`

**Comment by hiranya911** [comment]
The getters on `FirebaseOptions` are meant to be called from within the SDK. And we do so in the following util method:

https://github.com/firebase/firebase-admin-java/blob/e938204d6880f1e1c8780889505d84b3851b746c/src/main/java/com/google/firebase/FirebaseApp.java#L294-L314

How the external code finds the project ID is really not a concern of this API.
