### ISSUE TITLE
Problem with SDK Integration in Java ?

### ISSUE THREAD

**Issue by FlorianD77** [firebase/firebase-admin-java#210]
Hi,

I actually have a problem with the Admin SDK integration and usage. 
I actually work on a Java Project and I need to send notifications (firebase cloud messaging) on iOS devices. I use Firebase Admin SDK 6.5.0.

I follow the documentation and add everything we need, but when I try to send a push message, I have an error : 

<img width="725" alt="capture d ecran 2018-10-26 a 12 53 56" src="https://user-images.githubusercontent.com/12099087/47562265-3e2a3580-d91e-11e8-91c8-f77f46f6630c.png">

<img width="1568" alt="capture d ecran 2018-10-26 a 12 55 05" src="https://user-images.githubusercontent.com/12099087/47562383-8ea19300-d91e-11e8-80bb-99fda50d5fff.png">

I add firebase credentials to my project.
So, I can't send a push Notification.  Here's my code : 

#### Relevant Code:

```
public boolean sendPushMessage(String applicationName, String message, String incidentReference) {

		val firebaseMessage = Message.builder()
				.setNotification(new Notification(
						message,
						""))
				.setTopic("test")
				.build();
		try {
			FirebaseMessaging.getInstance().send(firebaseMessage);
		} catch (FirebaseMessagingException exception) {
			log.error("fail to send message {}", exception);
			return false;
		}

		return true;
	}
```

Thanks

**Comment by chaosnya** [comment]
Same issue on my side

**Comment by hiranya911** [comment]
Looks like it was a temporary issue in Google Auth. Works fine now.
