### ISSUE TITLE
Query doesn't fetch document by numeric field value

### ISSUE THREAD

**Issue by berar1994** [firebase/firebase-admin-java#212]
Hi guys,
I have an issue related to fetching a document from Firestore by a field which has numeric type. I'm using the **6.3.0** version for **firebase-admin** artifact id in a spring boot project. You can see in below image the field on which I would like to perform the query.

![capture](https://user-images.githubusercontent.com/17515623/47965309-0de54400-e04e-11e8-89a0-0b87899b1830.PNG)

I'm using the following code to fetch document by "id" field:
`final ApiFuture<QuerySnapshot> query = db.collection("raw_data").whereEqualTo("id",1029297385002991600L).get();`
`final QuerySnapshot querySnapshot = query.get();`

As a value I'm passing a Long one but it does not retrieve any document even if the value is present in firestore. I**f I change the type from numeric to string** in document and instead of 1029297385002991600L I use "1029297385002991600" in my code then it works and **retrives the document correctly**.

**Comment by schmidt-sebastian** [comment]
Thanks for letting us know. We will look into this as soon as we can.

**Comment by schmidt-sebastian** [comment]
This doesn't reproduce for me:

```
   addDocument("foo", 1029297385002991600L);

    QuerySnapshot querySnapshot = randomColl.whereEqualTo("foo", 1029297385002991600L).get().get();
    assertEquals(1, querySnapshot.size());

    Iterator<QueryDocumentSnapshot> documents = querySnapshot.iterator();
    assertEquals(1029297385002991600L, documents.next().get("foo"));
```

I also verified that the value itself is stored as a Number on the backend. Please let us know if this is still an issue.
