### ISSUE TITLE
Impove error messages while sending Apple notifications

### ISSUE THREAD

**Issue by sergeymeshkov** [firebase/firebase-admin-java#214]
Operating System version: Ubuntu 18.04.1 LTS
Firebase SDK version: firebase-admin 6.5.0 (Java)
Firebase Product: messaging

When I send a push notification that does not conform to the Apple notification format, I expect to see a detailed error with information about which parameters have been missed.

For example when I send request:

```
{
   "message":{
      "apns":{
         "payload":{
            "details":"Custom details",
            "aps":{
            }
         }
      },
      "token":"{firebase-token}"
   }
}

```

I recieve following error:

```
{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "errors": [
      {
        "message": "Request contains an invalid argument.",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
```

In this case, it is not clear which arguments are invalid and what I should change.
After I added 'badge' to request, notification was successfully sent.

```
{
   "message":{
      "apns":{
         "payload":{
            "details":"Custom details",
            "aps":{
               "badge":0
            }
         }
      },
      "token":"{firebase-token}"
   }
}

```

**Comment by hiranya911** [comment]
There seems to be a trick to get the FCM service to include more details in errors. Stay tuned for an update.

**Comment by hiranya911** [comment]
This has been implemented. Will be included in the next release.
