### ISSUE TITLE
Not receiving document updates on network disconnect and reconnect in Firestore Java admin SDK

### ISSUE THREAD

**Issue by cvml-user** [firebase/firebase-admin-java#215]
* Operating System version: Windows 10
  * Firebase SDK version: 6.5.0
  * Firebase Product: Firestore

I am setting up a watch for a query in Firestore in my local PC using Java admin SDK. If the network disconnects and reconnects then the updates are no longer received by my local machine. I have observed that if the network reconnection happens within a short interval (< 2 - 3 mins) then it is fine. But if it is longer then this issue happens. Also, no error/exception is notified in the Listener callback so that I can set up a watch again for the updates. My PC is not behind a proxy so it cannot be a proxy issue.

Looks like this is a bug in the SDK. I enabled the SDK logs and tried the following experiments:

 * Scenario 1:
1. Watch for query updates
2. Client sets up a GRPC connection with the server.
3. Looks like server is sending a keep alive(?) every minute to the client but no keep alive from the client to server
4. Disconnect the network
5. Reconnect within a minute, the query connection is still active and document updates arrive as expected
6. Disconnect the network
7. Reconnect after 5 minutes
8. Here my guess is that the server would have reset the GRPC connection from its end since it cannot reach the client but the SDK doesn't know about this. It is still expecting server to send the keep alive.
9. No document updates are received at the client side (as expected)
10. Issue a new query and watch for its updates.
11. SDK tries to send the query over the same GRPC connection it had established earlier, realizes that the connection is closed, opens a new GRPC connection. Now the document updates start coming for both the queries.

* Scenario 2:
1. Watch for query updates
2. Disconnect the network for about 5 minutes
3. Issue a new query before the network is reconnected.
4. SDK tries to send the query over the same GRPC connection it had established earlier, realizes that the connection is closed, opens a new GRPC connection. Even this fails but the connection attempt is retried every minute.
5. Reconnect the network.
6. Connection attempt of SDK succeeds and the updates start coming for both the queries.

I have also opened a SO [question](https://stackoverflow.com/questions/53313824/not-receiving-document-updates-on-network-disconnect-and-reconnect-in-firestore) for this issue

**Comment by cvml-user** [comment]
After setting the keep alive in the `TransportChannelProvider` of the `FirestoreOptions` while initializing `FirebaseApp`, this problem was resolved

**Comment by lucazin** [comment]
im facing same problem with springboot server and firestore.

listeners close unexpected.

**Comment by eranl** [comment]
> After setting the keep alive in the `TransportChannelProvider` of the `FirestoreOptions` while initializing `FirebaseApp`, this problem was resolved

@cvml-user, can you please recommend specific keep alive settings?
Will that work if network connections change (e.g. one network interface turning on and another turning off)?
