### ISSUE TITLE
setCredentials is required but not mentioned in documentation when using setServiceAccountId

### ISSUE THREAD

**Issue by peavers** [firebase/firebase-admin-java#234]
* Library version: 6.6.0
  * Firebase Product: firebase-admin

Following the [documentation](https://firebase.google.com/docs/auth/admin/create-custom-tokens) under "Using a service account ID" I should be able to skip the `setCredentials` option in the builder, as based on the documentation it's assumed to replace the need for a local copy of `service-account.json`. However should the `setCredentials` be missed, a NullPointerException is thrown 
```java
Caused by: java.lang.NullPointerException: FirebaseOptions must be initialized with setCredentials().
```
Attempt to set FirebaseOptions without a `setCredentials` option. 
```java
public FirebaseAuth firebaseAuth() throws IOException {
    FirebaseOptions options = new FirebaseOptions.Builder()
            .setServiceAccountId(SERVICE_ACCOUNT_EMAIL)
            .setProjectId(PROJECT_ID)
            .setDatabaseUrl(String.format("https://%s.firebaseio.com/", DATABASE_NAME))
            .build();

    FirebaseApp.initializeApp(options);

    return FirebaseAuth.getInstance();
}
```
Is the documentation incorrect/lacking detail or is this a bug?

**Comment by hiranya911** [comment]
Thanks @peavers for pointing this out. This is a documentation error. `GoogleCredentials` must be specified when creating an instance of `FirebaseOptions`. We will update the documentation as follows:

```
FirebaseOptions options = new FirebaseOptions.Builder()
        .setCredentials(GoogleCredentials.getApplicationDefault())
        .setServiceAccountId("my-client-id@my-project-id.iam.gserviceaccount.com")
        .build();
FirebaseApp.initializeApp(options);
```

Same applies for Node.js as well. Python, Go and C# will work as indicated in the samples.

**Comment by ravindranathakila** [comment]
May I please clarify what it is being used for? `setCredentials`

Why doesn't the SDK just use `setServiceAccountId`

**Comment by hiranya911** [comment]
SDK always requires some credentials to authorize remote API calls. Service account ID is only used when signing JWTs using the Cloud IAM API (those API calls also need to be authorized with some credentials).

**Comment by ravindranathakila** [comment]
Thank you very much for clarifying. It gives a lot of confidence to know it
won't mess with all the users hooked up with Firebase (as in, doesn't play
a role in user session management). It would be unfortunate to later
discover there were two keys linked to a token and one is gone thereby
breaking all token validity.
