### ISSUE TITLE
FR: Add scheduled notification parameter

### ISSUE THREAD

**Issue by cemo** [firebase/firebase-admin-java#236]
Please add support for scheduled notifications which is already supported by Web UI. Current API does not expose a parameter to schedule a notification.

**Comment by chong-shao** [comment]
Hi cemo, thanks for the request, we are currently working on this scheduled delivery feature.

**Comment by cemo** [comment]
Is this available now?

**Comment by jinho-actgames** [comment]
I don't understand why this issue is closed? cause we don't have schedule option yet!

**Comment by jinho-actgames** [comment]
@chong-shao Do we have any progress on this issue ?

**Comment by chong-shao** [comment]
@jinho-actgames @cemo thanks for asking. We are still working on this. Will provide an update once we have an expected launch date. :)

**Comment by jinho-actgames** [comment]
@chong-shao
Thanks for reply. 
Can you provide us any schedule of the option? 
It is almost 1 year after first issued.

**Comment by cemo** [comment]
Would you please reopen issue?

**Comment by jinho-actgames** [comment]
@cemo 
I have reopend this with #349, but it is closed with same message.
I just want to know when we can use the option.
