### ISSUE TITLE
Java 11 build problems

### ISSUE THREAD

**Issue by matejsp** [firebase/firebase-admin-java#243]
Unable to build using java 11.
- Old Mockito version is not working on java 11.
- Latest Mockito cannot mock IOException throw if interface cannot throw IOException.

Pull request contains fix for java 11 build.
- bump Mockito to 2.23.4
- fix unit test WebsocketConnectionTest.testIncomingMessageIOError

``
  org.mockito.exceptions.base.MockitoException: 
  Checked exception is invalid for this method!
  Invalid: java.io.IOException
``

**Comment by hiranya911** [comment]
This is fixed in #242
