### ISSUE TITLE
FR: In-App-Messaging

### ISSUE THREAD

**Issue by cemo** [firebase/firebase-admin-java#248]
Please provide Firebase Api for in-app-messaging at Admin Api.

**Comment by hiranya911** [comment]
@samtstern do you know who this should be assigned to from the FIAM side?

**Comment by samtstern** [comment]
I don't even know what a FIAM admin API would do but Megha B would be the
one to comment.

**Comment by hiranya911** [comment]
@meghab can you please take a look?

**Comment by cemo** [comment]
Hi @MeghaB, 
I would like to send in-app notifications by Admin API. In our use case I would like to select in some of our users in our backoffice or CRM application. Then I would like to send them in-app notification as push notifications.

**Comment by MeghaB** [comment]
Hi @cemo - What you're referring to sounds like a use-case for Firebase Cloud Messaging (FCM) - FIAM is for in-app messages (ex: embedded within the app as a modal or overlay), but not notifications. 

We already do have an admin sdk for FCM, detailed here! https://firebase.google.com/docs/cloud-messaging/admin/

**Comment by cemo** [comment]
@MeghaB This is definitely our use case what you described. We want to open some modals inside the app but these users must be targeted by our admins and crm power users. Sometimes it can be a discount offer or an advertisement related to our products etc... 

Please reopen this issue @hiranya911
