### ISSUE TITLE
onNewToken() sometimes gets unusable token.

### ISSUE THREAD

**Issue by u-shunya** [firebase/firebase-admin-java#254]
I changed MyApp's implementing push notification service from GCM to FCM.
I am using the code below to generate FCM Registration token and send it to my server.
```
@Override
public void onNewToken(String token) {
    super.onNewToken(token);
    sendTokenToMyServer(token);
}
```
I noticed that the new token may not be in the same format.
In many cases, the token is 152 characters and it is valid in notifications. However, in rare cases, a token of 140 characters is acquired. This could not be used for notifications.
My experience is very similar to the following posts.
https://stackoverflow.com/questions/39195216/firebaseinstanceid-getinstance-gettoken-is-generating-two-different-types-of

Please tell me the cause and measures.

I use `com.google.firebase:firebase-messaging:17.3.4`.

**Comment by hiranya911** [comment]
There's no such API in the Admin SDK. I think you're referring to the following Android API: https://firebase.google.com/docs/reference/android/com/google/firebase/messaging/FirebaseMessagingService

That's not part of this project.
