### ISSUE TITLE
Accessing http headers when sending push messages

### ISSUE THREAD

**Issue by vkolotov** [firebase/firebase-admin-java#258]
### [READ] Step 1: Are you in the right place?

Yes, I'm in the right place. 

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: macos
  * Firebase SDK version: ?
  * Library version: 6.7.0
  * Firebase Product: messaging

#### Steps to reproduce:

When sending push notifications, how do I access http response headers? As per documentation [here](https://firebase.google.com/docs/cloud-messaging/send-message) I have to respect `Retry-After` header in case of `messaging/server-unavailable` and `messaging/internal-error` error codes.

By looking into the [code](https://github.com/firebase/firebase-admin-java/blob/d314964edfafcc2f0dd64799905ba284b4d07c3c/src/main/java/com/google/firebase/messaging/FirebaseMessaging.java#L272), it appears that http headers get ignored.

#### Relevant Code:

```
ApiFuture<String> future = FirebaseMessaging.getInstance(firebaseApp).sendAsync(message);
future.addListener(() -> {
            try {
                String id = future.get();
                LOGGER.debug("FCM message has been sent successfully: {} / {}", id, notificationMessage.getId());
                sendToEndpoint(MARK_PENDING_NOTIFICATION_AS_SENT_ENDPOINT, notificationMessage);
            } catch (InterruptedException e) {
                LOGGER.debug("Sending a push notification {} was interrupted", notificationMessage.getId(), e);
            } catch (ExecutionException e) {
                Throwable cause = e.getCause();
                if (cause instanceof FirebaseMessagingException) {
                    FirebaseMessagingException fcmException = (FirebaseMessagingException) cause;
                    handleFirebaseMessagingException(notificationMessage, fcmException);
                    //TODO implement exponential backoff retry mechanism and respect 'Retry-After' http header response
                } else {
                    LOGGER.debug("Unexpected error of sending FCM message: {}. Marking the notification as failed.",
                            notificationMessage.getId(), e);
                    sendToEndpoint(MARK_PENDING_NOTIFICATION_AS_FAILED_ENDPOINT, notificationMessage);
                }
            }
        }, executor);
```

**Comment by vkolotov** [comment]
The response headers can be accessed via `fcmException.getClause()` method:

```
HttpResponseException httpResponseException = (HttpResponseException) fcmException.getCause();
            httpResponseException.getHeaders()
```

**Comment by hiranya911** [comment]
Also take note of #255, which will handle some of this automatically for you in the future.
