### ISSUE TITLE
The operation had to be aborted due to a network disconnect

### ISSUE THREAD

**Issue by fecogc** [firebase/firebase-admin-java#271]
* Firebase SDK version: 6.8.1
  * Firebase Product: Realtime database

Suddenly Firebase Realtime Database will be get disconnected and all its calls / transaction fails until a restart of the microservice.

**Transaction at /tid-191/bid-92/user_settings/uid-191/counterMap/P04 failed: DatabaseError: The operation had to be aborted due to a network disconnect**

The api is hosted in AWS, so I don't think their network might go down. Even if it goes down, Firebase should reconnect automatically right?

This issue started like 3-4 days ago when I was on 6.8.0, I updated to 6.8.1 and the issue persists.

This is how I make a transaction

```
public void updateCounter(int tenant_id, int branch_id, int user_id, String env, String type, int value)
{
    String path = "/tid-" + tenant_id + "/bid-" + branch_id + "/user_settings/uid-" + user_id + "/counterMap/" + env + type;
    	DatabaseReference ref = firebaseDB.getDatabase().getReference(path);
    	ref.runTransaction(new Transaction.Handler() {
    	    @Override
    	    public Transaction.Result doTransaction(MutableData mutableData) {
    	        mutableData.setValue(value);    	        
    	        return Transaction.success(mutableData);
    	    }

    	    @Override
    	    public void onComplete(DatabaseError databaseError, boolean committed, DataSnapshot dataSnapshot) {
    	    	if(committed)
    	    		logger.debug("Complete {}{}, Tenant: {}, branch: {}, User: {}, Value: {}", env, type, tenant_id, branch_id, user_id, dataSnapshot.getValue().toString());
    	    	else
    	    		logger.error("Failed {}{}, Tenant: {}, branch: {}, User: {}, {}", env, type, tenant_id, branch_id, user_id, databaseError.getMessage());
    	    }
    	});
}
```

**Comment by hiranya911** [comment]
I believe transactions are retried up to 25 times before the SDK gives up. That combined with the error message, seems like a network issue in your infrastructure that lasted for several minutes.

@schmidt-sebastian do you have any ideas?

**Comment by schmidt-sebastian** [comment]
@fecogc Can you provide us with debug logs? You can see how to enable them here: https://medium.com/@hiranya911/logging-in-java-libraries-for-firebase-and-google-cloud-platform-f8742493b73f

**Comment by fecogc** [comment]
I found the cause of this issue.

Where there an out of memory issue (Heap space in Firebase), the connection/transaction will fail and will not auto connect or recover.

Saddly I dont have the log file. But you can replicate the issue by uploading 50k 5kb object to Firebase.
My Java memory size at the moment was 1500mb.

**Comment by fecogc** [comment]
> I believe transactions are retried up to 25 times before the SDK gives up. That combined with the error message, seems like a network issue in your infrastructure that lasted for several minutes.
> 
> @schmidt-sebastian do you have any ideas?

I don't see any retries. Because after the error the field that I wanted to change remained the same.
How do I make sure it retried?

**Comment by schmidt-sebastian** [comment]
Transaction retries happen when data on the backend changes and the client state is not up to date. For this to occur, we have to be able to communicate with the backend to receive the updated hash.

That being said, the SDK should retry any failed connection attempts.

@fecogc Are you still blocked by this?

**Comment by fecogc** [comment]
Its not really blocking me. Since we have another nosql db that syncs the data.
It's just a bit annoying because in firebase the count is 4 but it really should be 5.

So, according to my findings, if the transaction is not committed/completed. I need to retry myself right?

```
@Override
public void onComplete(DatabaseError databaseError, boolean committed, DataSnapshot dataSnapshot) {
   if(committed) {
      logger.debug("Complete {}{}, Tenant: {}, branch: {}, User: {}, Value: {}", env, type, tenant_id, branch_id, user_id, dataSnapshot.getValue().toString());
   }
   else {
      logger.error("Failed {}{}, Tenant: {}, branch: {}, User: {}, {}", env, type, tenant_id, branch_id, user_id, databaseError.getMessage());
      retryTransaction(values...);
   }
}
```

**Comment by schmidt-sebastian** [comment]
That is correct. We will retry transaction internally for you, but if we fail (after 25 attempts) we will report a failure. You may choose to invoke further retries.

Since there are no immediate plans to improve this situation, I will close this issue. Please do let me us know if this issue does end up blocking you.

**Comment by fecogc** [comment]
I know its bad to reopen closed issues, but I think this is related and might help fix this issue.

So the network disconnect issues are still happening, because we run the [updateCounter()](https://github.com/firebase/firebase-admin-java/issues/271#issue-443053822) in a loop. Up to 250 iterations per second. And CPU usage spikes up to 100%.

I found out that in [Admin node.js](https://firebase.google.com/docs/reference/admin/node/admin.database.ServerValue) the ServerValue.increment() was added, but it is not in [Java's Admin](https://firebase.google.com/docs/reference/admin/java/reference/com/google/firebase/database/ServerValue).

And according to Frank(firebase) in StackOverflow,  

Using ServerValue.increase() can improve results,

> Results:
> 
> With transactions I was able to increment a value about 60-70 times per second.
> With the increment operator, I was able to increment a value about 200-300 times per second.

[https://stackoverflow.com/questions/61536203/how-quickly-can-you-atomically-increment-a-value-on-the-firebase-realtime-databa](https://stackoverflow.com/questions/61536203/how-quickly-can-you-atomically-increment-a-value-on-the-firebase-realtime-databa)

So I was wondering, is this feature going to be added in the future?

**Comment by schmidt-sebastian** [comment]
At this point in time, we do not currently have plans to expose ServerValue.increment() in the Java Server SDK. This, however, is mostly due prioritization on our end and limited engineering resources. We would be more than willing to take a port of the corresponding change in our Android SDK: https://github.com/firebase/firebase-android-sdk/pull/991, https://github.com/firebase/firebase-android-sdk/pull/1415 and https://github.com/firebase/firebase-android-sdk/pull/1417. Thank you for understanding!
