### ISSUE TITLE
io.grpc.Context and Firestore

### ISSUE THREAD

**Issue by Amosss** [firebase/firebase-admin-java#272]
Hi

I use Firestore and I just encountered the following: SEVERE [Catalina-utility-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@486b085d]) and a value of type [io.grpc.Context] (value [io.grpc.Context@5c653a4b]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.

I read this thread https://github.com/firebase/firebase-admin-java/issues/237 and maybe I've missed something but I didn't see a solution to the above. Is there an update since 4 months ago?
Thanks

**Comment by hiranya911** [comment]
I see that @wilhuff has commented on #237. Closing this issue, since our position on this hasn't changed.
