### ISSUE TITLE
FR: Break down this library into smaller ones for Microservices and FaaS

### ISSUE THREAD

**Issue by feinstein** [firebase/firebase-admin-java#273]
I am using Firebase Auth in my Flutter App and I need to validate my users in my Microservices. I just need Firebase Auth and nothing more. 

I run my code in a serverless environment, a FaaS, so the smaller the better. My code was with 7MB before I added this library, now it jumped to 27MB!!!

This makes it very hard to use this library into an AWS Lambda and the likes of it. 

Please break it down.

**Comment by hiranya911** [comment]
It's easy to filter out transitive dependencies that you don't want. Just use Maven exclusions to remove the `google-cloud-storage` and `google-cloud-firestore` dependencies (those are the biggest ones as far as I know). You might be able to drop some of the `netty-*` dependencies as well. Gradle supports the same feature too, if that's how you manage your builds.

We do this in our own codebase to screen out some unwanted dependencies:

https://github.com/firebase/firebase-admin-java/blob/6809316c814353b86c3f754128bd317617900488/pom.xml#L392-L402

We have no plans to split the library into smaller components at this point.

**Comment by feinstein** [comment]
I use gradle, but this is a big hassle and a waste of time, just the opposite of what cloud computing is all about.

**Comment by feinstein** [comment]
`google-cloud-storage` is about 1MB, while `google-cloud-firestore` is 14MB alone!

Could you open your build folder and share a printscreen of the sizes of all those jars, so I could select them more easily?

**Comment by hiranya911** [comment]
I created a simple webapp project with just `firebase-admin` as the sole dependency. Without any exclusions, the `WEB-INF/lib` directory is 23MB. With Firestore and Storage taken out, it comes down to 8.4MB. I can get it down to 5.9MB by taking out the 3 Netty dependencies.

```
<dependency>
      <groupId>com.google.firebase</groupId>
      <artifactId>firebase-admin</artifactId>
      <version>6.8.1</version>
      <exclusions>
        <exclusion>
          <groupId>com.google.cloud</groupId>
          <artifactId>google-cloud-firestore</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.google.cloud</groupId>
          <artifactId>google-cloud-storage</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-codec-http</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-handler</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-transport</artifactId>
        </exclusion>
      </exclusions>
</dependency>
```

That's everything that can be removed if you want to use FirebaseAuth.

**Comment by feinstein** [comment]
Thank you, this helps a lot!

**Comment by feinstein** [comment]
I think it's clear now that `Firestore` and `Storage` takes out the vast majority of space in this library (~75%), so it would make sense to at least make 2 libraries, one for Firebase Auth, and one for the rest. 

Just my 2 cents.
