### ISSUE TITLE
Error 500 - No details - deleteInstanceId/deleteInstanceIdAsync

### ISSUE THREAD

**Issue by hugoblanc** [firebase/firebase-admin-java#276]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: windows 10 _ 10.0.17763
  * Firebase SDK version: 6.8.1
  * java version 1.8.0_211
  * Firebase Product: Messaging <-> InstanceId

### [REQUIRED] Step 3: Describe the problem
I try to delete instance id with the following code: 
`FirebaseInstanceId.getInstance().deleteInstanceIdAsync(idToDelete).get();`
But I get a error 500: internal server error
 
#### Steps to reproduce & Relevant Code:

Step 1
Get token from android client app: 
`FirebaseInstanceId.getInstance().getToken()`
Pass token from client to server

Step 2
Split token to get only instanceId part
`String[] instanceId = token.split(":");
FirebaseInstanceId.getInstance().deleteInstanceIdAsync(instanceId[0]).get();`

Last line throw error 500

**Comment by hiranya911** [comment]
I've informed the relevant team about this. In the meantime any additional information you can provide would be helpful (full stacktrace of the error, debug logs etc).

**Comment by hugoblanc** [comment]
After investigating, I realized that even with the error 500, instance Id seems correctly deleted.
If I call getToken from client after error 500 the new token is different and topics are not present anymore. 

`ERROR - com.google.firebase.iid.FirebaseInstanceIdException: Instance ID "fix0PfuDfUQ": Internal server error.` 
`ERROR - java.lang.NoSuchMethodError: com.google.common.io.ByteStreams.exhaust(Ljava/io/InputStream;)J`

**Comment by hiranya911** [comment]
There are 2 different errors in your last comment. The 2nd one (NoSuchMethodError), is due to a guava version conflict. Can you make sure that you have at least guava 20 in your classpath? Until you do that, all calls to `deleteInstanceId()` are going to fail -- even when the backend service responds with a successful response.

https://github.com/firebase/firebase-admin-java/blob/dda8ff2d87b4c080cbeff7f907c64b98a89bed78/src/main/java/com/google/firebase/iid/FirebaseInstanceId.java#L150-L160

Error occurs in L155.

**Comment by hugoblanc** [comment]
I tried by forcing guava v20, admin SDK was loading v18. 
I don't see `java.lang.NoSuchMethodError` anymore.

But `Instance ID "fix0PfuDfUQ": Internal server error.` is still present

**Comment by hugoblanc** [comment]
I have deeper investigated on this issue by creating a new spring boot project. 
From this new starting point there are no more errors 500. 
But I don't think that FirebaseInstanceID is working correctly.

I'm basically doing the same stuff than before on client side :
`FirebaseInstanceId.getInstance().getToken()`

And on server side, I hardcoded instanceId: 
`FirebaseInstanceId.getInstance().deleteInstanceId("eKNpakBsZfQ");`
 
After android app is installed, I get a new clean/working  **instanceId:token**
If I deleteInstanceId with this new generated token there are no errors and everything is working fine.

But, when I call getToken after restart application on client side , I get the same token than before. 
If I try to deleteInstanceId a second time, I get the following error:
`FirebaseInstanceIdException: Instance ID "eKNpakBsZfQ": Already deleted.`

And I'm stuck between android app which is getting the same old token and my server which is firing Already deleted exception. 

In addition, GET on https://iid.googleapis.com/iid/info with this old "already deleted" token is correctly executed

`
{
    "applicationVersion": "20300",
    "connectDate": "2019-06-11",
    "attestStatus": "NOT_ROOTED",
    "application": "com.whitecorp.studay",
    "scope": "*",
    "authorizedEntity": "26xxxxxxxxxxxxxxx67",
    "connectionType": "WIFI",
    "appSigner": "5xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx9",
    "platform": "ANDROID"
}
`

**Comment by hiranya911** [comment]
I got some info from the backend team regarding this issue.

=== fix0Pfu**** ===
Has been deleted by CLIENT-SDK on 2019/06/07-01:16.
That means that the IID client-SDK send a "Delete" signal directly to the IID endpoint.
This happened most likely when the App-Instance was uninstalled from the device.

=== eKNpakB**** ===
Has been deleted by ADMIN-SDK on 2019/06/11-04:14.

They also confirm that a deletion via Admin-SDK will not immediately delete or invalidate an Instance-ID and endpoints like https://iid.googleapis.com/iid/info will continue to return valid information.

The reason for this is that the #DeleteInstanceId method will "only" mark an App-Instance as deleted and the IID Deletion Flume-job will periodically run and delete the associated data from FCM.

Hopefully that explains the behavior described in @hugoblanc's last comment: (https://github.com/firebase/firebase-admin-java/issues/276#issuecomment-500815767).

**Comment by hiranya911** [comment]
I'm going to close this issue since I don't see any action items for this particular codebase. If you're still having issues with this API, please reach out to Firebase support directly and provide information about your project (project ID, specific IID strings etc.)
