### ISSUE TITLE
UNAVAILABLE: HTTP/2 error code: NO_ERRORReceived Goawaysession_timed_out

### ISSUE THREAD

**Issue by Amosss** [firebase/firebase-admin-java#278]
* Operating System version: Ubuntu
  * Firebase SDK version: 6.8.1
  * Firebase Product: Firestore

This is the callstack:
java.util.concurrent.ExecutionException: com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP/2 error code: NO_ERRORReceived Goawaysession_timed_out	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500)	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:479)	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:76)	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:62)

This is my lines of code that triggered this
ApiFuture<WriteResult> future = db.collection(collection).document(doc).set(fsData, SetOptions.merge());
future.get();	    		    	       

This is working most of the time, it happened only twice so far so maybe it's something temporary but I have no idea what it is and how to overcome this.

Please advice
Thanks

**Comment by hiranya911** [comment]
Please report at https://github.com/googleapis/google-cloud-java where the Firestore code is being developed. Admin SDK is a thin wrapper around Firestore, and this issue cannot really be addressed in this codebase.
