### ISSUE TITLE
FR: Add sign in options

### ISSUE THREAD

**Issue by feinstein** [firebase/firebase-admin-java#283]
I am building a system to emulate users in my system, this way I can debug any troubles my users are facing. Also this makes testing easier.

I created a simple Java CLI Application that creates a Custom Token for a giver UID. I would like to be able to then sign-in with that Custom Token, so I can get an ID Token and use that ID Token to simulate my user in all my servers.

The problem is there's no pure Java Client library, just the Android one and the Java Firebase Auth Admin library doesn't provide any methods for signing-in and retrieving an ID Token.

Could you guys please add the ability to get an ID Token for a given UID?

**Comment by hiranya911** [comment]
I don't think there are any plans in the short term add user authentication APIs to the admin SDKs. But you can use the REST API directly for this purpose:

https://github.com/firebase/firebase-admin-java/blob/6e507af6fd84efcd7f8e79fc1561d92a0a72bbec/src/test/java/com/google/firebase/auth/FirebaseAuthIT.java#L617-L632

**Comment by feinstein** [comment]
Yes, that's what I did at the end. Thank you.

**Comment by bojeil-google** [comment]
We document how to do this via the REST API: https://firebase.google.com/docs/reference/rest/auth
As far as I know we don't have plans to provide this via the Admin SDK. You are welcome to file an official [feature request](https://firebase.google.com/support/) for this.

**Comment by feinstein** [comment]
Ok, I will.

**Comment by hiranya911** [comment]
We still do not have any plans to support these APIs in the Admin SDK. And we do not have a lot of demand for this functionality either based on the handful of feedback points we have received over the years. I'm going to close this issue now, and ask any other developers who are longing for this feature to file feature requests via Firebase Support (see the link above).
