### ISSUE TITLE
Misuses of cryptographic APIs

### ISSUE THREAD

**Issue by mhp0rtal** [firebase/firebase-admin-java#286]
Hi
The following lines have cryptographic API misuses. <br> File name => src/main/java/com/google/firebase/database/utilities/Utilities.java: Line number => 111: API name => MessageDigest:First parameter (with value "SHA-1") should be any of {SHA-256, SHA-384, SHA-512}<BR> File name => src/main/java/com/google/firebase/database/utilities/Utilities.java: Line number => 113: API name => MessageDigest:<BR>

**Comment by hiranya911** [comment]
Can you elaborate what the issue here is? Why is that usage a "misuse"?

**Comment by hiranya911** [comment]
In this case our application code requires the use of a SHA1 hash. I believe we use the hash as a way of ordering nodes, and has no security implications.
