### ISSUE TITLE
java.lang.NoClassDefFoundError: com.google.firebase.auth.FirebaseAuth$3

### ISSUE THREAD

**Issue by laatahzan** [firebase/firebase-admin-java#288]
I run the code below to get a token, but the program stops at **FirebaseAuth.getInstance(). createCustomToken()** and an error appears as attached below.

Where is **androidmanifest.xml** located? Thanks.

`    @Override
    protected void onCreate(Bundle savedInstanceState) {
        try {
            super.onCreate(savedInstanceState);
            setContentView(R.layout.activity_main);

            FileInputStream serviceAccount = new FileInputStream("/data/data/id.koding.firebaseadmin/firebase-adminsdk.json");

            FirebaseOptions options = new FirebaseOptions.Builder()
                    .setCredentials(GoogleCredentials.fromStream(serviceAccount))
                    .setDatabaseUrl("https://fir-firestore-24d9a.firebaseio.com")
                    .build();

            FirebaseApp.initializeApp(options);

            String token = FirebaseAuth.getInstance().createCustomToken("test"); // ERROR IN HERE
            Log.i("TOKEN: ", token);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
`

Errors:

>     java.lang.NoClassDefFoundError: com.google.firebase.auth.FirebaseAuth$3
>         at com.google.firebase.auth.FirebaseAuth.fromApp(FirebaseAuth.java:108)
>         at com.google.firebase.auth.FirebaseAuth.access$1100(FirebaseAuth.java:57)
>         at com.google.firebase.auth.FirebaseAuth$FirebaseAuthService.<init>(FirebaseAuth.java:1184)
>         at com.google.firebase.auth.FirebaseAuth.getInstance(FirebaseAuth.java:101)
>         at com.google.firebase.auth.FirebaseAuth.getInstance(FirebaseAuth.java:88)
>         at id.koding.firebaseadmin.MainActivity.onCreate(MainActivity.java:34)
>         at android.app.Activity.performCreate(Activity.java:5990)
>         at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
>         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
>         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
>         at android.app.ActivityThread.access$800(ActivityThread.java:151)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
>         at android.os.Handler.dispatchMessage(Handler.java:102)
>         at android.os.Looper.loop(Looper.java:135)
>         at android.app.ActivityThread.main(ActivityThread.java:5254)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at java.lang.reflect.Method.invoke(Method.java:372)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
>

**Comment by hiranya911** [comment]
Admin SDK cannot be used on Android. It is for server-side use only. Specifically, methods like `createCustomToken()` cannot and should not be used on client devices.
