### ISSUE TITLE
Get public keys connect time out

### ISSUE THREAD

**Issue by RoyceZheng87** [firebase/firebase-admin-java#292]
I verify ID tokens using the Firebase Admin SDK, but get public keys connect time out
```
public GooglePublicKeysManager refresh() throws GeneralSecurityException, IOException {
...
HttpResponse certsResponse = this.transport.createRequestFactory().buildGetRequest(new GenericUrl(this.publicCertsEncodedUrl)).execute();
...
}
```

**Comment by hiranya911** [comment]
Most likely due to a network issue at your end, or a temporary issue with Google public key server. Please get back to us if the problem can be reproduced reliably.
