### ISSUE TITLE
Shaded version of firebase-admin-java sdk jar w/ dependencies relocated 

### ISSUE THREAD

**Issue by pankajsinghal** [firebase/firebase-admin-java#293]
There is already an issue regarding this - https://github.com/firebase/firebase-admin-java/issues/162

I think it would really be helpful it there was a shaded (packaged with dependencies) version of `firebase-admin-java` SDK & dependencies relocated to some different package to avoid version conflict. 

I'm currently facing issues because we have a different version of netty which is getting conflicted with this & breaking the code.

**Comment by hiranya911** [comment]
I think our position on this hasn't changed. Neither Firebase nor GCP currently ship any shaded jar files due to multiple reasons. I don't see this changing in the near future.
