### ISSUE TITLE
Cannot resolve symbol FirebaseOptions

### ISSUE THREAD

**Issue by JagarYousef** [firebase/firebase-admin-java#296]
I am using Firebase admin with JavaFx and maven support module.<br>I've added the dependency: <br>
```
<dependency>
            <groupId>com.google.firebase</groupId>
            <artifactId>firebase-admin</artifactId>
            <version>6.9.0</version>
        </dependency>
```
But still all Firebase classes including FirebaseOptions not resolved.

**Comment by hiranya911** [comment]
Almost certainly a problem with your environment or build setup. If you inspect the contents of the jar file you will see the FirebaseOptions class file in there. Try dumping your maven dependency tree, and make sure the SDK is indeed in your classpath. If that doesn't help I'd recommend asking in Stackoverflow with more details about your application.
