### ISSUE TITLE
FR: Use PropertyName value as enum value

### ISSUE THREAD

**Issue by 6bangs** [firebase/firebase-admin-java#301]
This is a request to cherry-pick https://github.com/firebase/firebase-android-sdk/issues/239

The example from that project:

```java
public enum MyEnum {
  @PropertyName("one")
  ONE,

  @PropertyName("secondOne")
  SECOND_ONE
}
```

- When deserializing:
  - "one" will be mapped to ONE
  - "secondOne" will be mapped to SECOND_ONE
- When serializing:
  - ONE will be mapped to "one"
  - SECOND_ONE will be mapped to "secondOne"

The cherry-pick is available here: https://github.com/vi-technologies/firebase-admin-java/commit/faac58676ae7539010139ae9ad1b8b717bff8bfd

**Comment by hiranya911** [comment]
Do you want this implemented for Firestore or RTDB? The issue referenced above is concerning Firestore.

**Comment by 6bangs** [comment]
Firestore; I think the feature already exists for RTDB.

**Comment by hiranya911** [comment]
Firestore code is not part of this repo. You should follow up at https://github.com/googleapis/google-cloud-java

**Comment by 6bangs** [comment]
Hmm... I think I'm probably confused about the project organization. The [docs linked from this project's README](https://firebase.google.com/docs/admin/setup) say:

> Access Google Cloud Platform resources like Cloud Storage buckets and Firestore databases associated with your Firebase projects.

That's what I'm using it for (and it works). The google-cloud-java project does have similar code (and actually supports serialization/deserialization of enum values by `@PropertyName`), but it appears to be oriented towards usage of Firestore in Google Cloud.

Sorry for the confusion.

**Comment by hiranya911** [comment]
Our Firestore support is entirely provided by the `google-cloud-firestore` library. When a developer calls `FirestoreClient.getFirestore()`, we simply call out to that library.

**Comment by 6bangs** [comment]
Got it, looks like we were transitively depending on an old version of `google-cloud-firestore` (that didn't support this use case). All cleared up, thanks.
