### ISSUE TITLE
Firebase RDB transaction returns success, but isn't committed

### ISSUE THREAD

**Issue by sgammon** [firebase/firebase-admin-java#304]
### [REQUIRED] Step 2: Describe your environment
  * Operating System version: `macOS 10.14.6` and `Alpine Linux`
  * Firebase SDK version: `6.9.0`
  * Library version: `java`
  * Firebase Product: `database` (auth, database, storage, etc)

### [REQUIRED] Step 3: Describe the problem

Cross-posted with cloud support (case `20498489`). We work against Firebase Realtime Database from the Java (admin) driver. When running a rather large transaction, we change the `MutableData` object in significant ways, and then commit the transaction to Firebase.

The transaction returns `committed=true`, no error, and a value is provided as output. However, it does not appear to have applied the new data in any sense. The Firebase console does not display data as updated, and we cannot discern from the output payload that it was updated.

A few more details/things we tried:
1) We tried wiping all data at the transaction location. This worked, proving that the Firebase database is selected correctly, that permissions are working and not rejecting requests outright, and so on.

2) The database in question has no rules that might reject the write due to validation errors. In fact, there are no rules at all:
```
{
  "rules": {
    ".write": "auth != null",
    ".read": true
  }
}
```

3) We tried enabling debug logging over the WebSocket with Firebase. Amidst a ton of logs we found a message about ETag headers not matching for a transaction, indicating a retry, but otherwise this looks to be an innocuous error, and the stream itself displayed no other abnormalities.

4) When refreshing the Firebase console (to address for the >1MB trigger quota), no data is updated. Strict triggers are on anyway so it should be an error to write over 1MB, unless I am mistaken.

#### Steps to reproduce:

Working on this

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
# coming shortly
```

**Comment by mikelehen** [comment]
I believe this issue was resolved via another channel (cloud support case 20498489). If you're still having issues, please re-open with repro code, etc.  Thanks!

**Comment by sgammon** [comment]
Indeed it was, this one was our fault! Thank you @mikelehen.
