### ISSUE TITLE
Firestore exception in jar with dependencies

### ISSUE THREAD

**Issue by jexom** [firebase/firebase-admin-java#310]
* Operating System version: Win10 x64 Java 1.8
  * Firebase SDK version: 6.10.0
  * Firebase Product: Firestore

While making a simple web app I've encountered an issue with Firestore that prevents me from using it. While I run the following code from IntelliJ it's works fine as expected, but after building a jar with dependencies through Maven the following exception occurs.

 ### Code:
```Java
package me.jexom.MPEIPush;
import com.google.auth.oauth2.GoogleCredentials;
import com.google.cloud.firestore.Firestore;
import com.google.firebase.FirebaseApp;
import com.google.firebase.FirebaseOptions;
import com.google.firebase.cloud.FirestoreClient;

import java.io.IOException;
import java.io.InputStream;

public class MPEIPush {
    public static void main(String[] args) throws IOException {
        InputStream serviceAccount = MPEIPush.class.getResourceAsStream("/pupush-sak.json");
        GoogleCredentials credentials = GoogleCredentials.fromStream(serviceAccount);
        FirebaseOptions options = new FirebaseOptions.Builder()
                .setCredentials(credentials)
                .build();
        FirebaseApp.initializeApp(options);

        Firestore db = FirestoreClient.getFirestore(); //crash
    }
}
```
### Exception
```
Exception in thread "main" com.google.cloud.firestore.FirestoreException: java.lang.UnsupportedOperationException
        at com.google.cloud.firestore.FirestoreException.networkException(FirestoreException.java:70)
        at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:82)
        at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:72)
        at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:510)
        at com.google.cloud.firestore.FirestoreOptions.getFirestoreRpc(FirestoreOptions.java:315)
        at com.google.cloud.firestore.FirestoreImpl.<init>(FirestoreImpl.java:77)
        at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreFactory.create(FirestoreOptions.java:63)
        at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreFactory.create(FirestoreOptions.java:56)
        at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:498)
        at com.google.firebase.cloud.FirestoreClient.<init>(FirestoreClient.java:51)
        at com.google.firebase.cloud.FirestoreClient.<init>(FirestoreClient.java:29)
        at com.google.firebase.cloud.FirestoreClient$FirestoreClientService.<init>(FirestoreClient.java:95)
        at com.google.firebase.cloud.FirestoreClient.getInstance(FirestoreClient.java:85)
        at com.google.firebase.cloud.FirestoreClient.getFirestore(FirestoreClient.java:78)
        at me.jexom.MPEIPush.MPEIPush.main(MPEIPush.java:34)
Caused by: java.io.IOException: java.lang.UnsupportedOperationException
        at com.google.cloud.firestore.spi.v1.GrpcFirestoreRpc.<init>(GrpcFirestoreRpc.java:137)
        at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:80)
        ... 13 more
Caused by: java.lang.UnsupportedOperationException
        at io.grpc.ManagedChannelBuilder.disableServiceConfigLookUp(ManagedChannelBuilder.java:572)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:239)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:185)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:177)
        at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:160)
        at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:122)
        at com.google.cloud.firestore.spi.v1.GrpcFirestoreRpc.<init>(GrpcFirestoreRpc.java:122)
        ... 14 more
```
### pom.xml
```XML
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>me.jexom.MPEIPush</groupId>
    <artifactId>MPEIPush</artifactId>
    <version>1.0</version>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>me.jexom.MPEIPush.MPEIPush</mainClass>
                        </manifest>
                    </archive>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
        <resources>
            <resource>
                <directory>
                    src/main/resources
                </directory>
                <includes>
                    <include>**/*.*</include>
                </includes>
            </resource>
        </resources>
    </build>

    <dependencies>
        <dependency>
            <groupId>com.google.firebase</groupId>
            <artifactId>firebase-admin</artifactId>
            <version>6.10.0</version>
        </dependency>
    </dependencies>
</project>
```

**Comment by schmidt-sebastian** [comment]
@jexom Thanks for filing this issue and sorry for your trouble!

The stacktrace refers to an API that seems to have changed recently: https://github.com/grpc/grpc-java/pull/5546

Can you:
- Update all dependencies to the latest version
- Make sure that you do not have any dependency conflicts

If the issue still occurs, please share the output of `mvn dependency:tree`.

**Comment by ChenChiaHung** [comment]
@schmidt-sebastian @jexom I'm also facing this same problem in my docker container. the following is my output of `mvn dependency: tree` for your reference.
Thanks for looking into this issue. :-)

[INFO] --- maven-dependency-plugin:3.1.1:tree (default-cli) @ testframework-core ---
[INFO] io.github.carousell:testframework-core:jar:test-SNAPSHOT
[INFO] +- io.cucumber:cucumber-java:jar:4.5.4:compile
[INFO] |  \- org.apiguardian:apiguardian-api:jar:1.1.0:compile
[INFO] +- org.seleniumhq.selenium:selenium-chrome-driver:jar:3.141.59:compile
[INFO] |  +- org.apache.commons:commons-exec:jar:1.3:compile
[INFO] |  +- com.google.guava:guava:jar:28.0-jre:compile
[INFO] |  |  +- com.google.guava:failureaccess:jar:1.0.1:compile
[INFO] |  |  +- com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[INFO] |  |  +- org.checkerframework:checker-qual:jar:2.8.1:compile
[INFO] |  |  +- com.google.errorprone:error_prone_annotations:jar:2.3.2:compile
[INFO] |  |  +- com.google.j2objc:j2objc-annotations:jar:1.3:compile
[INFO] |  |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.17:compile
[INFO] |  +- com.squareup.okhttp3:okhttp:jar:3.11.0:compile
[INFO] |  \- com.squareup.okio:okio:jar:1.14.0:compile
[INFO] +- io.rest-assured:rest-assured:jar:3.1.0:compile
[INFO] |  +- org.codehaus.groovy:groovy:jar:2.4.12:compile
[INFO] |  +- org.codehaus.groovy:groovy-xml:jar:2.4.12:compile
[INFO] |  +- org.apache.httpcomponents:httpclient:jar:4.5.3:compile
[INFO] |  +- org.apache.httpcomponents:httpmime:jar:4.5.1:compile
[INFO] |  +- org.hamcrest:hamcrest-core:jar:1.3:compile
[INFO] |  +- org.hamcrest:hamcrest-library:jar:1.3:compile
[INFO] |  +- org.ccil.cowan.tagsoup:tagsoup:jar:1.2.1:compile
[INFO] |  \- io.rest-assured:xml-path:jar:3.1.0:compile
[INFO] |     \- javax.xml.bind:jaxb-api:jar:2.2.12:compile
[INFO] +- io.rest-assured:json-path:jar:3.1.0:compile
[INFO] |  +- org.codehaus.groovy:groovy-json:jar:2.4.12:compile
[INFO] |  \- io.rest-assured:rest-assured-common:jar:3.1.0:compile
[INFO] +- javax.annotation:javax.annotation-api:jar:1.2:compile
[INFO] +- com.github.javafaker:javafaker:jar:0.15:compile
[INFO] |  +- org.yaml:snakeyaml:jar:android:1.20:compile
[INFO] |  \- com.github.mifmif:generex:jar:1.0.2:compile
[INFO] |     \- dk.brics.automaton:automaton:jar:1.11-8:compile
[INFO] +- io.cucumber:cucumber-core:jar:4.5.4:compile
[INFO] |  +- io.cucumber:gherkin:jar:5.1.0:compile
[INFO] |  +- io.cucumber:tag-expressions:jar:1.1.1:compile
[INFO] |  +- io.cucumber:cucumber-expressions:jar:7.0.2:compile
[INFO] |  \- io.cucumber:datatable:jar:1.1.14:compile
[INFO] |     \- io.cucumber:datatable-dependencies:jar:1.1.14:compile
[INFO] +- org.slf4j:slf4j-api:jar:1.8.0-beta2:compile
[INFO] +- org.slf4j:jcl-over-slf4j:jar:1.8.0-beta2:compile
[INFO] +- org.assertj:assertj-core:jar:3.9.1:compile
[INFO] +- org.mockito:mockito-core:jar:2.18.3:compile
[INFO] |  +- net.bytebuddy:byte-buddy-agent:jar:1.8.5:compile
[INFO] |  \- org.objenesis:objenesis:jar:2.6:compile
[INFO] +- com.github.stefanbirkner:system-rules:jar:1.19.0:compile
[INFO] +- junit:junit:jar:4.12:compile
[INFO] +- com.google.protobuf:protobuf-java:jar:3.8.0:compile
[INFO] +- org.apache.commons:commons-lang3:jar:3.7:compile
[INFO] +- org.apache.httpcomponents:httpcore:jar:4.4.9:compile
[INFO] +- org.seleniumhq.selenium:selenium-remote-driver:jar:3.141.59:compile
[INFO] +- org.seleniumhq.selenium:selenium-support:jar:3.141.59:compile
[INFO] +- org.seleniumhq.selenium:selenium-api:jar:3.141.59:compile
[INFO] +- ch.qos.logback:logback-core:jar:1.3.0-alpha4:compile
[INFO] +- ch.qos.logback:logback-classic:jar:1.3.0-alpha4:runtime
[INFO] |  \- com.sun.mail:javax.mail:jar:1.6.0:runtime
[INFO] |     \- javax.activation:activation:jar:1.1:runtime
[INFO] +- org.openpnp:opencv:jar:3.4.2-1:compile
[INFO] +- io.github.bonigarcia:webdrivermanager:jar:2.2.1:compile
[INFO] |  +- com.google.code.gson:gson:jar:2.8.0:compile
[INFO] |  +- org.rauschig:jarchivelib:jar:0.7.1:compile
[INFO] |  |  \- org.apache.commons:commons-compress:jar:1.9:compile
[INFO] |  \- org.jsoup:jsoup:jar:1.10.2:compile
[INFO] +- com.googlecode.json-simple:json-simple:jar:1.1.1:compile
[INFO] +- commons-io:commons-io:jar:2.6:compile
[INFO] +- com.amazonaws:aws-java-sdk-s3:jar:1.11.475:compile
[INFO] |  +- com.amazonaws:aws-java-sdk-kms:jar:1.11.475:compile
[INFO] |  \- com.amazonaws:jmespath-java:jar:1.11.475:compile
[INFO] +- com.amazonaws:aws-java-sdk-core:jar:1.11.475:compile
[INFO] |  +- commons-logging:commons-logging:jar:1.1.3:compile
[INFO] |  +- software.amazon.ion:ion-java:jar:1.0.2:compile
[INFO] |  +- com.fasterxml.jackson.core:jackson-databind:jar:2.9.9:compile
[INFO] |  |  +- com.fasterxml.jackson.core:jackson-annotations:jar:2.9.9:compile
[INFO] |  |  \- com.fasterxml.jackson.core:jackson-core:jar:2.9.9:compile
[INFO] |  +- com.fasterxml.jackson.dataformat:jackson-dataformat-cbor:jar:2.9.9:compile
[INFO] |  \- joda-time:joda-time:jar:2.8.1:compile
[INFO] +- com.amazonaws:aws-java-sdk-secretsmanager:jar:1.11.475:compile
[INFO] +- com.amazonaws:aws-java-sdk-sqs:jar:1.11.475:compile
[INFO] +- org.springframework:spring-context:jar:5.0.7.RELEASE:compile
[INFO] |  +- org.springframework:spring-aop:jar:5.0.7.RELEASE:compile
[INFO] |  +- org.springframework:spring-core:jar:5.0.7.RELEASE:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:5.0.7.RELEASE:compile
[INFO] |  \- org.springframework:spring-expression:jar:5.0.7.RELEASE:compile
[INFO] +- org.springframework:spring-test:jar:5.0.7.RELEASE:compile
[INFO] +- org.springframework:spring-beans:jar:5.0.7.RELEASE:compile
[INFO] +- org.springframework.retry:spring-retry:jar:1.1.5.RELEASE:compile
[INFO] +- com.amazonaws:aws-java-sdk-dynamodb:jar:1.11.475:compile
[INFO] +- io.appium:java-client:jar:7.0.0:compile
[INFO] |  +- org.seleniumhq.selenium:selenium-java:jar:3.141.59:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-edge-driver:jar:3.141.59:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-firefox-driver:jar:3.141.59:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-ie-driver:jar:3.141.59:compile
[INFO] |  |  +- org.seleniumhq.selenium:selenium-opera-driver:jar:3.141.59:compile
[INFO] |  |  \- org.seleniumhq.selenium:selenium-safari-driver:jar:3.141.59:compile
[INFO] |  +- cglib:cglib:jar:3.2.8:compile
[INFO] |  |  +- org.ow2.asm:asm:jar:6.2.1:compile
[INFO] |  |  \- org.apache.ant:ant:jar:1.10.3:compile
[INFO] |  |     \- org.apache.ant:ant-launcher:jar:1.10.3:compile
[INFO] |  +- commons-validator:commons-validator:jar:1.6:compile
[INFO] |  |  +- commons-beanutils:commons-beanutils:jar:1.9.2:compile
[INFO] |  |  +- commons-digester:commons-digester:jar:1.8.1:compile
[INFO] |  |  \- commons-collections:commons-collections:jar:3.2.2:compile
[INFO] |  \- org.aspectj:aspectjweaver:jar:1.9.1:compile
[INFO] +- io.cucumber:cucumber-junit:jar:4.5.4:compile
[INFO] +- org.slf4j:jul-to-slf4j:jar:1.8.0-beta2:compile
[INFO] +- net.bytebuddy:byte-buddy:jar:1.9.13:compile
[INFO] +- com.google.firebase:firebase-admin:jar:6.10.0:compile
[INFO] |  +- com.google.api-client:google-api-client:jar:1.30.1:compile
[INFO] |  |  \- com.google.oauth-client:google-oauth-client:jar:1.30.1:compile
[INFO] |  +- com.google.api-client:google-api-client-gson:jar:1.30.1:compile
[INFO] |  |  \- com.google.http-client:google-http-client-gson:jar:1.30.1:compile
[INFO] |  +- com.google.http-client:google-http-client:jar:1.30.1:compile
[INFO] |  |  \- io.opencensus:opencensus-contrib-http-util:jar:0.21.0:compile
[INFO] |  +- com.google.cloud:google-cloud-storage:jar:1.79.0:compile
[INFO] |  |  \- com.google.apis:google-api-services-storage:jar:v1-rev20190523-1.28.0:compile
[INFO] |  +- io.netty:netty-codec-http:jar:4.1.34.Final:compile
[INFO] |  |  +- io.netty:netty-common:jar:4.1.34.Final:compile
[INFO] |  |  +- io.netty:netty-buffer:jar:4.1.34.Final:compile
[INFO] |  |  \- io.netty:netty-codec:jar:4.1.34.Final:compile
[INFO] |  +- io.netty:netty-handler:jar:4.1.34.Final:compile
[INFO] |  \- io.netty:netty-transport:jar:4.1.34.Final:compile
[INFO] |     \- io.netty:netty-resolver:jar:4.1.34.Final:compile
[INFO] +- com.google.api:api-common:jar:1.8.1:compile
[INFO] |  \- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO] +- com.google.auth:google-auth-library-oauth2-http:jar:0.16.1:compile
[INFO] |  +- com.google.auth:google-auth-library-credentials:jar:0.16.1:compile
[INFO] |  \- com.google.http-client:google-http-client-jackson2:jar:1.30.1:compile
[INFO] +- com.google.cloud:google-cloud-firestore:jar:1.9.0:compile
[INFO] |  +- com.google.cloud:google-cloud-core-grpc:jar:1.79.0:compile
[INFO] |  |  +- io.grpc:grpc-protobuf:jar:1.21.0:compile
[INFO] |  |  |  \- io.grpc:grpc-protobuf-lite:jar:1.21.0:compile
[INFO] |  |  \- io.grpc:grpc-context:jar:1.21.0:compile
[INFO] |  +- com.google.api:gax-grpc:jar:1.46.1:compile
[INFO] |  |  +- org.threeten:threetenbp:jar:1.3.3:compile
[INFO] |  |  \- io.grpc:grpc-alts:jar:1.21.0:compile
[INFO] |  |     \- io.grpc:grpc-grpclb:jar:1.21.0:compile
[INFO] |  +- com.google.api.grpc:proto-google-cloud-firestore-admin-v1:jar:1.9.0:compile
[INFO] |  +- com.google.api.grpc:proto-google-cloud-firestore-v1:jar:1.9.0:compile
[INFO] |  +- com.google.api.grpc:proto-google-cloud-firestore-v1beta1:jar:0.62.0:compile
[INFO] |  +- io.grpc:grpc-netty-shaded:jar:1.21.0:compile
[INFO] |  |  \- io.grpc:grpc-core:jar:1.21.0:compile (version selected from constraint [1.21.0,1.21.0])
[INFO] |  |     +- com.google.android:annotations:jar:4.1.1.4:compile
[INFO] |  |     \- io.opencensus:opencensus-contrib-grpc-metrics:jar:0.21.0:compile
[INFO] |  +- io.grpc:grpc-stub:jar:1.21.0:compile
[INFO] |  |  \- io.grpc:grpc-api:jar:1.21.0:compile
[INFO] |  +- io.grpc:grpc-auth:jar:1.21.0:compile
[INFO] |  +- io.opencensus:opencensus-api:jar:0.21.0:compile
[INFO] |  \- io.opencensus:opencensus-contrib-grpc-util:jar:0.21.0:compile
[INFO] +- com.google.cloud:google-cloud-bigquery:jar:1.87.0:compile
[INFO] |  +- com.google.cloud:google-cloud-core-http:jar:1.87.0:compile
[INFO] |  |  +- com.google.http-client:google-http-client-appengine:jar:1.31.0:compile
[INFO] |  |  \- com.google.api:gax-httpjson:jar:0.64.1:compile
[INFO] |  \- com.google.apis:google-api-services-bigquery:jar:v2-rev20190807-1.30.1:compile
[INFO] +- com.google.cloud:google-cloud-core:jar:1.79.0:compile
[INFO] |  +- com.google.api:gax:jar:1.46.1:compile
[INFO] |  +- com.google.protobuf:protobuf-java-util:jar:3.7.1:compile
[INFO] |  +- com.google.api.grpc:proto-google-common-protos:jar:1.16.0:compile
[INFO] |  \- com.google.api.grpc:proto-google-iam-v1:jar:0.12.0:compile
[INFO] \- commons-codec:commons-codec:jar:1.9:compile

**Comment by jexom** [comment]
So the only explicit dependency left in the project is firebase-admin and the problem persists. The exception is only thrown when launching the jar with dependencies. The regular jar with dependencies copied to the lib folder works as expected.
Here's the dependency tree
```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ FirestoreTest ---
[INFO] me.jexom.Firestore:FirestoreTest:jar:1.0
[INFO] \- com.google.firebase:firebase-admin:jar:6.10.0:compile
[INFO]    +- com.google.api-client:google-api-client:jar:1.30.1:compile
[INFO]    |  +- com.google.oauth-client:google-oauth-client:jar:1.30.1:compile
[INFO]    |  \- com.google.http-client:google-http-client-jackson2:jar:1.30.1:compile
[INFO]    |     \- com.fasterxml.jackson.core:jackson-core:jar:2.9.9:compile
[INFO]    +- com.google.api-client:google-api-client-gson:jar:1.30.1:compile
[INFO]    |  \- com.google.http-client:google-http-client-gson:jar:1.30.1:compile
[INFO]    |     \- com.google.code.gson:gson:jar:2.8.5:compile
[INFO]    +- com.google.http-client:google-http-client:jar:1.30.1:compile
[INFO]    |  +- org.apache.httpcomponents:httpclient:jar:4.5.8:compile
[INFO]    |  |  +- org.apache.httpcomponents:httpcore:jar:4.4.11:compile
[INFO]    |  |  +- commons-logging:commons-logging:jar:1.2:compile
[INFO]    |  |  \- commons-codec:commons-codec:jar:1.11:compile
[INFO]    |  +- com.google.code.findbugs:jsr305:jar:3.0.2:compile
[INFO]    |  +- com.google.j2objc:j2objc-annotations:jar:1.3:compile
[INFO]    |  +- io.opencensus:opencensus-api:jar:0.21.0:compile
[INFO]    |  |  \- io.grpc:grpc-context:jar:1.19.0:compile
[INFO]    |  \- io.opencensus:opencensus-contrib-http-util:jar:0.21.0:compile
[INFO]    +- com.google.api:api-common:jar:1.8.1:compile
[INFO]    |  \- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO]    +- com.google.auth:google-auth-library-oauth2-http:jar:0.16.1:compile
[INFO]    |  \- com.google.auth:google-auth-library-credentials:jar:0.16.1:compile
[INFO]    +- com.google.cloud:google-cloud-storage:jar:1.79.0:compile
[INFO]    |  +- com.google.cloud:google-cloud-core:jar:1.79.0:compile
[INFO]    |  |  +- com.google.api:gax:jar:1.46.1:compile
[INFO]    |  |  +- com.google.protobuf:protobuf-java-util:jar:3.7.1:compile
[INFO]    |  |  +- com.google.api.grpc:proto-google-common-protos:jar:1.16.0:compile
[INFO]    |  |  \- com.google.api.grpc:proto-google-iam-v1:jar:0.12.0:compile
[INFO]    |  +- com.google.cloud:google-cloud-core-http:jar:1.79.0:compile
[INFO]    |  |  +- com.google.http-client:google-http-client-appengine:jar:1.30.1:compile
[INFO]    |  |  \- com.google.api:gax-httpjson:jar:0.63.1:compile
[INFO]    |  \- com.google.apis:google-api-services-storage:jar:v1-rev20190523-1.28.0:compile
[INFO]    +- com.google.cloud:google-cloud-firestore:jar:1.9.0:compile
[INFO]    |  +- com.google.cloud:google-cloud-core-grpc:jar:1.79.0:compile
[INFO]    |  |  +- com.google.protobuf:protobuf-java:jar:3.7.1:compile
[INFO]    |  |  \- io.grpc:grpc-protobuf:jar:1.21.0:compile
[INFO]    |  |     \- io.grpc:grpc-protobuf-lite:jar:1.21.0:compile
[INFO]    |  +- com.google.api:gax-grpc:jar:1.46.1:compile
[INFO]    |  |  +- org.threeten:threetenbp:jar:1.3.3:compile
[INFO]    |  |  \- io.grpc:grpc-alts:jar:1.21.0:compile
[INFO]    |  |     +- io.grpc:grpc-grpclb:jar:1.21.0:compile
[INFO]    |  |     \- org.apache.commons:commons-lang3:jar:3.5:compile
[INFO]    |  +- com.google.api.grpc:proto-google-cloud-firestore-admin-v1:jar:1.9.0:compile
[INFO]    |  +- com.google.api.grpc:proto-google-cloud-firestore-v1:jar:1.9.0:compile
[INFO]    |  +- com.google.api.grpc:proto-google-cloud-firestore-v1beta1:jar:0.62.0:compile
[INFO]    |  +- io.grpc:grpc-netty-shaded:jar:1.21.0:compile
[INFO]    |  |  \- io.grpc:grpc-core:jar:1.21.0:compile (version selected from constraint [1.21.0,1.21.0])
[INFO]    |  |     +- com.google.android:annotations:jar:4.1.1.4:compile
[INFO]    |  |     \- io.opencensus:opencensus-contrib-grpc-metrics:jar:0.21.0:compile
[INFO]    |  +- io.grpc:grpc-stub:jar:1.21.0:compile
[INFO]    |  |  \- io.grpc:grpc-api:jar:1.21.0:compile
[INFO]    |  +- io.grpc:grpc-auth:jar:1.21.0:compile
[INFO]    |  \- io.opencensus:opencensus-contrib-grpc-util:jar:0.21.0:compile
[INFO]    +- com.google.guava:guava:jar:26.0-android:compile
[INFO]    |  +- org.checkerframework:checker-compat-qual:jar:2.5.2:compile
[INFO]    |  +- com.google.errorprone:error_prone_annotations:jar:2.1.3:compile
[INFO]    |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.14:compile
[INFO]    +- org.slf4j:slf4j-api:jar:1.7.25:compile
[INFO]    +- io.netty:netty-codec-http:jar:4.1.34.Final:compile
[INFO]    |  +- io.netty:netty-common:jar:4.1.34.Final:compile
[INFO]    |  +- io.netty:netty-buffer:jar:4.1.34.Final:compile
[INFO]    |  \- io.netty:netty-codec:jar:4.1.34.Final:compile
[INFO]    +- io.netty:netty-handler:jar:4.1.34.Final:compile
[INFO]    \- io.netty:netty-transport:jar:4.1.34.Final:compile
[INFO]       \- io.netty:netty-resolver:jar:4.1.34.Final:compile
```

**Comment by schmidt-sebastian** [comment]
I think you version of Google-Gax is too new. Unfortunately, we don't seem to be specifying a dependency version for this library: https://mvnrepository.com/artifact/com.google.cloud/google-cloud-firestore

As a short term work-around, I will ping Hiranya to update the Firebase Admin Java dependency of Firestore to the latest version. We will then also have to fix the GAX dependency of the Firestore SDK itself.

**Comment by ChenChiaHung** [comment]
@schmidt-sebastian 
Thanks for providing the short term workaround on this issue.
It works on our test environment after using a hard dependency on Firestore 1.20.0.
I will keep waiting for the latest version including fixes.
Thank you. :-)

**Comment by manjotsidhu** [comment]
I am still facing this issue.. `pom.xml` can be seen from here : https://github.com/manjotsidhu/SmartClassrooms-Hardware/blob/pi/pom.xml

**Comment by manjotsidhu** [comment]
Just updated to `6.11.0` ... Fixed! Thanks
