### ISSUE TITLE
com/google/api/core/ApiFuture: java.lang.NoClassDefFoundError java.lang.NoClassDefFoundError: com/google/api/core/ApiFuture

### ISSUE THREAD

**Issue by boluok** [firebase/firebase-admin-java#315]
`  FirebaseApp.initializeApp(options)`

Throws this exception when running in an AWS Lambda Function 

`com/google/api/core/ApiFuture: java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: com/google/api/core/ApiFuture
at utils.FirebaseUtils.<clinit>(FirebaseUtils.kt:29)
at lamdas.CourseManagerLambda.handleRequest(CourseManagerLambda.kt:57)`

**Comment by hiranya911** [comment]
Make sure api-commons library is in the classpath.

**Comment by boluok** [comment]
I already have this in my gradle 

> implementation 'com.google.api-client:google-api-client:1.30.2'

But the issue still persists

**Comment by hiranya911** [comment]
`ApiFuture` class comes from the `api-commons` library -- not `google-api-client`.

Unless you can provide a minimal repro with just the Admin SDK, you will have to debug this as a classloading issue specific to your environment (AWS Lambda) and your code. I also see a `FirebaseUtils` Kotlin file mentioned in the error message. That seems to be part of your code. All we can say is that by the time that file is loaded, the `api-commons` library has not been loaded to the runtime.

**Comment by boluok** [comment]
The  `FirebaseUtils` calls this line of code `FirebaseApp.initializeApp(options)` before this issue, it works fine when i run it on my computer but when i deploy it to AWS i get this issue. Does that mean it is environment specific or should i proceed to with the minimal repro

**Comment by hiranya911** [comment]
We can't tell why a certain class would fail to load in AWS Lambda. Most common reason is that jar file did not get uploaded with your code. If you think it's an issue with the SDK and can be addressed in this repo, provide us a minimal, independent repro so we can take a look.
