### ISSUE TITLE
Firestore conflicting with Cloud Scheduler library

### ISSUE THREAD

**Issue by Sdwz** [firebase/firebase-admin-java#316]
### Describe your environment

  * Operating System version: AppEngine Java 8 standard
  * Firebase SDK version: 6.10.0
  * Library version: 6.10.0
  * Firebase Product: Firestore

#### Steps to reproduce:

I recently had to use Cloud Scheduler to trigger tasks for my AppEngine project.

Adding the dependency to the project : 

```
implementation 'com.google.apis:google-api-services-cloudscheduler:v1-rev4-1.25.0'
implementation 'com.google.auth:google-auth-library-oauth2-http:0.17.2'
```
(The latest I had to add cause GoogleCredential depreciation)

From there, Firestore stopped working due to some opencensus library deprecation, logs are as follow : 

```
java.lang.IllegalAccessError: tried to access field io.opencensus.trace.unsafe.ContextUtils.CONTEXT_SPAN_KEY from class io.grpc.internal.CensusTracingModule$TracingClientInterceptor
```

Checking the google-cloud-firestore library, it seems the problem was already fixed. So I tried to update my configuration as follow : 

```
implementation("com.google.firebase:firebase-admin:6.10.0")  {
	exclude group: "com.google.cloud", module: "google-cloud-firestore"
}
implementation 'com.google.cloud:google-cloud-firestore:1.26.0'
```

From there, the dependency issue seems to be gone, although none of my query are performed correctly (at least in less than 60 seconds).

#### Relevant Code:

Reduced for lisibility : 

```
FirestoreClient
                .getFirestore()
                .collection("my_collection")
                .whereEqualTo("id", object.getId())
                .get()
                .get()
```

The collection contains 15 documents, id is indexed, and the query times out when the AppEngine thread serving is dying, but it spent 58 seconds performing it (which is almost 58 more seconds than our firebase client on the frontend for the same query)

**Comment by hiranya911** [comment]
Can you provide a minimal repro? Ideally something we can deploy to App Engine and test.

Also, have you verified whether the code works locally (i.e. outside App Engine)?

**Comment by Sdwz** [comment]
Thanks for your reply.

Let me takes this as a next step :

1. Just read a couple issue here and a good first idea would be to raise the logging level to understand what's happening in the background
2. As for the dependencies issues, it's similar to https://github.com/firebase/firebase-admin-java/issues/310
3. Will try to replicate locally
4. Going to make a small spring boot app and see if it happens once deployed and share it here.

Will report my finding asap.

**Comment by Sdwz** [comment]
1. Increasing logging level this is all I have 

https://gist.github.com/Sdwz/0be97b318be484ac08296b82ce0f1903

**Comment by Sdwz** [comment]
3. Seems like I got my hands on it. Updating firestore lib didn't fix the issue actually, exception is just swallowed it seems.

Made a small class within my project to test with all the deps I have :

https://gist.github.com/Sdwz/40b670e5316711f2eb0c5d732de98b36

which produced the following : 

https://gist.github.com/Sdwz/14a31346c0326722ddb68439db740b17

So seems like the opencensus issue is still the cause.

**Comment by Sdwz** [comment]
Moving on so you guys don't waste your time : Made a new app and added the cloud scheduler library and it seems to be working fine. It's only within mine it's failing. It has to be revolving around spring cloud.

**Comment by Sdwz** [comment]
Updated to Spring Cloud SR3, issue is fixed !

**Comment by schmidt-sebastian** [comment]
@Sdwz Thank you for your updates. I am glad to hear that things worked out!
