### ISSUE TITLE
FR: Let developers have tools to administer users

### ISSUE THREAD

**Issue by swftvsn** [firebase/firebase-admin-java#33]
It would be really nice to have feature parity with node-admin, that has these tools to manage users.

**Comment by hiranya911** [comment]
This is actually  one of our more popular feature requests. I'm planning to prioritize and implement it in the near future. Stay tuned.

**Comment by swftvsn** [comment]
Awesome! Can't wait :)

**Comment by Solido** [comment]
Thanks this is currently a complete no go to firebase because of this but I'm now impatient to start working on it.

**Comment by hiranya911** [comment]
I have this feature under development at https://github.com/firebase/firebase-admin-java/tree/hkj-user-mgt

**Comment by hiranya911** [comment]
This has been released in [v5.1.0](https://firebase.google.com/support/release-notes/admin/java#5.1.0)

**Comment by swftvsn** [comment]
Absolutely fabulous work! Pass on the compliments to the whole team!

The documentation has also been updated which is awesome, and as an Java guy myself, one could also tick another box in the feature matrix in https://firebase.google.com/docs/admin/setup "Java" column. :)

Thanks again, I'll head back to my code now :D

**Comment by hiranya911** [comment]
Thanks @swftvsn :) 

And thanks for the reminder about the feature matrix. We have updated it now.
