### ISSUE TITLE
Tenants support in Java Admin SDK

### ISSUE THREAD

**Issue by vkercan** [firebase/firebase-admin-java#332]
Support for user management based on a Tenant is currently not yet supported in Java Admin SDK, although Google Cloud Identity Platform already supports this (https://cloud.google.com/blog/products/identity-security/multi-tenancy-support-identity-platform-now-generally-available).

Would be helpful to extend this support also in Java Admin SDK.

**Comment by hiranya911** [comment]
@micahstairs FYA

**Comment by micahstairs** [comment]
Thanks for the feature request! Fortunately, I've already begun working on this. We are still in the early stages (working out the design for the API), but once I begin working on the implementation, this issue will track my progress.

**Comment by micahstairs** [comment]
Thanks for your patience! This has now been released. See https://github.com/firebase/firebase-admin-java/releases/tag/v6.15.0.
