### ISSUE TITLE
Documents for Error Code

### ISSUE THREAD

**Issue by kui** [firebase/firebase-admin-java#335]
* Firebase SDK version: 6.9.0
* Firebase Product: cloud message

Can I check error code descriptions how we should handle it like [admin SDK guide][]?

I expected that firebase-admin-java raises error code strings with "messaging/" prefix like "messaging/registration-token-not-registered". But actually, it raises it without the prefix like "registration-token-not-registered".

I think that firebase-admin-java does not follow the specs of error code in the above admin SDK guide. So I want error code documents in firebase-admin-java.

[admin SDK guide]: https://firebase.google.com/docs/cloud-messaging/send-message?hl=en#admin

**Comment by hiranya911** [comment]
The prefixed error codes are only really supported in the Node.js SDK. Java SDK currently uses unprefixed error codes.

The error handling support is going through a major overhaul. So far we've implemented this for Python and .NET, while Java is next in our list. This will significantly change how error codes are exposed. In case of Java there will be enum types for error codes which will make it easier to check and compare different error codes.

**Comment by kui** [comment]
Thank you! I will treat these as error codes without the prefix in this version.
