### ISSUE TITLE
Incorrect timestamp format in AndroidNotification.event_time

### ISSUE THREAD

**Issue by hiranya911** [firebase/firebase-admin-java#337]
I think the way we format the `event_time` field on `AndroidNotification` is wrong:

https://github.com/firebase/firebase-admin-java/blob/83b7a64c103fbf20f46c04df229000529e9a8d2d/src/main/java/com/google/firebase/messaging/AndroidNotification.java#L458-L462

There seems to be couple of issues with this.

1. We are not specifying the timezone for the `SimpleDateFormat`. Therefore the resulting timestamp string is in the local timezone while the backend expects it to be in UTC.
2. The way nanoseconds are formatted seems to be wrong. For the milliseconds value `1546304523123L` this generates the string `2019-01-01T01:02:03.000000123Z`. I would expect the nanos to be formatted as `123000000` (i.e. 123 milliseconds in nanos).

**Comment by chong-shao** [comment]
I think you are correct on both issues:
1. Yes currently it formats based on the local timezone. Should change to UTC.
2. I think RFC3339 does not specify how nanoseconds should be formatted. But in Java class SimpleDateFormat, 'S' means Milliseconds. So I think I should just format it into 'SSS' and append '000000' after the 'SSS'. 

Will add a fix soon.
