### ISSUE TITLE
ListUsersPage: class not found

### ISSUE THREAD

**Issue by abelardolg** [firebase/firebase-admin-java#341]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: UBUNTU
  * Firebase SDK version: where can I get it?
  * Library version: firebase-auth:19.2.0
  * Firebase Product: auth (auth, database, storage, etc)

### [REQUIRED] Step 3: Describe the problem
The method listUsers doesn't exist in FirebaseAuth.getInstance().listUsers(null);

#### Steps to reproduce:
To follow these instructions, I created an Android app today: 
// Start listing users from the beginning, 1000 at a time.
```
ListUsersPage page = FirebaseAuth.getInstance().listUsers(null);
while (page != null) {
  for (ExportedUserRecord user : page.getValues()) {
    System.out.println("User: " + user.getUid());
  }
  page = page.getNextPage();
}
```

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.
Type these lines of code.

#### Relevant Code:
// Start listing users from the beginning, 1000 at a time.
ListUsersPage page = FirebaseAuth.getInstance().listUsers(null);
while (page != null) {
  for (ExportedUserRecord user : page.getValues()) {
    System.out.println("User: " + user.getUid());
  }
  page = page.getNextPage();
}
```
// TODO(you): code here to reproduce the problem
```

**Comment by hiranya911** [comment]
`firebase-auth:19.2.0` 

That's the Android SDK. `listUsers()` is part of the Admin SDK (artifact ID `firebase-admin`).

**Comment by abelardolg** [comment]
Thanks, @hiranya911 
I took a look at the documentation but it inside of auth.

Best regards.
