### ISSUE TITLE
FirebaseOptions Not Found in jar build using gradle

### ISSUE THREAD

**Issue by feras-ngss** [firebase/firebase-admin-java#346]
Describe your environment
Am using Pure Java to Build a library to use inside Spring boot projects.

  * Operating System version: _____(Server Side Application) , deveolpment on Mac OS
  * Firebase SDK version: _____ admin-SDK 6.12.0
  * Library version: _____
  * Firebase Product: _____ (auth, database, storage, etc)

 Describe the problem
the problem is that am built a library that implements Firebase inside.
but When am Building the project as an External Jar file to Implement in the Other Projects, am Getting Class Not Found Exception.

Caused by: java.lang.ClassNotFoundException: com.google.firebase.FirebaseOptions$Builder

#### Relevant Code:
Just a regular Code like what mentioned in the Docs
```java
FirebaseOptions options = (new Builder()).setCredentials(GoogleCredentials.fromStream(this.fileInputStream)).setDatabaseUrl(this.fireBaseUrl).build();
        FirebaseApp.initializeApp(options);
        this.dbReference = FirebaseDatabase.getInstance().getReference();
```

**Comment by hiranya911** [comment]
All we can say is that Firebase classes are not available in your application classpath. It's not clear how you were planning to make them available for your application, so we cannot provide any specific instructions. 

Please use StackOverflow for this type of usage questions.

**Comment by feras-ngss** [comment]
I did search Stack Over Flow,
what am building basically Is a library that Maps all the Data and interact with FCM.
for the Clients that using the Api(LIB) am Building a Jar File out of the the project to use it. I used to use this Kind of stuff.
but with FireBaseOptions Case when am Building the Api using gradle and try to access the login in the Clients am Getting that the Class FirebaseOptions is not Exist in the Build, and that Does not make sense at all
Thanks for helping.

**Comment by hiranya911** [comment]
I'd start by checking if the `com.google.firebase` packages are correctly packaged into your library (if that's how you intended to put those classes in the application classpath). Otherwise make sure the `firebase-admin` jar is in the classpath of the application.
