### ISSUE TITLE
Message.builder().putAllData() Does not Accept HashMap<String, Object>

### ISSUE THREAD

**Issue by Bonythomasv** [firebase/firebase-admin-java#348]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to firebase Messaging the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Mac
  * Firebase SDK version: 6.11.0
  * Library version: 6.11.0
  * Firebase Product: cloud messaging (auth, database, storage, etc)

### [REQUIRED] Step 3: Describe the problem
 Message.builder().putData()
MulticastMessage.builder().putAllData()
does currently accept a Hashmap<String,String> . We would need HashMap<String, Object> to has some nested JSON objects in this field. FCM API has this feature. so excepting to see the same in Admin SDK as well.

#### Steps to reproduce:

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

#### Relevant Code:
    val notificationMessage: MulticastMessage = MulticastMessage.builder().setAndroidConfig(androidConfig)
                //.putData("test_message","message from Local")
                .putAllData(testMap as MutableMap<String, String>?)

Excepted to pass objects as HasMap values in addition to String values.

```
// TODO(you): code here to reproduce the problem
```

**Comment by Bonythomasv** [comment]
Data Object with HasMap<String,Object> seems to work if you hit the API directly.

![Screen Shot 2020-01-13 at 3 33 27 PM](https://user-images.githubusercontent.com/15947082/72293931-21107e00-361a-11ea-82d3-216082c86cd5.png)

**Comment by hiranya911** [comment]
Your screenshots are displaying a call to the legacy FCM API, which is not used in the Java SDK. Java SDK uses the V1 API: https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#Message

As per the documentation this API requires values to be strings:

```
"data": {
    string: string,
    ...
},
```

I don't know in practice if this API accepts non-string data values as well. But either way we can't just change the method signature, as that would be a breaking change. I'll assign to the FCM team to see what they think.

**Comment by Bonythomasv** [comment]
@hiranya911 
I've also tried using the below URL ( new V1 Endpoint) and that seems to work if I hit the API directly. If not a Breaking change, would you be able to provide a Override method which accepts Object, I can try putting together PR if that helps.

WE had been using the Direct API over three years and we were looking to switch to use FCM Admin SDK and this came as a blocker for us.
https://fcm.googleapis.com/v1/projects/<Project Name>/messages:send

**Comment by hiranya911** [comment]
@chong-shao what do you think?

**Comment by Bonythomasv** [comment]
@hiranya911 my Bad the V1 API only Accepts String:String
But the legacy API still accepts String: Object, Is this something we can bake into Admin SDK for legacy API?

**Comment by hiranya911** [comment]
@Bonythomasv we are actually looking into turning down the legacy API altogether. Only our Node.js SDK supports it (this is because the Node.js SDK predates the FCM v1 API). But the FCM team may be open to supporting non-string data values in the v1 API.

**Comment by Bonythomasv** [comment]
@hiranya911 Can you tag someone from FCM team, or Do you want me to move this issue another repo?

**Comment by chong-shao** [comment]
HI @Bonythomasv I'm from the FCM team. We are considering adding non-string support but no plans for the timeline yet.

**Comment by hiranya911** [comment]
@Bonythomasv since this requires backend changes, I'd recommend you to file a feature request at https://firebase.google.com/support. There's nothing we can do in this repo to address this issue. If the backend ever starts supporting non-string data values, we will definitely expose the functionality in the SDK APIs.
