### ISSUE TITLE
FR: Notification priority

### ISSUE THREAD

**Issue by mazu-rok** [firebase/firebase-admin-java#370]
Hi, I want to set a priority for notification for iOS. But I cannot find how to make it.

**Comment by hiranya911** [comment]
Look into the apns-priority header. See APNS docs. 

https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CommunicatingwithAPNs.html#//apple_ref/doc/uid/TP40008194-CH11-SW1

**Comment by leolux** [comment]
And how to set the priority for web and Android?
