### ISSUE TITLE
Unable to install firebase-admin properly

### ISSUE THREAD

**Issue by RaviPrasadP** [firebase/firebase-admin-java#376]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Ubuntu 16.04 LTS
  * Firebase SDK version: 6.12.2
  * Library version: 6.12.2
  * Firebase Product: _____ (auth, database, storage, etc)
  * Maven Version: 2.2.1
  * Java Version: 1.8

### [REQUIRED] Step 3: Describe the problem
1. I am unable to install firebase-admin 6.12.2 in my maven project. While running mvn install command in online mode it is throwing an error (i.e,) it could not able to download the supporting dependencies. For me "com.google.cloud:google-cloud-bom" the artifact is not downloading. 
Note: 
    1. I have analyzed the root cause, maven is downloading dependencies in "http://repo1.maven.org/maven2" whereas "HTTP" is restricted. If I hit as "HTTPS" it is working.

#### Steps to reproduce:
Just run mvn command in online mode. If you run you will get the error as below:
Downloading: http://repo1.maven.org/maven2/com/google/cloud/google-cloud-bom/0.33.0-alpha/google-cloud-bom-0.33.0-alpha.pom
[WARNING] Unable to get resource 'com.google.cloud:google-cloud-bom:pom:0.33.0-alpha' from repository central (http://repo1.maven.org/maven2): Error transferring file: **Server returned HTTP response code: 501 for URL: http://repo1.maven.org/maven2/com/google/cloud/google-cloud-bom/0.33.0-alpha/google-cloud-bom-0.33.0-alpha.pom**
[INFO] ------------------------------------------------------------------------
[ERROR] BUILD ERROR
[INFO] ------------------------------------------------------------------------
[INFO] Failed to resolve artifact.

Unable to get dependency information: Unable to read the metadata file for artifact 'com.google.cloud:google-cloud-storage:jar': POM 'com.google.cloud:google-cloud-bom' not found in repository: Unable to download the artifact from any repository

  com.google.cloud:google-cloud-bom:pom:0.33.0-alpha

from the specified remote repositories:
  central (http://repo1.maven.org/maven2)

 for project com.google.cloud:google-cloud-bom
  com.google.cloud:google-cloud-storage:jar:1.15.0**
============================================================

#### Relevant Code:
POM.xml:
        <dependency>
            <groupId>com.google.firebase</groupId>
            <artifactId>firebase-admin</artifactId>
            <version>6.12.2</version>
        </dependency>

**Comment by RaviPrasadP** [comment]
Please share the fix for this. I need it quickly.

**Comment by hiranya911** [comment]
See https://support.sonatype.com/hc/en-us/articles/360041287334

You need to upgrade Maven
