### ISSUE TITLE
FR: time_to_live as a common field

### ISSUE THREAD

**Issue by kexsteve** [firebase/firebase-admin-java#378]
**version:** com.google.firebase:firebase-admin:6.12.2
**products:** messaging
**references:** 
https://firebase.google.com/docs/cloud-messaging/concept-options, https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages

I wonder if there is a way to enter time_to_live as a common field so we don't have to specify one for each platform.

```json
{
  "message":{
    "token":"bk3RNwTe3H0:CI2k_HHwgIpoDKCIZvvDMExUdFQ3P1...",
    "data":{
      "Nick" : "Mario",
      "body" : "great match!",
      "Room" : "PortugalVSDenmark"
    },
    "apns":{
      "headers":{
        "apns-expiration":"1604750400"
      }
    },
    "android":{
      "ttl":"4500s"
    },
    "webpush":{
      "headers":{
        "TTL":"4500"
      }
    }
  }
}
```

**Comment by hiranya911** [comment]
The existing REST API surface doesn't support that. But feel free to file a feature request at https://firebase.google.com/support
