### ISSUE TITLE
Support @DocumentId annotation?

### ISSUE THREAD

**Issue by achuinard** [firebase/firebase-admin-java#382]
Any chance you could add the @DocumentId Android annotation / functionality into the Firebase Java Admin SDK?

https://firebase.google.com/docs/reference/android/com/google/firebase/firestore/DocumentId

I need to get my ID when deserializing!

**Comment by hiranya911** [comment]
Firestore API is part of the google-cloud-firestore library. Please report at https://github.com/googleapis/java-firestore
