### ISSUE TITLE
FirebaseAuth(JVM version) has no user authentication method.

### ISSUE THREAD

**Issue by erickcabral** [firebase/firebase-admin-java#384]
### [READ] Step 1: Are you in the right place?

  * For issues or feature requests related to __the code in this repository__
    file a Github issue.
    * If this is a __feature request__ make sure the issue title starts with "FR:".
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/)
    with the firebase tag.
  * For general Firebase discussion, use the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk)
    google group.
  * For help troubleshooting your application that does not fall under one
    of the above categories, reach out to the personalized
    [Firebase support channel](https://firebase.google.com/support/).

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: _____ Windows 8
  * Firebase SDK version: _____ FIREBASE-ADMIN
  * Library version: _____6.12.2
  * Firebase Product: _____ AUTH

### [REQUIRED] Step 3: Describe the problem
The problem is simple.

The JVM Firebase Auth version does not have any method to authenticate a firebase user, so it is impossible to authenticate any user using this lib.
[https://mvnrepository.com/artifact/com.google.firebase/firebase-admin](url)
All others lib (Android, IOs, JavaScript...) have a method to authenticate a user. The JVM Admin lib doesn't.
The Firebase Client JVM lib (firebase-client-jvm - version 2.5.2) has the method do authenticate users but it doesn't work at all (I believe the LIB is deprecated).  
[https://mvnrepository.com/artifact/com.firebase/firebase-client-jvm](url)

#### Steps to reproduce:
 Firebase firebase = new Firebase("[PROJECT URL]");
        firebase.authWithPassword("123@123.com", "123", new Firebase.AuthResultHandler() {
            @Override
            public void onAuthenticated(AuthData authData) {
                log.info(">>>>>>>>>>>> LOGGED <<<<<<<<<<<<<<< ");
            }
            @Override
            public void onAuthenticationError(FirebaseError firebaseError) {
                log.warning(">>>>> FIREBSER LOG ERROR >>>> " + firebaseError.getDetails());
            }
        });

#### Relevant Code:

```
// TODO(you): code here to reproduce the problem
```

**Comment by hiranya911** [comment]
Admin SDKs do not provide any user-specific operations. It is for backend administrative operations only. You should perform all user-specific operations in the client apps using one of the client SDKs.

Firebase client JVM library is an old legacy API and is no longer supported.
