### ISSUE TITLE
FR: Provide getters or equals method on the Message class

### ISSUE THREAD

**Issue by danielsiwiec** [firebase/firebase-admin-java#398]
* Library version: 6.12.2
  * Firebase Product: messaging

The `Message` class doesn't provide either getters nor an `equals` method, which would allow an instance of this class to be asserted on in testing. Here's an example of what I'm trying to do:

```Java
Message testMessage = Message.builder()
        .setToken(deviceToken)
        .putAllData(firebaseMessageMap)
        .build();

    Mockito.verify(firebaseMessaging).send(testMessage);
```

What I get in return is:

```
Argument(s) are different! Wanted:
firebaseMessaging bean.send(com.google.firebase.messaging.Message@5402b18c);

Actual invocations have different arguments:
firebaseMessaging bean.send(com.google.firebase.messaging.Message@706dd38b);
```

**Comment by hiranya911** [comment]
@danielsiwiec what is your test case trying to verify? The SDK does not create new instances of `Message`, so it's not clear to me how your test case ended up with 2 instances.

On testing, I'd generally advise you to use one of the following 2 methods:

1. Wrap SDK APIs in your own interfaces and conduct full blackbox testing. That is, do not test the functionality of the SDK. Just test your own code that uses the SDK.
2. Use the `HttpTransport` interface to control how the HTTP requests are made by the SDK (you can configure this via `FirebaseOptions`).

We use the 2nd approach in our own unit tests: https://github.com/firebase/firebase-admin-java/blob/2cfbc3d96d0090593828f78b497ea29c09fcaae1/src/test/java/com/google/firebase/messaging/FirebaseMessagingClientImplTest.java#L494-L507

**Comment by danielsiwiec** [comment]
Ahh, thanks @hiranya911 - I used the first approach, but 2. is really what I was looking for. I appreciate your response!
