### ISSUE TITLE
Incorrect Verified status returned by Firebase Auth Admin SDK Java

### ISSUE THREAD

**Issue by deepfriedbrain** [firebase/firebase-admin-java#407]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: MacOS 10.15.4
  * Firebase SDK version: 6.12.2
  * Library version: (not sure what this is)
  * Firebase Product: auth

### [REQUIRED] Step 3: Describe the problem

I'm migrating my application from Google Identity Toolkit to Firebase Auth. During testing I found that for newly registered and verified users, the Firebase Admin SDK for Java returns the email verification status as false even though the user has clicked the link in their email and verified themselves.

The Firebase client for web (Javascript) returns the correct email verification status (true). This is weird because the client sends the idToken to the server. So both are getting the verification status using the same idToken.

I've tested this by registering multiple test user accounts and it is reproducible every single time.

This is causing problems because I cannot trust the server to return the correct status. When the user sends a request, the server rejects it saying that user's email is not verified. 

The issue gets resolved if the users logs out and logs in again. Then both client and server return the status as true. But I don't see a point in forcing the user to log out and log in again.

#### Relevant Code:

```
FirebaseToken decodedToken;
try {
	decodedToken = FirebaseAuth.getInstance().verifyIdToken(gtoken);
} catch (FirebaseAuthException e) {			
	e.printStackTrace();
	logger.severe("FirebaseAuthException exception thrown.");
	throw new UnauthorizedException(e);
}

if (decodedToken == null) {
	return null;
}

String emailId = decodedToken.getEmail();
logger.info("Firebase user emailId : " + emailId);

boolean isVerified = decodedToken.isEmailVerified();
logger.info("isVerified : " + isVerified); // prints false
```

Please let me know if I'm missing something.

**Comment by hiranya911** [comment]
@deepfriedbrain the Admin SDK is not returning any value on its own. It is simply decoding the values already available in the ID token you've passed to it. The method `isEmailVerified()` just reads the `email_verified` claim on the ID token. 

What's happening here is that your client app is holding on to an old ID token that was issued before the user account was verified. This will automatically refresh within the hour at which point it will have the correct `email_verified` claim. Or you can force the ID token to get refreshed via a login (as you've already observed). You should also be able to fetch a new ID token in the client app by doing something like this:

```
await firebase.auth().currentUser.getIdTokenResult(true);
```

See https://firebase.google.com/docs/reference/js/firebase.User#getidtokenresult

I will close this, since there's no action items for the Admin SDK. If you continue to have issues, please raise an issue for the Firebase Web SDK.

**Comment by deepfriedbrain** [comment]
@hiranya911 Thank you for your response. What you said makes sense. I looked up the client code again and it gets the verification status from User object and not the token.

It would have been good if there was a way to force log out the user out of the application the moment their email address was verified. As such, my client won't know that the user has been verified because the email verification happens completely outside of my application. I knew the API to force refresh the token, but my application won't know when to force it.

I'm using the default email action handlers. Is there a configuration that could force log out the user? I can look at building custom email handlers later. Right now Google Identity Toolkit email / password registration has been disabled and I need to migrate out urgently.

**Comment by hiranya911** [comment]
@deepfriedbrain I'm fairly confident such a configuration does not exist at the moment. Ideally you'd need something like a Functions trigger that runs whenever a user account is verified (which sounds like a great feature request for Functions btw). Can you use `getIdTokenResult(true)` in your client app to side-step this issue?

@bojeil-google do you have any suggestions?

**Comment by bojeil-google** [comment]
Hey @hiranya911 your suggestion makes sense. When you update the user properties, we do not force token refresh until the token expires. If you expect the updated properties to be reflected in the token, you can force refresh as you recommended.

**Comment by deepfriedbrain** [comment]
@hiranya911 I have my own server as well. So I could do it on my server itself. But how would I notify the server? How would calling getIdTokenRequest(true) help in this case? 

@bojeil-google The question is how would my client know when to force token refresh and when not to. The email verification is happening outside of my application. My application does not get notified when user gets verified. I saw some of your responses on Stackoverflow on similar questions and this point is unaddressed in those posts as well. 

Ideally the token should be invalidated once the user's email is verified because the token is stale anyway. Token invalidation happens for password reset, and it should happen for email verification too. Or at least a flag should be provided in the server API to request token invalidation. Then when the user comes back to my site, the client would automatically fetch a refreshed token. This will solve the issue that I'm facing.

I clearly see a gap here. Please correct me if I'm missing something.

**Comment by hiranya911** [comment]
In your client app check `UserReocrd.email_verified` and `IdTokenResult.email_verified` and if they are out of sync, call `getIdTokenResult(true)` to fetch a new token. This needs to be done whenever passing the token to the backend Java server. That's the closest you can get to implementing this use case with the features available today. Anything else is likely to require changes in the Firebase Auth backend, and that sort of changes will take time.

**Comment by deepfriedbrain** [comment]
@hiranya911 Thank you.

I'll test it out today. If it works, this would be a workaround, but not a permanent solution. An extra API call will add latency to every request to the server. But at least I should be able to go live with it. 

I understand that backend changes are not going to be addressed anytime soon.

**Comment by bojeil-google** [comment]
Email verification is very different than password change or email change. We don't want to invalidate a user's tokens after verification as it will require the user re-authenticating.

If you don't agree, you can just invalidate the user's tokens yourself on verification. We offer Admin APIs to revoke all sessions for a specific user. You can do that upon verification.

**Comment by deepfriedbrain** [comment]
@bojeil-google But you are still missing my point. My application does not get notified when user clicks on the email verification link and gets verified. That's happening outside of my application What would invoke a function or method in my application when user gets verified?

**Comment by bojeil-google** [comment]
I understand the issue. You will need to build a mechanism to notify the app. There are different approaches. One common one is to use Firebase RTDB or Firestore change triggers. For verified email endpoints on your server, you can just lookup the user via `getUser` API using the `uid` from the ID token and check `emailVerified`. You can also pass a continue URL with some state in the verification flow. This way on verification, the user clicks the [continue URL](https://firebase.google.com/docs/auth/web/passing-state-in-email-actions) to go back to the app.

**Comment by deepfriedbrain** [comment]
@bojeil-google Thanks. Both approaches make sense to me. Let me try out the suggestions today. I'll update this thread after testing.

**Comment by deepfriedbrain** [comment]
@bojeil-google The approach to `getUser` from `uid` and then call `isEmailVerified()` on it resolved this issue. It gave me the correct verification status of the user.

Thanks a lot to you and @hiranya911

**Comment by deepfriedbrain** [comment]
@bojeil-google Unfortunately there's a problem with the approach that you suggested. Calling `getUser` with `uid` takes about 700ms. That's a bit hit to every request to the server.

`verifyIdToken` itself takes less than 10ms, but to get the user from the decoded token takes about 700ms.

Are you aware of this performance issue? Do you have any suggestions to overcome it?

**Comment by manwithsteelnerves** [comment]
When I first saw email_verified flag was exposed, i was in the thought that I don’t  need to call getUser method for unverified users. But I see that its in-fact the data from the current token. Technically it makes sense but not much useful as the core problem is to know in someway once user finishes the registration step. A note on doc would be helpful that it holds until current token is expired.

Also as mentioned by @hiranya911 a trigger would be helpful on backend once any verification finishes. Currently its totally disjoint. Auth triggers are much helpful to avoid these problems. Or at least a provision to configure a webhook or a pubsub notification.
