### ISSUE TITLE
UserRecord getEmail returns null

### ISSUE THREAD

**Issue by deepfriedbrain** [firebase/firebase-admin-java#429]
Operating System version: MacOS 10.15.5
Firebase SDK version: 6.12.2
Library version: 6.12.2
Firebase Product: auth

I ran into an issue today where `userRecord.getEmail()` returns null, even though the token is verified successfully, and the `decodedToken.getUid()` and `userRecord.getDisplayName()` return proper values.

Can someone explain why the email would be null when the id token has been verified and other fields are valid?

EDIT 1: I found this user by the uid in the Firebase console. The provider is Facebook, but the Identifier is blank. What would cause this?

![image](https://user-images.githubusercontent.com/1531669/83254827-ea5e8d00-a1e1-11ea-9b54-d73db613f10e.png)

EDIT 2: My Firebase App has the setting ""Prevent creation of multiple accounts with the same email address".

Following is the code. In this case, `decodedToken.isEmailVerified()` returned `false`. So the if condition was executed (not else).

```
		FirebaseAuth auth = FirebaseAuth.getInstance();

		try {
			decodedToken = auth.verifyIdToken(idToken);
			if (decodedToken == null) {
				logger.info("decodedToken is null");
				return null;
			}

			/* Note: 
			Don't use decodedToken to check verified status as it may be stale and return incorrect verified status
			https://github.com/firebase/firebase-admin-java/issues/407
			boolean isVerified = decodedToken.isEmailVerified();

			CAVEAT: 

			There's a big performance penalty in getUser() from the uid.
			It takes about 700ms, whereas verifyIdToken takes just about 5ms.
			
			So, we should call getUser only if decodedToken says user is not verified
			*/

			isVerified = decodedToken.isEmailVerified();
			logger.info("Firebase user isVerified from decodedToken : " + isVerified);
	
			if (! isVerified) {
				uid = decodedToken.getUid();
				logger.info("Firebase user uid : " + uid); // <-- this printed a valid uid
	
				userRecord = auth.getUser(uid);
	
				if (userRecord == null) {
					logger.info("userRecord is null");
					return null;
				}

				emailId = userRecord.getEmail();
				isVerified = userRecord.isEmailVerified();
				logger.info("Firebase user isVerified from userRecord : " + isVerified);
				fullName = userRecord.getDisplayName(); // <--- this printed a valid full name
				provider = userRecord.getProviderId();
				photoUrl = userRecord.getPhotoUrl();
			}
			else {
				emailId = decodedToken.getEmail();
				fullName = decodedToken.getName();
				provider = decodedToken.getIssuer();
				photoUrl = decodedToken.getPicture();
			}

			logger.info("emailId : " + emailId); // <--- emailId is null here

                 } catch (FirebaseAuthException e) {	
			// handle exception
		}
```

**Comment by hiranya911** [comment]
I believe `getEmail()` only returns a value for users that sign in with email+password. This behavior is probably WAI for Facebook users. @bojeil-google can you please confirm?

**Comment by deepfriedbrain** [comment]
@hiranya911 The reason `getEmail()` doesn't work on the Admin Java SDK is because it's null to start with even in the Firebase console (hope you saw the screenshot in my OP).

Otherwise it has been returning the email for all the 3 options that I use - email/password, Google, and Facebook.

I migrated to Firebase from Identity Toolkit couple days ago. And this is the first such case. But I found that even last month (when I was still using Identity Toolkit) there were quite a few Facebook accounts registered with blank email Ids but Identity Toolkit "probably" failed at the token validation step.

I say "probably" because I cannot confirm the behavior now as I have only get 30 days of logs retention with with Google App Engine.

But after migrating to Firebase, it seems to be handling these accounts differently.

Hope @bojeil-google can share more insight on this.

I have also entered a ticket with Firebase support to understand why the accounts are allowed to be registered with blank email address, or at least provide a way to reject them before the registration.

**Comment by bojeil-google** [comment]
Hey @deepfriedbrain please file support tickets using the [official channel](https://firebase.google.com/support). We don't have access to your project information.
There are numerous reason why email may be null. It could be that the user doesn't have an email (Facebook phone user) or chose not to share it.

**Comment by hiranya911** [comment]
Based on the conversation so far it doesn't look like there's a bug in the SDK, so I'm closing this. Please follow up the issue with specific user accounts through the issue already raised with Firebase Support.
