### ISSUE TITLE
3 issues I encountered with Firestore

### ISSUE THREAD

**Issue by Amosss** [firebase/firebase-admin-java#437]
Hi

I'm working with Firestore for a year now and I was very satisfied. Lately I encountered 3 issues that I find disturbing. 2 are relevant here, the 3rd is kinda bonus.

### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Ubuntu 18.04
  * Firebase SDK version: 6.13.0
  * Library version: ?
  * Firebase Product: Firestore

### [REQUIRED] Step 3: Describe the problem
**1. 500 batch items update:** 
If there are more than 500 items, I have to use multiple batch operations. If in the middle of those operations, something bad happens (see point 2), the integrity of the data can be considered as worse.
 
**2. network issue:**
I got the following problem the other day
```
java.util.concurrent.ExecutionException: com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:531)
at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:512)
at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83)
at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:62)
at com.app.API3.addTransaction(API3.java:2685)...

Caused by: io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer
```
The code from my side is
```
future = batch.commit();
future.get();
```
If I got it right, connection reset by peer means the other server (Firebase server?) cut off my request? What can cause such interruption? Can this be intercept and overcome internally? I ask because, as stated in point 1, if this happens in the middle of several batch operations, it's a bad thing.

**3. read count**
Consider this a bonus question: From time to time I notice a surge in the read count of my project with no explanation (1 day: 160K read in 24h, the next day: 68k in 3h, then quiet (much less than 50k) for 2 weeks and so on). I added some traces to my code but even then I left with no explanation. For example, my trace showed 4k read count while Firestore reported 19K. I know I'm not logging ALL reads but still the gap was too much. I already know there is no way to know the collections affected by the read count but I wonder if there's anything to be done from my side or yours to understand whether it is coming from my code or there's a leak somewhere. Generally speaking, I hope the ability to know the collections affected by the read count will be added soon.

#### Steps to reproduce:
There are no specific actions to reproduce the above issues.

#### Relevant Code:
Attached to the relevant point above.

**Comment by schmidt-sebastian** [comment]
Thanks for writing in!

1) Unfortunately, this is a system limitation. Raising the batch limit past 500 is not feasible at this point.

2) We will soon be retrying Commits that fail with UNAVAILABLE.

3) This is a well known feature request. It will likely not get any traction here, since `firebase-admin-java` only wraps the Java SDK that lives at https://github.com/googleapis/java-firestore. 
This, however, is a product-wide issue with all SDKs. Do you mind opening a request at https://b.corp.google.com/savedsearches/5337669?

**Comment by Amosss** [comment]
Thanks for replying.

1. I hope this limitation will be uplifted though if point 2 will be implemented soon (for any problem, not just unavailable), it might make this point less crucial.

2. So it is a network issue from the Firebase server side?

3. I got into the link and saw user/password/security code... am I even eligible to get into there? :)

**Comment by schmidt-sebastian** [comment]
Looks like the public link is https://issuetracker.google.com/savedsearches/5302135

"Unavailable" means that your client could not connect to our backend. The error code alone is unspecific and does not let us pinpoint the root cause. UNAVAILABLE errors are save to retry though.

**Comment by Amosss** [comment]
So to conclude: I opened a feature request.

Unavailable is what I thought it was and later on, you will "fix" it so it will retry itself? I ask mostly because it happened in the middle of several batch updates.

Thanks

**Comment by schmidt-sebastian** [comment]
@Amosss Yes, we will retry UNAVAILABLE on our end.

**Comment by Amosss** [comment]
Hi again,

Just got a new "hit"
java.util.concurrent.ExecutionException: com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:531) at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:512) at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83) at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:62) at com.myapp.API3.api(API3.java:2789)

Caused by: io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: readAddress(..) failed: Connection reset by peer.

I see that 6.14.0 is out but I didn't see any reference to this issue. Any estimation on when a retry will be added? Thanks.

**Comment by hiranya911** [comment]
@Amosss you should follow https://github.com/googleapis/java-firestore for Firestore-related changes.
