### ISSUE TITLE
FR: Support For Remote Config in JAVA admin SDK

### ISSUE THREAD

**Issue by ubarua123** [firebase/firebase-admin-java#446]
I see the Java admin SDK doesn't support Remote Config while the node.js does. Is there any plan to support it in the future? or is it final?

**Comment by lahirumaramba** [comment]
Thank you for reaching out! Great news! We have already started working out the design for the Remote Config API for Admin Java SDK. Things are still pretty early stage, and this issue will track our work once we start implementation.

**Comment by lahirumaramba** [comment]
Remote Config API is now available in Admin Java v.7.1.0. Thank you!
