### ISSUE TITLE
Leverage libraries-bom to ensure compatible transitive dependencies between google-cloud-storage & google-cloud-firestore

### ISSUE THREAD

**Issue by BenWhitehead** [firebase/firebase-admin-java#450]
Given the inherent complexities of dependency management in `com.google.cloud` libraries, `com.google.cloud:libraries-bom` can be used to simplify verification and compatibility.

The release tooling and automation implemented in `com.google.cloud:libaries-bom` ensures all dependencies defined in it are binary compatible across the full dependency graph for all of the included projects (including grpc, guava, google-cloud-* and more. See [The Google Cloud Platform Libraries BOM](https://github.com/GoogleCloudPlatform/cloud-opensource-java/wiki/The-Google-Cloud-Platform-Libraries-BOM) for links to all libraries). 

While updating to use libraries-bom wouldn't fix the issue present in #447 directly, it would provide information to users that the BOM is used for version resolution, and that their projects should do the same when using other GCP libraries in their projects along with `firebase-admin`.

**Comment by hiranya911** [comment]
Thank you @BenWhitehead. 

I've put together #451. I cannot assign it to you, but perhaps you can take a quick look and comment on whether my approach is correct or not?
