### ISSUE TITLE
Check that the token is available

### ISSUE THREAD

**Issue by john-projects** [firebase/firebase-admin-java#454]
It is now possible to use dryrun parameter verification, but it is not very friendly, can you add an API for batch inspection?

**Comment by hiranya911** [comment]
You can dry run  a batch with `sendAll()` or `sendMulticast()`. @chong-shao is there anything else that needs to be done to support this?

**Comment by chong-shao** [comment]
sendAll() or sendMulticast() should work. Nothing else is needed.

You can also try the IID info HTTP API: https://developers.google.com/instance-id/reference/server
