### ISSUE TITLE
Chore:Upgrade to maven wrapper

### ISSUE THREAD

**Issue by shambhand** [firebase/firebase-admin-java#468]
Maven Wrapper is an excellent choice for projects that need a specific version of Maven (or for contributors that don't want to install Maven at all). Its tech improvement so raising it as chore.

**Comment by hiranya911** [comment]
I don't see the immediate need for this. Looking at https://github.com/googleapis/google-cloud-java, they don't seem to be using it either. Developers can use most Maven 3.x distributions to build and test this repo. If that changes, we can reconsider this.
