### ISSUE TITLE
Global VerifyIdToken() fails when token has a tenantId

### ISSUE THREAD

**Issue by michaelgambold** [firebase/firebase-admin-java#474]
* Operating System version: Windows 10 2004
  * Firebase SDK version: 7.0.0
  * Library version: Not sure
  * Firebase Product: Auth (auth, database, storage, etc)

When a tenant Firebase JWT token is verified using the FirebaseAuth.verifyIdToken() this fails. This is in direct conflict to the google documentation for Google Identity Platform docs (https://cloud.google.com/identity-platform/docs/multi-tenancy-managing-tenants#identity_verification).

The exception message thrown is: "com.google.firebase.auth.FirebaseAuthException: The tenant ID ($MY_TENANT_ID) of the token did not match the expected value ('')"

It's worth noting this does not occur using the Node.JS version of the Firebase Admin SDK.

To reproduce Try and verify a Firebase JWT with a tenant with the global FirebaseAuth.verifyIdToken() method.

The issue appears to be that in the FirebaseTokenVerifierImp class it sets the tenant Id in the constructor as an empty string (makes sense there is no tenant here). However in the verifyToken() method this calls the checkTenantId() method. This compares the empty tenant Id to the tenant id in the token which throws the exception.

It probably makes sense for the TenantAwareFirebaseAuth class to check this in the verify token but not in the base class (i.e. the same as the Node version). Otherwise you will need to:
* decode the token first to get the tenant Id
* create a TenantAwareFirebaseAuth instance
* verify the token.

**Comment by michaelgambold** [comment]
If removing the tenant check is an acceptable solution for the main FirebaseAuth I can create a pull request.

**Comment by hiranya911** [comment]
Thanks for the bug report @michaelgambold. Fix in progress.
