### ISSUE TITLE
Firebase admin SDK: getUserByEmail fails for facebook

### ISSUE THREAD

**Issue by chaitanya4288** [firebase/firebase-admin-java#482]
* Operating System version: MacOS Catalina 10.15.6
  * Firebase SDK version: 7.14.3
  * Library version: 6.12.2
  * Firebase Product: auth

I have enabled facebook, google and email/password options in my firebase console.
(1): If a facebook user logs-in and chooses to disclose his email, after successful login the firebase console shows his record for the email. Also, through Admin SDK I am able to get the User record using the getUserByEmail method.

![image](https://user-images.githubusercontent.com/2232566/95081320-01386180-0737-11eb-92e5-6ce695ee170d.png)

So far this is fine. (2) But when the user does not disclose his email, the firebase does not have his email info (which is expected).

![image](https://user-images.githubusercontent.com/2232566/95081363-13b29b00-0737-11eb-9f9f-fc3eb176ea1a.png)

![image](https://user-images.githubusercontent.com/2232566/95081406-21682080-0737-11eb-9dd5-df662703032f.png)

The problem appears if the user deletes the app from facebook (settings > apps & websites) and retries the register action or login.

![image](https://user-images.githubusercontent.com/2232566/95081461-32b12d00-0737-11eb-8f2c-c32eee2c95f4.png)

After deleting the app from settings in facebook, user will again have the choice to disclose his email or not. If he chooses to disclose his email. the same record which was created during (2) seems to get updated with his email. Firebase console shows the record if I query for this email.

But through admin SDK, getUserByEmail does not return any User record corresponding to this email. Is this a bug in firebase admin SDK or am I missing something?

**Comment by bojeil-google** [comment]
I think this is due to the Admin SDK and the Console using different APIs to query the email.

I believe the Admin SDK API queries the top level email `user.email`, whereas the Console uses a different API to look by email at the top level `user.email` and at the provider level `user.providerData[0].email`.

In the second case above, when the user creates the account and chooses not to disclose the email, the top level email and provider level email are left blank but when the user signs in again and discloses the email, only the provider level email is updated. This explains why the user can be queried in the Console but not by `getUserByEmail`.

**Comment by chaitanya4288** [comment]
Hi team,

Does this mean, there will be a fix soon? if yes can you let me know any tentative date for the fix as I need to communicate to our customers.

**Comment by bojeil-google** [comment]
This works as intended. `getUserByEmail` only looks up by top level email.

**Comment by chaitanya4288** [comment]
So is there a different api to get what console is able to return?
In other words how do I get the user record with email using the admin sdk?

**Comment by chaitanya4288** [comment]
If the user doesn't disclose his email, and later wants to correct it, then in this case, we won't be able to query his record by email. So is there no way in this case?

**Comment by bojeil-google** [comment]
There is a client SDK to `updateEmail` which sets the top level email on a user. So you can always use that API. This would make the account searchable. If you need to expose an API to look for user email in providers too, please file an official [feature request](https://firebase.google.com/support).
