### ISSUE TITLE
FR: header.typ should be set : FirebaseAuth.getInstance().createCustomToken

### ISSUE THREAD

**Issue by emmanuelomotosho** [firebase/firebase-admin-java#494]
firebase-admin maven version: 7.0.1

When creating custom token with FirebaseAuth.getInstance().createCustomToken(..), the resulting token is missing header.typ field.

FirebaseTokenFactory.createSignedCustomAuthTokenForUser seems to only set the alg field, [see this](https://github.com/firebase/firebase-admin-java/blob/master/src/main/java/com/google/firebase/auth/internal/FirebaseTokenFactory.java#L71).

If you try to set the typ field yourself, the factory restricts you, [see this](https://github.com/firebase/firebase-admin-java/blob/master/src/main/java/com/google/firebase/auth/internal/FirebaseTokenFactory.java#L91)

**Comment by hiranya911** [comment]
Why do you want this header set? The Firebase Auth service doesn't require it.

**Comment by emmanuelomotosho** [comment]
hi, thanks for the response @hiranya911 . 

yes firebase auth service doesn't require it, but other downstream apps that integrates with an app that uses firebase based apps may require it.  Which is what happened in my case. e.g. i sent firebase jwt token to an external jwt awared app.  So since its a standard field per spec (see [this](https://tools.ietf.org/html/rfc7519#page-11)), i figured i ask if the team can please include it.  What do you think?

Also, since firebase auth service doesnt require it like you've pointed out, it probably shouldn't be restricted by [this](https://github.com/firebase/firebase-admin-java/blob/master/src/main/java/com/google/firebase/auth/internal/FirebaseTokenFactory.java#L91) when one is trying to create a custom token.  what do you think?

**Comment by hiranya911** [comment]
@bojeil-google wdyt?

I don't mind setting the `typ` header. But sending Firebase custom tokens to other external services sounds iffy. Custom tokens can be exchanged for ID tokens, which allows those services to impersonate users. That can have serious security implications. I'd recommend minting your own JWTs (with your own `iss` and `aud` claims) for such third-party integrations. 

> Also, since firebase auth service doesnt require it like you've pointed out, it probably shouldn't be restricted by this when one is trying to create a custom token. what do you think?

`typ` should be set on the header portion of the JWT. Setting it as a claim on the payload won't really help with your use case, even if the token factory allowed it.

**Comment by emmanuelomotosho** [comment]
> typ should be set on the header portion of the JWT. Setting it as a claim on the payload won't really help with your use case, even if the token factory allowed it.
actually, i just noticed that.  You guys are restricting it on the payload; that is interesting as well.

thanks for considering tho.

**Comment by bojeil-google** [comment]
I think we can set the `typ` header field to `JWT`. However, I do not recommend that the tokens be passed to other services. The tokens would allow full access to user accounts.

**Comment by emmanuelomotosho** [comment]
I think it depends on the tokens are being used with other services and how trusted they are.  But, again, thanks 4 considering.

**Comment by hiranya911** [comment]
I'm going to close this now as won't fix. Adding the `typ` header is not required by Firebase Auth services, and this API works as is without it.
