### ISSUE TITLE
Sign in link is not generated properly for iOS: no app store redirect when app missing

### ISSUE THREAD

**Issue by theHilikus** [firebase/firebase-admin-java#495]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Linux
  * Firebase SDK version: 
  * Library version: 6.15.0, 7.0.1
  * Firebase Product: auth

### [REQUIRED] Step 3: Describe the problem
When generating a sign in email link, the generated link doesn't redirect to the app store when the ios app is not installed

#### Steps to reproduce:

- Generate a a sign in link
- Open it in an ios device that doesn't have the app installed
- The final result is you get redirected to Url instead of to the app store like it does for android

#### Relevant Code:

```
auth.generateSignInWithEmailLink(destination.getEmail(), generateActionSettings());
...
private ActionCodeSettings generateActionSettings() {
        return ActionCodeSettings.builder()
                .setAndroidInstallApp(true)
                .setHandleCodeInApp(true)
                .setUrl("https://example.com")
                .setDynamicLinkDomain(dynamicLinkDomain)
                .setAndroidPackageName(androidPackageName)
                .setIosBundleId(iOsBundleId)
                .build();
    }

```
The link generated is of the form (modified for security reasons)
https://foo.page.link?link=https://foo.firebaseapp.com/__/auth/action?apiKey%3DA-JgRIp53l0Rp0TNAXFYRllDHwpnKfE%26mode%3DsignIn%26oobCode%3DMlz_ZLn5kCG9q2hP2UPyjW0oGeTZoG4KRrsjQ4AAAF153fxhA%26continueUrl%3Dhttps://example.com%26lang%3Den&apn=com.my.android.id&amv&ibi=com.my.ios.id&ifl=https://foo.firebaseapp.com/__/auth/action?apiKey%3DA-JgRIp53l0Rp0TNAXFYRllDHwpnKfE%26mode%3DsignIn%26oobCode%3DMlz_ZLn5kCG9q2hP2UPyjW0oGeTZoG4KRrsjQ4AAAF153fxhA%26continueUrl%3Dhttps://example.com%26lang%3Den

If I debug the link i get this
![image](https://user-images.githubusercontent.com/1633408/99850880-2ac51500-2b4c-11eb-966c-a4e6f7870fb7.png)

You can see that the android path leads to the play store when the app is not installed, but the ios path leads to a weblink, not to the app store. 

From my tests, it seems that for the link to redirect to the app store it needs to have the query parameter `isi`, which the [documentation](https://firebase.google.com/docs/dynamic-links/create-manually) states
> isi | Your app's App Store ID, used to send users to the App Store when the app isn't installed

**Comment by bojeil-google** [comment]
We don't support install app flow for iOS for security reasons. There are risks that the link could be intercepted by an intended app. As this is Auth related, we are not comfortable with that risk.

**Comment by theHilikus** [comment]
oh really? that's a pity. This should be mentioned somewhere in the documentation. Maybe i missed it but i've read the documentation multiple times and wasn't aware of it

Thanks anyway for the clarification. This explains the behaviour
