### ISSUE TITLE
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState

### ISSUE THREAD

**Issue by pskd73** [firebase/firebase-admin-java#50]
Here is my code
```
FileInputStream serviceAccount = new FileInputStream("firebase.json");
		FirebaseOptions options = new FirebaseOptions.Builder()
			.setCredential(FirebaseCredentials.fromCertificate(serviceAccount))
			.setDatabaseUrl("https://xxxxx.firebaseio.com/")
			.build();
		FirebaseApp.initializeApp(options);
		FirebaseAuth.getInstance();
```
`FirebaseAuth.getInstance();` causing the issue. The error log stack is here
```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V
	at com.google.firebase.FirebaseApp.checkNotDeleted(FirebaseApp.java:314)
	at com.google.firebase.FirebaseApp.getOptions(FirebaseApp.java:260)
	at com.google.firebase.auth.FirebaseAuth.<init>(FirebaseAuth.java:74)
	at com.google.firebase.auth.FirebaseAuth.<init>(FirebaseAuth.java:61)
	at com.google.firebase.auth.FirebaseAuth.<init>(FirebaseAuth.java:52)
	at com.google.firebase.auth.FirebaseAuth$FirebaseAuthService.<init>(FirebaseAuth.java:316)
	at com.google.firebase.auth.FirebaseAuth.getInstance(FirebaseAuth.java:98)
	at com.google.firebase.auth.FirebaseAuth.getInstance(FirebaseAuth.java:85)
	at com.datasignstech.lam.core.google.GoogleInterface.main(GoogleInterface.java:119)
```

I am not sure why I am getting the above error. I see the code and at FirebaseApp.java:314 it is passing 3 arguments, but in error it is showing only two arguments, which is not there in Preconditions. Kindly help me in this.

I am using firebase-admin sdk: 5.2.0
Jdk: 1.8.0
OS: Ubuntu 16.04

**Comment by swftvsn** [comment]
Hi,

this is most likely wrong version of Guava. Check mvn dependency:tree or gradlew dependencies to find out what version you have.

iirc the version 20 and up of guava has that. However, many libraries depend on older version if you use google cloud stuff.

**Comment by hiranya911** [comment]
Yes, this happens when two version of Guava ends up in the classpath. Check the dependency tree and add an exclusion rule to the older version.

**Comment by pskd73** [comment]
Thanks @hiranya911 Now the above issue got fixed. But I am facing another issue now. 
```
java.lang.NoSuchMethodError: com.google.firebase.auth.internal.FirebaseTokenVerifier.getIssuers()Ljava/util/Collection;
	at com.google.firebase.auth.internal.FirebaseTokenVerifier.verifyTokenAndSignature(FirebaseTokenVerifier.java:120)
	at com.google.firebase.auth.FirebaseAuth$2.then(FirebaseAuth.java:199)
	at com.google.firebase.auth.FirebaseAuth$2.then(FirebaseAuth.java:187)
	at com.google.firebase.tasks.ContinueWithCompletionListener$1.run(ContinueWithCompletionListener.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```
I am getting this error when I cann verifyIdToken() method. Can you/anybody help me in this?

**Comment by pskd73** [comment]
It was issue with google oauth library. I managed to fix it by removing old version of the google oauth library.

**Comment by hth** [comment]
Code below should fix this issue. 

    compile ('com.google.firebase:firebase-admin:5.2.0') {
       exclude group: 'com.google.guava'
    }
    compile 'com.google.guava:guava:23.0'

**Comment by cohenadair** [comment]
@hth Thank you, but in my case I used to use Guava 20.0 as 23.0 requires Java 8 and I'm still on Java 7. Note that I used 20.0, but there may be newer versions that do not require Java 8.

**Comment by galcyurio** [comment]
maven solution example
````xml
<dependency>
    <groupId>com.google.firebase</groupId>
    <artifactId>firebase-admin</artifactId>
    <version>${firebase.version}</version>
    <exclusions>
        <exclusion>
            <groupId>com.google.guava</groupId>
            <artifactId>guava</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>com.google.guava</groupId>
    <artifactId>guava</artifactId>
    <version>${guava.version}</version>
</dependency>
````

**Comment by mituldreamworld** [comment]
@hth Thanks for the solution.

**Comment by ZeyadAlma** [comment]
I'm having the same problem but the solution does not work for me
Java 8 Standard App Engine - Firebase Admin
Exception:
 
    java.lang.NoSuchMethodError: 
        com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;)V`
        at com.google.firebase.FirebaseApp.checkNotDeleted (FirebaseApp.java:352)
        at com.google.firebase.FirebaseApp.getOptions (FirebaseApp.java:267)
        at com.google.firebase.FirebaseApp$TokenRefresher.<init> (FirebaseApp.java:434)
        at com.google.firebase.FirebaseApp$TokenRefresher$Factory.create (FirebaseApp.java:535)
        at com.google.firebase.FirebaseApp.<init> (FirebaseApp.java:113)
        at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:201)
        at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:188)
        at com.google.firebase.FirebaseApp.initializeApp (FirebaseApp.java:175)

Code:

        InputStream in = getServletConfig()..getResourceAsStream("/WEB-INF/PRIVATE_KEY_JSON.json");

        FirebaseOptions options = null;
        try {
            options = new FirebaseOptions.Builder()
                    .setCredentials(GoogleCredentials.fromStream(in))
                    .setDatabaseUrl("MyDBURL")
                    .build();
        } catch (IOException e) {
            e.printStackTrace();
        }
        FirebaseApp app = FirebaseApp.initializeApp(options);


Dependency:

      appengineSdk 'com.google.appengine:appengine-java-sdk:1.9.60'
      compile 'com.google.appengine.tools:appengine-gcs-client:
      compile ('com.google.firebase:firebase-admin:5.4.0'){
         exclude group: 'com.google.guava'
      }
      compile 'com.google.guava:guava:23.0'
      compile 'javax.servlet:servlet-api:2.5'
      compile 'com.google.code.gson:gson:2.8.2'
      compile 'com.googlecode.json-simple:json-simple:1.1.1'
      compile group: "com.twilio.sdk", name: "twilio", version: "7.11.+"
      compile 'com.sendgrid:sendgrid-java:4.1.1'

**Comment by 779503982** [comment]
The solution didn't work for me either.

**Comment by zloyreznic** [comment]
try 
```
<exclusions>
				<exclusion>
					<groupId>com.google.guava</groupId>
					<artifactId>guava</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.google.guava</groupId>
					<artifactId>guava-jdk5</artifactId>
				</exclusion>
			</exclusions>
```

**Comment by 779503982** [comment]
@zloyreznic Thank you very much for your reply. I appreciate it. After I added the routines galcyurio provided, I noticed there were still two versions of guava existed in the maven dependencies in Eclipse. So I right clicked the guava with lower version in "Maven Dependencies", and select "Maven" -- "Exclude Maven Artifact", and this issue was thus figured out. Still, thank you very much!

**Comment by ZeyadAlma** [comment]
@zloyreznic  Thank you for replying, I excluded both Guava and Guava-jdk5. Still not working

**Comment by hiranya911** [comment]
While there's no guaranteed way to "fix" this, I think there may be a way to drastically reduce the chance of developers running into this. I will send a experimental PR shortly.

**Comment by hiranya911** [comment]
I've attached a new `firebase-admin` binary with a potential fix at #125. Please check if that helps with this problem.

**Comment by 779503982** [comment]
@hiranya911 Thank you! I think it worked for me. I just deleted all the exclusions and also the dependency on guava of newest version, that error didn't show up again. I can see two guava versions in Maven Dependencies in Eclipse, but without "no such method error". 

Could you please help with another google project, this project won't work on google cloud: https://github.com/GoogleCloudPlatform/firebase-appengine-backend
Please see issue: project uses deprecated Managed VMs beta environment.
Well, it does work on local gcloud server, but the example is to deploy the project on google cloud. Thank you very much!

**Comment by hiranya911** [comment]
@779503982 thanks for the feedback.

The issue with the other project is not really related to Admin SDK in anyway, but it seems it was fixed a few weeks ago: https://github.com/GoogleCloudPlatform/firebase-appengine-backend/pull/8

You should follow up there.

**Comment by hiranya911** [comment]
Fixed in #125.

**Comment by thirupks** [comment]
> Thanks @hiranya911 Now the above issue got fixed. But I am facing another issue now.
> 
> ```
> java.lang.NoSuchMethodError: com.google.firebase.auth.internal.FirebaseTokenVerifier.getIssuers()Ljava/util/Collection;
> 	at com.google.firebase.auth.internal.FirebaseTokenVerifier.verifyTokenAndSignature(FirebaseTokenVerifier.java:120)
> 	at com.google.firebase.auth.FirebaseAuth$2.then(FirebaseAuth.java:199)
> 	at com.google.firebase.auth.FirebaseAuth$2.then(FirebaseAuth.java:187)
> 	at com.google.firebase.tasks.ContinueWithCompletionListener$1.run(ContinueWithCompletionListener.java:49)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
> 	at java.lang.Thread.run(Thread.java:748)
> ```
> I am getting this error when I cann verifyIdToken() method. Can you/anybody help me in this?

<dependency>
            <groupId>com.google.cloud</groupId>
            <artifactId>google-cloud-datastore</artifactId>
            <version>1.62.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.oauth-client</groupId>
                    <artifactId>google-oauth-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        
        <dependency>
            <groupId>com.google.oauth-client</groupId>
            <artifactId>google-oauth-client</artifactId>
            <version>1.28.0</version>
        </dependency>

**Comment by raghav382** [comment]
Hello all,
I am raghavendra, new user to the maven.
Here are my POI content and trying to on chorme version 76.0. It would be nice to guide me with very granular level.

Code getting executed:

	@BeforeClass
	public void openbrowser1()
	{
		System.out.println("Hello Relax");
		System.setProperty("webdriver.chrome.driver","D:\\JavaAutomation\\Files\\chromedriver.exe");
		driver=new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("http://www.google.com");
		  driver.manage().timeouts().implicitlyWait(5000, TimeUnit.MILLISECONDS);

Error getting :
Tests run: 3, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 0.706 sec <<< FAILURE! - in TestSuite
openbrowser1(com.org.metric1.Shangrila.HelloMavenTest)  Time elapsed: 0.597 sec  <<< FAILURE!
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V
	at com.org.metric1.Shangrila.HelloMavenTest.openbrowser1(HelloMavenTest.java:36)


Results :

Failed tests: 
  HelloMavenTest.openbrowser1:36 » NoSuchMethod com.google.common.base.Precondit...

Tests run: 3, Failures: 1, Errors: 0, Skipped: 2

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.org.metric1</groupId>
  <artifactId>Shangrila</artifactId>
  <version>1-SNAPSHOT</version>
  <packaging>jar</packaging>
  <name>Shangrila</name>
  <url>http://maven.apache.org</url>
  <properties>
     <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
     <jre.level>1.8</jre.level>
	 <jdk.level>1.8</jdk.level>
     <suiteXmlFile>testing1.xml</suiteXmlFile>
  </properties>
  <dependencies>
     <dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>3.141.59</version>
     </dependency>
     <dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-api</artifactId>
    <version>3.141.59</version>
</dependency>
    <dependency>
        <groupId>org.seleniumhq.selenium</groupId>
        <artifactId>selenium-server</artifactId>
        <version>3.0.1</version>
    </dependency> 
  <dependency>
    <groupId>org.apache.poi</groupId>
    <artifactId>poi</artifactId>
    <version>4.1.0</version>
  </dependency> 
<dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>6.9.8</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.8.1</version>
</dependency>
<dependency>
    <groupId>org.apache.poi</groupId>
    <artifactId>poi-ooxml</artifactId>
    <version>4.1.0</version>
 </dependency>
 <dependency>
    <groupId>org.apache.poi</groupId>
    <artifactId>poi-ooxml-schemas</artifactId>
    <version>4.1.0</version>
</dependency>
     <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>Test</scope>
    </dependency>
      <dependency>
            <groupId>com.google.collections</groupId>
            <artifactId>google-collections</artifactId>
            <version>1.0</version>
     </dependency>

<dependency>
    <artifactId>guava</artifactId>
    <groupId>com.google.guava</groupId>
    <type>jar</type>
    <version>20.0</version>
</dependency>
        
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-chrome-driver</artifactId>
            <version>${selenium-chrome-driver}</version>
        </dependency>
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-chrome-driver</artifactId>
    <version>3.141.59</version>
</dependency>
   </dependencies>  
    <build>
<plugins>
        <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.19.1</version>
        <configuration>
          <suiteXmlFiles>
            <suiteXmlFile>${suiteXmlFile}</suiteXmlFile>
          </suiteXmlFiles>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.owasp</groupId>
        <artifactId>dependency-check-maven</artifactId>
        <version>5.2.1</version>
      </plugin>
</plugins>
</build>
   </project>

**Comment by raghav382** [comment]
Hello all,
I am raghavendra, new user to the maven.
Here are my POI content and trying to on chorme version 76.0. It would be nice to guide me with very granular level.

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.org.metric1</groupId>
  <artifactId>Shangrila</artifactId>
  <version>1-SNAPSHOT</version>
  <packaging>jar</packaging>
  <name>Shangrila</name>
  <url>http://maven.apache.org</url>
  <properties>
     <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
     <jre.level>1.8</jre.level>
	 <jdk.level>1.8</jdk.level>
     <suiteXmlFile>testing1.xml</suiteXmlFile>
  </properties>
  <dependencies>
     <dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-java</artifactId>
    <version>3.141.59</version>
     </dependency>
     <dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-api</artifactId>
    <version>3.141.59</version>
</dependency>
    <dependency>
        <groupId>org.seleniumhq.selenium</groupId>
        <artifactId>selenium-server</artifactId>
        <version>3.0.1</version>
    </dependency> 
  <dependency>
    <groupId>org.apache.poi</groupId>
    <artifactId>poi</artifactId>
    <version>4.1.0</version>
  </dependency> 
<dependency>
    <groupId>org.testng</groupId>
    <artifactId>testng</artifactId>
    <version>6.9.8</version>
    <scope>test</scope>
</dependency>
<dependency>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>3.8.1</version>
</dependency>
<dependency>
    <groupId>org.apache.poi</groupId>
    <artifactId>poi-ooxml</artifactId>
    <version>4.1.0</version>
 </dependency>
 <dependency>
    <groupId>org.apache.poi</groupId>
    <artifactId>poi-ooxml-schemas</artifactId>
    <version>4.1.0</version>
</dependency>
     <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>3.8.1</version>
      <scope>Test</scope>
    </dependency>
      <dependency>
            <groupId>com.google.collections</groupId>
            <artifactId>google-collections</artifactId>
            <version>1.0</version>
     </dependency>

<dependency>
    <artifactId>guava</artifactId>
    <groupId>com.google.guava</groupId>
    <type>jar</type>
    <version>20.0</version>
</dependency>
        
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-chrome-driver</artifactId>
            <version>${selenium-chrome-driver}</version>
        </dependency>
<dependency>
    <groupId>org.seleniumhq.selenium</groupId>
    <artifactId>selenium-chrome-driver</artifactId>
    <version>3.141.59</version>
</dependency>
   </dependencies>  
    <build>
<plugins>
        <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.19.1</version>
        <configuration>
          <suiteXmlFiles>
            <suiteXmlFile>${suiteXmlFile}</suiteXmlFile>
          </suiteXmlFiles>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.owasp</groupId>
        <artifactId>dependency-check-maven</artifactId>
        <version>5.2.1</version>
      </plugin>
</plugins>
</build>
   </project>


Code getting executed:

@BeforeClass
public void openbrowser1()
{
	System.out.println("Hello Relax");
	System.setProperty("webdriver.chrome.driver","D:\\JavaAutomation\\Files\\chromedriver.exe");
	driver=new ChromeDriver();
	driver.manage().window().maximize();
	driver.get("http://www.google.com");
	  driver.manage().timeouts().implicitlyWait(5000, TimeUnit.MILLISECONDS);
Error getting :
Tests run: 3, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 0.706 sec <<< FAILURE! - in TestSuite
openbrowser1(com.org.metric1.Shangrila.HelloMavenTest) Time elapsed: 0.597 sec <<< FAILURE!
java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkState(ZLjava/lang/String;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)V
at com.org.metric1.Shangrila.HelloMavenTest.openbrowser1(HelloMavenTest.java:36)

Results :

Failed tests:
HelloMavenTest.openbrowser1:36 » NoSuchMethod com.google.common.base.Precondit...

Tests run: 3, Failures: 1, Errors: 0, Skipped: 2

4.0.0 com.org.metric1 Shangrila 1-SNAPSHOT jar Shangrila http://maven.apache.org UTF-8 1.8 1.8 testing1.xml org.seleniumhq.selenium selenium-java 3.141.59 org.seleniumhq.selenium selenium-api 3.141.59 org.seleniumhq.selenium selenium-server 3.0.1 org.apache.poi poi 4.1.0 org.testng testng 6.9.8 test org.apache.maven.plugins maven-compiler-plugin 3.8.1 org.apache.poi poi-ooxml 4.1.0 org.apache.poi poi-ooxml-schemas 4.1.0 junit junit 3.8.1 Test com.google.collections google-collections 1.0 guava com.google.guava jar 20.0 org.seleniumhq.selenium selenium-chrome-driver ${selenium-chrome-driver} org.seleniumhq.selenium selenium-chrome-driver 3.141.59 org.apache.maven.plugins maven-surefire-plugin 2.19.1 ${suiteXmlFile} org.owasp dependency-check-maven 5.2.1
