### ISSUE TITLE
UNAVAILABLE

### ISSUE THREAD

**Issue by Amosss** [firebase/firebase-admin-java#511]
* Operating System version: ubuntu 18.04
  * Firebase SDK version: firebase-admin 7.0.1
  * Firebase Product: FireStore

I had this issue a long time ago and I was told it's an internal issue that should be fixed. It was fixed as I didn't see it for a long time but I got it twice already in the last week.

> java.util.concurrent.ExecutionException: com.google.api.gax.rpc.UnavailableException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:564)	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:545)	at com.google.common.util.concurrent.FluentFuture$TrustedFuture.get(FluentFuture.java:86)	at com.google.common.util.concurrent.ForwardingFuture.get(ForwardingFuture.java:62)	at com.app.API3.addTransaction(API3.java:3474)

#### Relevant Code:
It happens with the following code
```
future = batch.commit();
future.get();    <<<<< failing code
```

Thanks

**Comment by schmidt-sebastian** [comment]
@Amosss We currently retry Commits that fail with UNAVAILBLE (https://github.com/googleapis/nodejs-firestore/blob/master/dev/src/v1/firestore_client_config.json#L67). 

These retries are scheduled with backoff, but if the retries don't succeed after 10 minutes, the operation is cancelled and the Promise that is returned is rejected. Do you notice these 10 minute timeouts in your setup? If not, there might be an issue with our backoff logic that we should look at.

**Comment by Amosss** [comment]
Thank you for your reply. 

From what I gathered, a user tried to do a certain action and the response was this exception. Obviously it doesn't happen most of the time, it's just it did happen twice last week so I thought to bring it up here.

Bottom line, I don't know if the 10 minutes timeouts occurred or not.

**Comment by schmidt-sebastian** [comment]
Thanks for the update. Unfortunately, there won't be much we can do right now. If this issue gets reported again, it would help if you could give us information regarding the timeout (and debug logs if available).
