### ISSUE TITLE
Firebase messaging content available

### ISSUE THREAD

**Issue by ArkaitzSKR** [firebase/firebase-admin-java#513]
We do not get the notifications to IOS but to android yes. The only parameter that makes that happen is the content available that appears in the library as **content-available** and that we believe should be **content_available**.
In the postman tests against FCM, the parameter must be sent as **content_available** and the result is that it works perfectly. On the other hand, it is not like that with the library.
If you can take a look, we would appreciate it.
Sorry for the inconvenience.

**Comment by hiranya911** [comment]
`content-available` is consistent with APNs documentation: https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/RemoteNotificationsPG/CreatingtheNotificationPayload.html

@chong-shao wdyt?

**Comment by chong-shao** [comment]
`content_available` is used instead of `content-available` for both legacy and v1 API. As a field in APNs, it's not documented in FCM API references, but it was mentioned in the legacy API reference https://firebase.google.com/docs/cloud-messaging/http-server-ref as "`content_available`". 

I think choosing either one of the two has pros/cons. `content_available` with the `_` is consistent with the style of other fields in the FCM API. Perhaps we can introduce a feature in the SDK to accept both?

**Comment by hiranya911** [comment]
@chong-shao I think the original question is about the APNs content-available field (sent as part of the `aps` dictionary). I don't think we support any other `content-available` field anywhere in this library.

**Comment by hiranya911** [comment]
@ArkaitzSKR can you provide clear details on what you tried (sample code, message payloads etc), and what's not working?

**Comment by ArkaitzSKR** [comment]
sorry! our server provider updated the library and is using the API V1. It is true that content_available was written in the old api and it still works fine. But in v1 it works as content-available.
Sorry for the inconvenience!

**Comment by leeapted** [comment]
We have been using content_available with the old API. When moving to V1 we're getting a 400 bad request error with "content_available" and "content-available" (many formats including as part of the aps dictionary). @ArkaitzSKR, could you share your working JSON? Thanks.

**Comment by joonb14** [comment]
@leeapted how about this? https://firebase.google.com/docs/reference/admin/node/firebase-admin.messaging.aps
It seems like [contentAvailable](https://firebase.google.com/docs/reference/admin/node/firebase-admin.messaging.aps.md#apscontentavailable) might work for you.
