### ISSUE TITLE
FR: Support query operations that other Firebase libraries support

### ISSUE THREAD

**Issue by ScottPierce** [firebase/firebase-admin-java#519]
### [REQUIRED] Step 2: Describe your environment

  * Library version: 7.1.1
  * Firebase Product: firestore

### [REQUIRED] Step 3: Describe the problem
I don't seem too have access to all of the same firestore query syntax  as I have in other languages. i.e. I can't do a not equals query, but firestore definitely supports this.

**Comment by hiranya911** [comment]
It is supported in https://github.com/googleapis/java-firestore which means we do too. You might have to upgrade the google-cloud-firestore dependency installed into your project/app.
