### ISSUE TITLE
Missing dependency upon installing from Maven

### ISSUE THREAD

**Issue by nixin72** [firebase/firebase-admin-java#525]
### [REQUIRED] Step 2: Describe your environment

  * Operating System version: Arch Linux, Kernel 5.10-LTS
  * Firebase SDK version: 7.1.1
  * Library version: *
  * Firebase Product: FCM

### [REQUIRED] Step 3: Describe the problem
Trying to use the Firebase Admin SDK for sending push notifications from my server, however I'm getting dependency issues upon installing the library from Maven.

#### Steps to reproduce:
Using Leiningen for Clojure, I added the following to my `project.clj`
```
[com.google.firebase/firebase-admin "7.1.1"]
```

#### Relevant Code:
```
[com.google.firebase/firebase-admin "7.1.1"]
```

![image](https://user-images.githubusercontent.com/22285063/114230399-193ba880-9947-11eb-9d03-0ab53ce7e2c8.png)

I tried installing the missing dependency from here: https://mvnrepository.com/artifact/com.google.common/google-collect/1.0

But I get the same issue - it can't find this class.

**Comment by hiranya911** [comment]
Streams (which comes from guava jre dependencies) is not one of our dependencies. It seems your specific runtime framework requires it. So you will have to specify a direct dependent on it. See the instructions at https://github.com/GoogleCloudPlatform/cloud-opensource-java/wiki/The-Google-Cloud-Platform-Libraries-BOM#guava-versions--jre-or--android

> If your project requires Java 8 or later and uses Guava classes such as com.google.common.collect.Streams, you should add a dependency on a JRE version of Guava.
