### ISSUE TITLE
Unboxing may produce NPE

### ISSUE THREAD

**Issue by Amosss** [firebase/firebase-admin-java#526]
I have the following code `sd.setMethod(doc.getDouble("field1"));` where I get the mentioned warning (intellij)
Adding doc.contains("field1") before that, doesn't remove it, obviously.

To remove it, I need to do the following: `Objects.requireNonNull(doc.getDouble("field1"))` and doing so for many lines of code is not clean/readable.

I understand why the warning is there but I was wondering if there is a cleaner way to remove those warnings.

firestore, 7.1.1

**Comment by hiranya911** [comment]
You should probably enforce that field1 is not null at your design/schema level. If you do that you can just ignore the warnings by using a suitable annotation. If you cannot make that guarantee at the design level, you have to do a null check:

```
Double field1 = doc.getDouble("field1");
if (field1 != null) {

}
```

**Comment by Amosss** [comment]
I know it's not null but intellij doesn't know that :)
I was hoping for a cleaner way than adding annotations or null check every time I call document.getSomething() - there are many places like this.

Thanks

**Comment by hiranya911** [comment]
If you're certain that it's not null you can tell Intellij to suppress the warning. This can be configured at class, method or statement level: https://www.jetbrains.com/help/idea/disabling-and-enabling-inspections.html#suppress-inspections

Or write your own util to wrap the API call:
```java
public double getDouble(DocumentReference doc, String field) {
  Double val = doc.getDouble(field);
  if (val != null) {
    return val;
  }

  throw new IllegalStateException();
}
```

Then you can use the above method instead of directly calling `doc.getDouble()`.

**Comment by Amosss** [comment]
I prefer not to use suppress inspections so thanks a lot for the function tip!
