### ISSUE TITLE
Cannot create custom token using IAM because Service Account Credentials has priority for signing.

### ISSUE THREAD

**Issue by ddadon10** [firebase/firebase-admin-java#531]
I would like to create a custom token and sign it using a different GCP Project from the one I am actually running on.

But by using the library I cannot sign it using IAM because Service Account Credentials has priority for signing.

I am using the following method[1]:

`AbstractFirebaseAuth.createCustomToken(@NonNull String uid, @Nullable Map<String, Object> developerClaims)` 

In order to instantiate the `FirebaseAuth` object, we have to call the follow factory method[2]

`FirebaseAuth getInstance(FirebaseApp app)`

The argument `FirebaseApp` is then used internally by the `FirebaseTokenUtils` to create a `FirebaseTokenFactory` that will be use to create a custom token[3], and therefore by the `CryptoSigner` to determine which signing strategy to use.

If I got it correctly, the signing strategy is the following:

1. The private key of FirebaseApp's service account credentials
2. The IAM service if a service account email was specified
3. The App Identity service if the code is deployed in a GAE standard environment
4. The local Metadata server

My issue is that `FirebaseApp` has to be configured with `FirebaseOptions`, and it is not possible to configure `FirebaseOptions` without setting the credential supplier[5], so it is not possible to use the IAM service to sign the token because always the service account credential will be used

Is this an expected behavior?

Thank you,

Environment:
  * Operating System version: *
  * Firebase SDK version: *
  * Library version: v7.1.1
  * Firebase Product: auth

[1] https://github.com/firebase/firebase-admin-java/blob/589f08b68d8fafc63c5a9fc5d0351d805d952d8d/src/main/java/com/google/firebase/auth/AbstractFirebaseAuth.java#L127

[2] https://github.com/firebase/firebase-admin-java/blob/0b356e1fdf6da40f01315f54dad0322a0d732803/src/main/java/com/google/firebase/auth/FirebaseAuth.java#L63

[3] https://github.com/firebase/firebase-admin-java/blob/cc520a721ef3ced13c6c1e34fa010d082a948b99/src/main/java/com/google/firebase/auth/FirebaseTokenUtils.java#L59

[4] https://github.com/firebase/firebase-admin-java/blob/1e26ef3b7ed1d0593591fa1da454a84cd89c72ac/src/main/java/com/google/firebase/auth/internal/CryptoSigners.java#L148

[5] https://github.com/firebase/firebase-admin-java/blob/cc520a721ef3ced13c6c1e34fa010d082a948b99/src/main/java/com/google/firebase/FirebaseOptions.java#L89

**Comment by hiranya911** [comment]
This is WAI. We typically use IAM only in environments where service account credentials are not provided (e.g. application default credentials). 

If you want to override that behavior, you can just wrap the service account credential in your own implementation of `GoogleCredentials`. Here's an example from our own integration tests:

https://github.com/firebase/firebase-admin-java/blob/3e5c57d92d658c850f0d2506e22bc4b109ba27f9/src/test/java/com/google/firebase/auth/FirebaseAuthIT.java#L577-L600

For your use case you can do something like this:
```
class MyCredentials extends GoogleCredentials {

    private final GoogleCredentials delegate;

    public MyCredentials(GoogleCredentials delegate) {
      this.delegate = delegate;
    }

    @Override
    public AccessToken refreshAccessToken() throws IOException {
      return this.delegate.refreshAccessToken();
    }
  }
```
