### ISSUE TITLE
google-api-client needs to be updated

### ISSUE THREAD

**Issue by averikitsch** [firebase/firebase-admin-java#533]
This dependency relies on google-api-client v1.30.10 which conflicts with dependency: org.springframework.cloud:spring-cloud-gcp-dependencies:

```
java.lang.IllegalStateException: You are currently running with version 1.30.10 of google-api-client. You need at least version 1.31.1 of google-api-client to run version 1.31.0 of the Cloud SQL Admin API library.
```

**Comment by hiranya911** [comment]
You can specify a direct dependency on the version of google-api-client you require to avoid issues like this. 

> Dependency mediation - this determines what version of an artifact will be chosen when multiple versions are encountered as dependencies. Maven picks the "nearest definition". That is, it uses the version of the closest dependency to your project in the tree of dependencies. You can always guarantee a version by declaring it explicitly in your project's POM. Note that if two dependency versions are at the same depth in the dependency tree, the first declaration wins.

From https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#transitive-dependencies

**Comment by averikitsch** [comment]
Yes and that was the solution, but that's a bad experience if you expect everyone using Spring Boot + Google + this library to do that.
