### ISSUE TITLE
FR: Support for adding apps to a Firebase project from a CI server

### ISSUE THREAD

**Issue by visiolink-android-dev** [firebase/firebase-admin-java#54]
The CI server adds product flavors to our Android app. When a flavor is added, the project must be sync'ed 
using the Firebase plugin in Android Studio, so that the new flavor is added to the Firebase project and the new "google-services.json" file is downloaded to the project.

We would like to be able to do that without Android Studio. If it was added to this project, one could create a custom Gradle plugin or create a command line tool for the task and execute that from the CI server.

**Comment by hiranya911** [comment]
I don't see how this could be part of Admin SDK. Can you please elaborate? What would the API for this would look like?

**Comment by visiolink-android-dev** [comment]
Something like:

```
FirebaseApp.initializeApp(options)

FirebaseProject.createApp(project, packageName, nickname, debugCertificate)
InputStream stream = FirebaseProject.downloadJson(packageName)
```

Or should this be in the firebase-tools project instead?

**Comment by hiranya911** [comment]
Yeah, this doesn't look like it belong in the Admin SDK. Also the usecase/API suggested here seems very Android-specific. As you mentioned it should probably be done in a separate tool or a Gradle plugin. 

Try reporting this at https://github.com/firebase/firebase-tools (although I'm not sure whether that's the right place for this request either). I would also recommend you to reach out to the [firebase-talk](https://groups.google.com/forum/#!forum/firebase-talk) google group, where more Firebase devs can take a look at your requirement.

**Comment by visiolink-android-dev** [comment]
It was already there, so I posted a comment.

See:
https://github.com/firebase/firebase-tools/issues/319

You can close this issue.
