### ISSUE TITLE
Firebase does not send data and notification fields

### ISSUE THREAD

**Issue by Madina-S** [firebase/firebase-admin-java#552]
onMessageReceived(message: RemoteMessage) is called on Android device (Samsung A6+), but data and notification fields are null. 

Firebase admin version is 7.1.1, and the Android firebase bom version is 7.1.0

This how I am sending a message:
```
val builder = Message.builder()
                .setToken(it.firebaseToken)
                .putData(messageTypeKey, dto.message.type.constant)
                .putAllData(data)
                .setNotification(
                       Notification.builder()
                             .setTitle(title)
                            .setBody(content)
                            .build()
                )

 firebaseMessaging.send(builder.build())
```

My response and request:
```
POST https://fcm.googleapis.com/v1/projects/yool-caad4/messages:send
Accept-Encoding: gzip
Authorization: <Not Logged>
User-Agent: Google-HTTP-Java-Client/1.36.0 (gzip)
x-goog-api-format-version: 2
x-firebase-client: fire-admin-java/7.1.1
Content-Type: application/json; charset=UTF-8
Content-Length: 483

curl -v --compressed -X POST -H 'Accept-Encoding: gzip' -H 'Authorization: <Not Logged>' -H 'User-Agent: Google-HTTP-Java-Client/1.36.0 (gzip)' -H 'x-goog-api-format-version: 2' -H 'x-firebase-client: fire-admin-java/7.1.1' -H 'Content-Type: application/json; charset=UTF-8' -d '@-' -- 'https://fcm.googleapis.com/v1/projects/yool-caad4/messages:send' << $$$

{"message":{"data":{"id":"2","title":"Title","content":"Demo content"},"notification":{"body":"You have an request for reservation","title":"Reservation requested"},"token":"cLKTtB-eQGiqWe5pICTK9j:APA91bF89R7vM-nB-f05zwDbr32deP_Ykwo-wa0kW-4SNtt75sX1svs49j5oZbwV-5k9yd_Lium54_sQMqDNr8ANme_vf-d6ZmDd6ln6-JCwV4M8BX5uywMweLh59reJfNloXRuv8UYD"}}
```

My response:
```
 "name": "projects/***/messages/0:1620637393834568%a46f348da46f348d"
```

I have used MulticastMessage, sending message without setting notification and experimenting with device config, but no success.

**Comment by hiranya911** [comment]
Seems like should be reported on the Android SDK repo. From the log you can see that the Admin SDK has sent both the data and notification fields.

**Comment by chong-shao** [comment]
Hi @Madina-S normally filing a ticket at https://firebase.google.com/support is the best way for debugging a message send issue. Since you already provided your registration token, I'd like to ask for the send timestamp and I can query the backend logs for you.

**Comment by Madina-S** [comment]
Hi, thank you for your response. Now I tried to send again, time is 2021-05-26 12:21:37.884.

**Comment by chong-shao** [comment]
Hi @Madina-S , may I ask for the time zone of the time you mentioned

**Comment by Madina-S** [comment]
Hi, it is GMT+5

**Comment by chong-shao** [comment]
Hi Madina, I queried our backend logs for the time, I saw one entry with the matched time. But the log entry suggested that the message to the device was through topic publishing, not token send. 

I think a good step moving forward is to file a ticket though https://firebase.google.com/support and from there you can provide all your sample requests and ask our support team to debug it. It's difficult to do it here since the information you post on Github could be visible to the public.

Thanks!
