### ISSUE TITLE
Invalid registration token for new apns-push-type 'location'

### ISSUE THREAD

**Issue by ChristianOrgler** [firebase/firebase-admin-java#607]
### Describe your environment

  * Operating System version: **macOS Big Sir, 11.6**
  * Firebase SDK version (iOS): **8.6.0**
  * Library version (server): **8.1.0**
  * Firebase Product: **FCM Messaging**

### Describe the problem

Unable to send the "new" [location push notification](https://developer.apple.com/documentation/corelocation/cllocationmanager/creating_a_location_push_service_extension) to the APN server successfully.
The FCM token used was properly tested (after every step) to be able to send visible notifications via the Firebase console.

#### Steps to reproduce:

1. Tried to send a fcm message (normal and multicast) with the code below. The lines marked with `(x)` were tried to exchange to different values and or being omitted.
```
val message = MulticastMessage
            .builder()
            .addAllTokens(tokenList)
            .setApnsConfig(
                ApnsConfig.builder()
                    .setAps(
                        Aps.builder().setContentAvailable(true) // (x)
                            .build()
                    )
                    .putHeader("apns-push-type", "location")
                    .putHeader("apns-topic", "$iosBundleId.location-query")
                    .putHeader("apns-priority", "5") // (x)
                    .putHeader("apns-expiration", Instant.now().plus(3600, ChronoUnit.SECONDS).epochSecond.toString()) // (x)
                    .build()
            ).build()

firebaseMessaging.sendMulticast(message)
```

Receiving the FCM error "Invalid Argument" --> "Invalid registration token". Yet the token is valid, testing it via the Firebase console and sending a visible notification through my own server's code. It appears Firebase is restricting this before trying to send the request to the APN server.

Is there any setting, scope or something similar missing to be able to send the location-query push notification through Firebase?

**One observation I had was that the token changes from having a prefix seperated by a colon.**

### Relevant Code

**Request**
```
POST https://fcm.googleapis.com/v1/projects/fairenough/messages:send HTTP/1.1
Content-Length: 683
Content-Type: application/json; charset=UTF-8
x-goog-api-format-version: 2
x-firebase-client: fire-admin-java/8.1.0

{"message":{"apns":{"headers":{"apns-push-type":"location","apns-topic":"<bundle-id>.location-query","apns-expiration":"1635411540","apns-priority":"5"},"payload":{"aps":{"content-available":1}}},"data":{"eventId":"93e7728d-9f5e-4acf-b3d4-b69f671a1599","confirmationNeeded":"false","id":"1552","type":"Information","category":"AdhocLocationRequest","entity":"LocationRequests"},"token":"fHddGiu7MENDjdl3-ycL6I:APA91bHvfqSAR3dg2t19Z7moAtM62CEi_fHz6QvDC7KlIujzYVL7LjXoZyM_2RSKSK-KtkYCQUYhOmXU9uY-czMOqFH9bwx-3MbF1jUYFky9ETZq6ZEllugE*******************"}}
```

**Response**
```
Content-Type: application/http
Content-ID: response-1

HTTP/1.1 400 Bad Request
Vary: Origin
Vary: X-Origin
Vary: Referer
Content-Type: application/json; charset=UTF-8

{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.firebase.fcm.v1.FcmError",
        "errorCode": "INVALID_ARGUMENT"
      },
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "field": "message.token",
            "description": "Invalid registration token"
          }
        ]
      }
    ]
  }
}
```

**Comment by chong-shao** [comment]
Hello @ChristianOrgler, thanks for the post. the FCM team looked at the newly launched Apple Location Push Service Extension feature. We confirmed that currently FCM does not support this feature: it requires some significant system change on the FCM side for FCM to support this feature. 

We are currently investigating on adding this feature. I think for now in the short term we may want to update the error message to reduce confusion.

**Comment by chliangGoogle** [comment]
@ChristianOrgler Would you file a feature request on this so we can also see how many developers want the same feature like you.

**Comment by ChristianOrgler** [comment]
Thanks for investigating! Yes I will create a ticket right away and reference it here again.

Would you be able to go give a rough timeline in case this feature is wanted by others as well? (to plan if I need to support it on my own until then or I would be able to wait (and contribute if requested)

**Comment by chliangGoogle** [comment]
@ChristianOrgler We haven't received many requests by others yet which is why it would be helpful to file a separate feature request so others can vote on. Currently this effort is not prioritized given low volume of demands.

**Comment by ChristianOrgler** [comment]
Hi @chliangGoogle - is this request: 10155562 fine or should I create a new one?

**Comment by chliangGoogle** [comment]
@ChristianOrgler better to create a new one so other developers can search and upvote it.

**Comment by ChristianOrgler** [comment]
Ok @chliangGoogle - via this [link](https://firebase.google.com/support/troubleshooter/report/features) or here at GitHub?

**Comment by chliangGoogle** [comment]
@ChristianOrgler No, still via github. Here's an example: https://github.com/firebase/firebase-ios-sdk/issues/8968

**Comment by ChristianOrgler** [comment]
Created: https://github.com/firebase/firebase-admin-java/issues/620 - how do people upvote on it?

**Comment by chliangGoogle** [comment]
@ChristianOrgler they can upvote by clicking on the emoji. 
Thank you for filling the feature request!
