### ISSUE TITLE
Dependency Issue : io.netty

### ISSUE THREAD

**Issue by dhakaji** [firebase/firebase-admin-java#612]
Latest version of firebase (8.1.0) uses some older versions of io.netty dependencies. Due to which we are getting security issues. Can we get the dependencies updated in next release. Or someone can help with some workaround ?

**Comment by hiranya911** [comment]
You don't have to wait for us to upgrade a transitive dependency. Just specify the Netty version you want as a direct dependency of your project. Build tools like Maven and Gradle will always prioritize that.

We have already bumped our Netty version to 4.1.68 in the main branch. This will be included in the next release.

**Comment by dhakaji** [comment]
It helped. Thnks @hiranya911 for quick reply. Appreciate it.
