### ISSUE TITLE
FR: OSGI Metadata Support

### ISSUE THREAD

**Issue by cdecode** [firebase/firebase-admin-java#62]
Is it possible to make the Firebase Admin SDK compatible with OSGI ?

The minimal requirements would be to add OSGI metadata to the manifest.
To go further, you could rely on the OSGI service model, here is a project example : 

[https://github.com/cdecode/org.cdecode.firebase](https://github.com/cdecode/org.cdecode.firebase)

In this project the API was redefined to not expose internal classes to consumers, the implementation is based on the version 5.2.0 of firebase and can be configured in an OSGI way.

The avantage of this will be firstly to support a new runtime environment, and secondly, if you go further, to minimize the impact on the consumer bundles.

**Comment by cdecode** [comment]
Here is the project : [https://github.com/cdecode/org.cdecode.firebase](https://github.com/cdecode/org.cdecode.firebase)

**Comment by hiranya911** [comment]
We can add the required OSGi bundle headers  to the build artifact (perhaps you can help us with that by providing a patch).

**Comment by cdecode** [comment]
Some of the dependencies are not bundles. They will have to be included in the firebase artifact or they can be converted to bundles in another module and released together with firebase.

Also, note that all packages will be exported (public) and so must be consistently versionned.

**Comment by hiranya911** [comment]
We will need some community support to implement and test this. Feel free to reopen and follow up if you're interested.
