### ISSUE TITLE
[FR] Add Argon2 support to Java Admin SDK

### ISSUE THREAD

**Issue by ssbushi** [firebase/firebase-admin-java#636]
**Is your feature request related to a problem? Please describe.**
Argon2 Hashing algorithm is now supported by GCIP/Firebase Auth BE ([Public docs](https://cloud.google.com/identity-platform/docs/reference/rest/v1/projects.accounts/batchCreate)). This should be supported in the Admin SDKs too.

**Describe the solution you'd like**
Add Argon2 Hash class along with other existing supported hash algorithms like Scrypt/Hmac,etc.

**Describe alternatives you've considered**
N/A

**Additional context**
API Proposal (Internal): [go/firebase-auth-argon2-admin](http://go/firebase-auth-argon2-admin)

**Comment by lahirumaramba** [comment]
Released in v8.2.0
