### ISSUE TITLE
com.google.cloud:libraries-bom dependency needs to be upgraded in pom.xml

### ISSUE THREAD

**Issue by dconeybe** [firebase/firebase-admin-java#678]
The dependency on `com.google.cloud:libraries-bom` in `pom.xml` is almost one year old, and needs to be upgraded.

It looks like "dependabot" has not been doing its job, since the last time it bumped the bom was almost one year ago in July 2021: https://github.com/firebase/firebase-admin-java/pull/583

pom.xml currently uses bom version 20.9.0, but the latest version is 25.3.0.

upgrading is highly desirable to pick up the following fix: https://github.com/googleapis/java-firestore/pull/875

Note that I am a Googler. Feel free to DM me at dconeybe@ or comment on b/232419509

**Comment by dconeybe** [comment]
Here is the part of pom.xml that uses the old bom:

https://github.com/firebase/firebase-admin-java/blob/14c7ade015fb98b18bf51637c718b86ed162b3af/pom.xml#L386-L388

**Comment by lahirumaramba** [comment]
Thank you @dconeybe! This issue is on the top of my list. It seems like upgrading the BOM breaks our CIs on Java 7. We will most likely have to drop support for Java 7 (a breaking change) before upgrading the `com.google.cloud:libraries-bom`. We are currently planning this major release of the SDK.

**Comment by lahirumaramba** [comment]
This is now fixed in v9.0.0. Thank you!

**Comment by dconeybe** [comment]
Awesome. Thanks @lahirumaramba!
