### ISSUE TITLE
Firebase Database Query hangs

### ISSUE THREAD

**Issue by Motojo** [firebase/firebase-admin-java#68]
Hello! 
# Enviroment
  * Operating System version: Windows 8.1u1
  * Firebase SDK version: 5.3.0
  * Firebase Product: Database

# Issue 
When  I trying to get some info from the database and the query contains some of startAt, endAt, equalTo the query hangs and the thread keeps workings and my method cant return anything...

**Event Listeners removed for simplicity, can be reproduced with or without them** 

**example**: only the String "before query" is printed, then the nothing happens, it hangs
```
FirebaseDatabase db = FirebaseDatabase.getInstance();
System.out.println("before query");
db.getReference("/some/path/").orderByChild("pending").equalTo(true);
System.out.println("after query");
```
But, if I remove the "equalTo" condition the mehtod executes normally
**example**: both strings are printed and the data is retreived without any problem.

```
FirebaseDatabase db = FirebaseDatabase.getInstance();
System.out.println("before query");
db.getReference("/some/path/").orderByChild("pending");
System.out.println("after query");
```

------------------------------------------
edit: I don't know if this is useful, but if I try the same query on the node.js  enviroment it works and my data is retrieved without any problem

**Comment by katowulf** [comment]
Most likely, you haven't set up an index on the remote path and it's attempting to download all data to the client. You will need to add an error handler as described in the docs to get the exact error condition, but the query is likely timing out after a [read limit](https://firebase.google.com/docs/database/usage/limits) is reached.

One quick way to test this would be to run the same query against a sample path with only a few records. If you can reproduce it there, and you can demonstrate that you've added proper error handlers to the query and still aren't making progress, then please resubmit this issue with a **minimal and complete** repro of the problem, including sample data and security rules, we can run locally.
