### ISSUE TITLE
Library size with dependencies

### ISSUE THREAD

**Issue by tananaev** [firebase/firebase-admin-java#699]
The library with all dependencies is really big. I only want to use Firebase push notifications. Can I exclude any dependencies to reduce the size?

**Comment by tananaev** [comment]
Is it safe to exclude `google-cloud-firestore` like this if I'm only interested in the Firebase push notifications?
```
    implementation ("com.google.firebase:firebase-admin:9.0.0") {
        exclude group: 'com.google.cloud', module: 'google-cloud-firestore'
    }
```

**Comment by TomBeckett** [comment]
@tananaev YMMV but I've excluded it and it seemed okay:

```xml
  <dependency>
      <groupId>com.google.firebase</groupId>
      <artifactId>firebase-admin</artifactId>
      <version>${firebaseAdmin.version}</version>
      <exclusions>
          <exclusion>
              <groupId>com.google.cloud</groupId>
              <artifactId>google-cloud-firestore</artifactId>
          </exclusion>
      </exclusions>
  </dependency>
```

**Comment by tananaev** [comment]
Yeah, I also tried it earlier and it works, but just wanted to confirm that there are no corner cases that will fail with class not found exceptions 🙂

**Comment by TomBeckett** [comment]
Yup I would not say its officially supported but works 🤷‍♂️

**Comment by lahirumaramba** [comment]
Hey everyone, thanks for your patience on this. We have had some previous discussions on the library size (see #273), and as you mentioned above, using Maven exclusions is the correct way to remove the unwanted dependencies for your project. Gradle supports the same feature if that is your build tool. You should be able to exclude `google-cloud-storage` and `google-cloud-firestore` (assuming you don't use any of those APIs in your project) without any issue, plus some of the `netty-*` dependencies as well. See below for an example:

```
<dependency>
      <groupId>com.google.firebase</groupId>
      <artifactId>firebase-admin</artifactId>
      <version>6.8.1</version>
      <exclusions>
        <exclusion>
          <groupId>com.google.cloud</groupId>
          <artifactId>google-cloud-firestore</artifactId>
        </exclusion>
        <exclusion>
          <groupId>com.google.cloud</groupId>
          <artifactId>google-cloud-storage</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-codec-http</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-handler</artifactId>
        </exclusion>
        <exclusion>
          <groupId>io.netty</groupId>
          <artifactId>netty-transport</artifactId>
        </exclusion>
      </exclusions>
</dependency>
```

**Comment by sryze** [comment]
@lahirumaramba In 9.2.0 and 9.1.1, if I exclude `google-cloud-storage` it results in a `java.lang.ClassNotFoundException: com.google.api.client.json.jackson2.JacksonFactory` error because `com.google.firebase.internal.ApiClientUtils` uses it.

Could you please add an explicit dependency on `com.google.api.client.json.jackson2`?
