### ISSUE TITLE
Deserializing BigDecimal throws exception

### ISSUE THREAD

**Issue by CluEleSsUK** [firebase/firebase-admin-java#75]
Inside `CustomClassMapper` in method `deserializeToClass(Object obj, Class<T> clazz)`, the conditional statement wrongly assumes the value is of primitive type if `Number.class.isAssignableFrom(clazz)`.
BigDecimal returns true but is not primitive, and throws an `IllegalArgumentException` in `deserializeToPrimitive(Object obj, Class<T> clazz)`

**Comment by hiranya911** [comment]
Thanks for pointing this out @CluEleSsUK. If you can please provide us a pull request to fix this. Otherwise I will take a look in a couple of days.

**Comment by CluEleSsUK** [comment]
Sure thing, I'll have a look tomorrow!

**Comment by ghajba** [comment]
A question to this topic: how should a BigDecimal/BigInteger be serialized?

I am currently facing the same issue, and I want to fix it, but I don't just want to hack something together.

**Comment by schmidt-sebastian** [comment]
We are taking a look at this internally as this affects Android as well.

**Comment by schmidt-sebastian** [comment]
I have pushed PRs to provide better error messages. Unfortunately, this will only marginally improve your experience with BigDecimal/BigInteger. Our backend does not support integer precision for numbers that exceed the 64bit signed range. If you do need to store larger numbers, please use "double" instead.

**Comment by hiranya911** [comment]
@schmidt-sebastian are you going to implement any changes in the Admin SDK code?

**Comment by schmidt-sebastian** [comment]
We are only updating our error messages: https://github.com/googleapis/google-cloud-java/pull/4675

**Comment by hiranya911** [comment]
As of now we don't plan to support serialization of these types in RTDB. But we can revisit this issue if there's more interest.
