### ISSUE TITLE
java.lang.NoSuchMethodException: com.google.auth.oauth2.ServiceAccountCredentials.getQuotaProjectId()

### ISSUE THREAD

**Issue by lpellegr** [firebase/firebase-admin-java#753]
In a micronaut (3.8.0) Java app, bundled as native GraalVM app, using the dependency `com.google.firebase:firebase-admin` to perform a simple Firestore get, fails at runtime.

Gradle dependencies are as follows:

```
annotationProcessor 'org.projectlombok:lombok:1.18.24'
compileOnly 'org.projectlombok:lombok:1.18.24'

implementation platform('com.google.cloud:libraries-bom:26.2.0')

implementation 'io.micronaut:micronaut-http-server-netty'
implementation 'io.micronaut:micronaut-inject'
implementation 'io.micronaut:micronaut-runtime'

implementation 'ch.qos.logback:logback-classic'
implementation 'com.google.firebase:firebase-admin'
implementation 'io.noticeable:noticeable-indexes:7.0.7'
implementation 'javax.annotation:javax.annotation-api:1.3.2'
```

The dependency tree is the following:
https://gist.github.com/lpellegr/1e3042cf0395c64731b6d5822dc85f63

The stack trace:

> java.lang.NoSuchMethodException: com.google.auth.oauth2.ServiceAccountCredentials.getQuotaProjectId() at java.lang.Class.getMethod(DynamicHub.java:2227) at io.grpc.auth.GoogleAuthLibraryCallCredentials$JwtHelper.<init>(GoogleAuthLibraryCallCredentials.java:318) at io.grpc.auth.GoogleAuthLibraryCallCredentials.createJwtHelperOrNull(GoogleAuthLibraryCallCredentials.java:224) at io.grpc.auth.GoogleAuthLibraryCallCredentials.<clinit>(GoogleAuthLibraryCallCredentials.java:53) at io.grpc.auth.MoreCallCredentials.from(MoreCallCredentials.java:35) at com.google.api.gax.grpc.GrpcCallContext.withCredentials(GrpcCallContext.java:160) at com.google.api.gax.grpc.GrpcCallContext.withCredentials(GrpcCallContext.java:67) at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:206) at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:132) at com.google.cloud.firestore.spi.v1.GrpcFirestoreRpc.<init>(GrpcFirestoreRpc.java:127) at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:88) at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreRpcFactory.create(FirestoreOptions.java:80) at com.google.cloud.ServiceOptions.getRpc(ServiceOptions.java:564) at com.google.cloud.firestore.FirestoreOptions.getFirestoreRpc(FirestoreOptions.java:358) at com.google.cloud.firestore.FirestoreImpl.<init>(FirestoreImpl.java:79) at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreFactory.create(FirestoreOptions.java:71) at com.google.cloud.firestore.FirestoreOptions$DefaultFirestoreFactory.create(FirestoreOptions.java:64) at com.google.cloud.ServiceOptions.getService(ServiceOptions.java:544) at com.google.firebase.cloud.FirestoreClient.<init>(FirestoreClient.java:55) at com.google.firebase.cloud.FirestoreClient.<init>(FirestoreClient.java:32) at com.google.firebase.cloud.FirestoreClient$FirestoreInstances.lambda$get$0(FirestoreClient.java:150) at java.util.HashMap.computeIfAbsent(HashMap.java:1220) at java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2760) at com.google.firebase.cloud.FirestoreClient$FirestoreInstances.get(FirestoreClient.java:150) at com.google.firebase.cloud.FirestoreClient.getInstance(FirestoreClient.java:121) at com.google.firebase.cloud.FirestoreClient.getFirestore(FirestoreClient.java:98) at com.google.firebase.cloud.FirestoreClient.getFirestore(FirestoreClient.java:83) at io.noticeable.widgets.data.FirebaseService.getFirestore(FirebaseService.java:21) at io.noticeable.widgets.data.ApplicationService.getPublications(ApplicationService.java:123) at io.noticeable.widgets.data.ApplicationController.publications(ApplicationController.java:60) at io.noticeable.widgets.data.$ApplicationController$Definition$Exec.dispatch(Unknown Source) at io.micronaut.context.AbstractExecutableMethodsDefinition$DispatchedExecutableMethod.invoke(AbstractExecutableMethodsDefinition.java:378) at io.micronaut.context.DefaultBeanContext$4.invoke(DefaultBeanContext.java:594) at io.micronaut.web.router.AbstractRouteMatch.execute(AbstractRouteMatch.java:303) at io.micronaut.web.router.RouteMatch.execute(RouteMatch.java:111) at io.micronaut.http.context.ServerRequestContext.with(ServerRequestContext.java:103) at io.micronaut.http.server.RouteExecutor.lambda$executeRoute$14(RouteExecutor.java:659) at reactor.core.publisher.FluxDeferContextual.subscribe(FluxDeferContextual.java:49) at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62) at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194) at io.micronaut.reactive.reactor.instrument.ReactorInstrumentation.lambda$init$0(ReactorInstrumentation.java:62) at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84) at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37) at io.micronaut.scheduling.instrument.InvocationInstrumenterWrappedCallable.call(InvocationInstrumenterWrappedCallable.java:53) at java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) at java.lang.Thread.run(Thread.java:833) at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705) at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)

As you can see, the latest BOM version is used. I think this is a dependency issue or a GraalVM configuration that is missing from one Google library. 

Would appreciate knowing if there is a workaround.

**Comment by lpellegr** [comment]
By forcing to use `com.google.firebase:firebase-admin:9.1.0` and Micronaut`3.7.5`, the app works. 

The issue seems to come from recent versions of dependencies that pull a not-compatible google auth library version.

**Comment by lahirumaramba** [comment]
Hi @lpellegr , Thank you for reporting this issue.

Looks like a known issue in [libraries-bom-v26.4.0](https://github.com/googleapis/java-cloud-bom/releases/tag/libraries-bom-v26.4.0). This should be fixed in the next release of `libraries-bom`.

In the meantime try pinning the `com.google.cloud:libraries-bom` version to `26.3.0`.
