### ISSUE TITLE
Exceptions swallowed in snapshot.getValue()

### ISSUE THREAD

**Issue by drindt** [firebase/firebase-admin-java#79]
I was looking for hours why getValue doesn't return anything. The thread dies in the background silently. First as i step debug the code i've seen that some things must be present in the pojos like empty constructor and getters at least. I don't know why the exception is swallowed. I just can assume that google endpoints hide it from my eyes. I am using firebase with cloud endpoints together.

**Comment by hiranya911** [comment]
Is this in an event handler? I believe this is because `ThreadPoolEventTarget` class does not log errors by default.
