### ISSUE TITLE
Error: Could not find or load main class in .jar file

### ISSUE THREAD

**Issue by Psijic** [firebase/firebase-admin-java#845]
The error happens after running the .jar:

`Error: Could not find or load main class MainKt`

It looks like the problem appears because of firebase:

`implementation("com.google.firebase:firebase-admin:9.2.0")`

Adding it in an empty project provides this error while all is ok without this dependency.

**Comment by Psijic** [comment]
Seems ok after updating Java from 17 to 19.

**Comment by lahirumaramba** [comment]
It seems like you have resolved the issue. I will close this for now. We can reopen later if needed. Thanks!
