### ISSUE TITLE
HttpRequest with 0 write timeout may make program hangs

### ISSUE THREAD

**Issue by meor9zcu12** [firebase/firebase-admin-java#850]
### Problem encountered:
When under high traffic, FCM admin SDK will throw some errors like:

> Error 1. com.google.firebase.messaging.FirebaseMessagingException: Unexpected HTTP response with status: 408

> Error 2. com.google.firebase.messaging.FirebaseMessagingException: Unknown error while making a remote service call: Unexpected end of file from server

> Error 3. com.google.firebase.messaging.FirebaseMessagingException: Unknown error while making a remote service call: Connection timed out (Connection timed out)

At the same time, after throwing these errors, FCM admin SDK may still make java program never stop because of FCM admin SDK still waiting response from [fcm.googleapis.com](fcm.googleapis.com)

### Findings:
FCM admin uses com.google.http-client, which writeTimeout = 0 by default, [link](https://github.com/googleapis/google-http-java-client/blob/13edd1357eb79535d943f5288ab3adf4d9dfb52a/google-http-client/src/main/java/com/google/api/client/http/HttpRequest.java#L154)

I can't find how [ErrorHandlingHttpClient ](https://github.com/firebase/firebase-admin-java/blob/master/src/main/java/com/google/firebase/internal/ErrorHandlingHttpClient.java#L92) to set writeTimeout, it may be one of result that make program keep waiting response from [fcm.googleapis.com](fcm.googleapis.com) under high traffic.

**Comment by TheRittler** [comment]
I think we also ran into this Issue. Are there any news on this topic?

**Comment by chong-shao** [comment]
Sorry for the delay in reply. We are currently investigating this issue. Will update here later.

**Comment by GarreltMock** [comment]
Any updates here?
