### ISSUE TITLE
Unknown error while making a remote service call: Remote host closed connection during handshake

### ISSUE THREAD

**Issue by wchenwei** [firebase/firebase-admin-java#859]

**Comment by lahirumaramba** [comment]
Please provide more details, error logs, a minimal repro, etc., on the issue you are facing so we can help you better. Please use StackOverflow for usage questions. Thanks!

**Comment by sarismet** [comment]
@lahirumaramba I have encountered the same issue when I tried virtual threads in ThreadManager in firebase-app. I have shared a post in [stackoverflow](https://stackoverflow.com/questions/78605839/java21-virtual-thread-in-firebase-admin-java). I think this errors are related to rate limit of FCM but in that case I expect the errors regarding to rate limit such as 429 http status code but I could not see these in exception.

The error "Remote host closed connection during handshake" comes from java itself not from FCM.
