### ISSUE TITLE
[FR] Add HTTP2 support for sendEach() and sendEachForMulticast()

### ISSUE THREAD

**Issue by honorhs** [firebase/firebase-admin-java#973]
When will HTTP/2 support be available for methods like sendEach() and sendEachForMulticast() in the Firebase Admin Java SDK? 

It appears that this support has already been implemented in firebase-admin-node. 
https://github.com/firebase/firebase-admin-node/releases/tag/v12.3.0

I was informed that after implementing HTTP/2 in firebase-admin-node, the same would be applied to firebase-admin-java.
https://github.com/firebase/firebase-admin-java/issues/834#issuecomment-2108825607

Thank you.

**Comment by honorhs** [comment]
@lahirumaramba @jonathanedey

**Comment by jhkim-grip** [comment]
#834 show that api deprecation is started but where is the http2 support?

**Comment by ratuka** [comment]
It would have been nice to release a new version before the deprecation.

**Comment by lahirumaramba** [comment]
This will be addressed in https://github.com/firebase/firebase-admin-java/pull/979

**Comment by jonathanedey** [comment]
HTTP/2 support has now been added with the release of [v9.4.0](https://github.com/firebase/firebase-admin-java/releases/tag/v9.4.0). 
See [our wiki](https://github.com/firebase/firebase-admin-java/wiki/HTTP-Transport) for more information on this change.
