### ISSUE TITLE
Issue Same Fcm Fired from Firebase consode but not work from node js

### ISSUE THREAD

**Issue by Chandan1998788** [firebase/firebase-admin-java#988]
i used node js for custom notification for android and ios but for ios i faced issue Error sending notification: {
  error: {
    code: 404,
    message: 'Requested entity was not found.',
    status: 'NOT_FOUND',
    details: [ [Object] ]
  }
}.
-But same fcm token fired from firebase console send notification

**Comment by lahirumaramba** [comment]
This is the repo for Firebase Admin Java SDK. If you are facing an issue with the Node.JS SDK please open a new issue on https://github.com/firebase/firebase-admin-node and provide us with error logs and/or a minimal repro.

Please use StackOverflow for usage questions.
