### ISSUE TITLE
a large number of threads will be created when use sendEach api

### ISSUE THREAD

**Issue by ffyyhh995511** [firebase/firebase-admin-java#994]
firebase-admin-java, the version is 9.3.0. When sendEach api is used to push tens of thousands of tokens, a large number of threads will be created, resulting in a high cpu. How do I solve the problem

**Comment by lahirumaramba** [comment]
We are working on adding http/2 support to `sendEach` to solve this issue and improve performance. In the meantime, you can try implementing your own code to use the REST endpoints with http/2. We will track any progress on this here https://github.com/firebase/firebase-admin-java/pull/979
